README.md
After deploying and logging in, noticed a few things that look like problems that are expected - we should point these out in the README
This is also testing the CircleCI integration
* Update README
* CI
=> README updates after test deployment

internal/log_analysis/rules_engine/src/engine.py
If the UI pushes incomplete records into ddb, then the rule engine crashes
Added logging and validation for all keys referenced
Testing by deploying with incomplete ddb records.
=> [ENG-1317] Fix missing validations in rule loading

deployments/panther_config.yml
New version of analysis is up that contains bug fixes. 
* Point to the latest release
=> Changed configuration to use latest rules

deployments/web/Dockerfile
Make sure to use the locked versions of the packages and not the latest ones 
* Add `package-lock.json` to docker context
* Locally
=> add package-lock.json to Docker context

README.md
Closes #19 
* Add the FOSSA badge
* Looking in the README
=> Fossa Badge

.eslintrc
This PR resolves a request from @austinbyers and @nhakmiller to display what went wrong when front-end validations fail on our CI. This is indeed important for future contributors
* Feed prettier rules into ESLint rules
* Locally
=> [ENG-1351] Display frontend errors

docs/gitbook/README.md
=> Remove exclaimation to confirm gitbook syncing

docs/gitbook/README.md
=> 2nd test to verify github syncing

package-lock.json, package.json, web/webpack.config.js
As the time passes, packages gets deprecated and configurations change. This PR simply bumps out front-end building tool to its latest version and makes sure that all of its options create value for the project.
* Bump `webpack` and `webpack-dev-server`
* Remove any un-needed hot reloads from the configuration
* Remove some default values from the config
* Remove workbox, since we are not (and will not for the near future) be using a service worker for our app.
* Locally
=> [Build] Cleanup & update webpack config

pkg/awsglue/integration_test.go
=> Fix glue integration test name so it runs from mage test:integration

internal/core/analysis_api/handlers/get.go, internal/core/analysis_api/handlers/util.go
On most failures no error message was being set.
Manually in dev env
=> Improve error messages for analysis api

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Add Feature Request to templates
=> Update issue template

web/README.md
Fix small inconsistencies in the web's README 
* Update README.md
None required
=> [Docs] Update web docs

docs/gitbook/SUMMARY.md, docs/gitbook/historical-search/example-queries.md
Historical search doc edits. 
1) Fix indentation in SUMMARY.md 
2) refine RunInstances example query
=> Minor historical search doc edits. 

docs/gitbook/historical-search/README.md, docs/gitbook/historical-search/example-queries.md
I was reading published doc via Panther app and noticed places that needed editing.
=> Minor edits to historical search documentation

docs/gitbook/development.md, docs/gitbook/quick-start.md
Updating the docs to reference 0.2.0 instead of 0.1.1
=> Bump version to 0.2.0 in documentation

README.md
=> Fixes grammar in readme

internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go, internal/log_analysis/log_processor/sources/s3_client_cache.go
Update to check http status code range if not null
mage test:go
=> S3access validate http status if not null

deployments/backend.yml, deployments/core/appsync.yml, requirements.txt
Appsync released an X-Ray integration a couple of days ago. This PR allows Appsync actions (queries/mutations) to be analyzed using X-ray
- Enable X-Ray for Appsync
Successfully deployed to dev account
=> [Feature] Add x-ray to appsync

web/src/components/forms/user-invitation-form/index.tsx
This PR fixes an issue when interacting with the role dropdown in the user invitation page.
Closes #179 
- Force front-end email Validation
- Fix typo in lists
- Locally on all edge cases
=> Fix user dropdown bug

internal/log_analysis/rules_engine/src/main.py
@rleighton  identified an issue with current alerting mechanism. The issue was introduced in https://github.com/panther-labs/panther/pull/182 
- Fixing message the rules engine sends to the alert merger
- Deployed and verified locally that it works. 
- This change affected part of the code that was previously untested and also will be removed within the next couple of weeks
=> Fixing bug in the new code

web/src/components/auth-page-container.tsx
Fix the login page filler text on the left side, it was out of date.
- Made changes in the browser, then edited the relevant files
=> [login page] edit text on left side of auth page

.fossa.yml
An updated FOSSA configuration to include all project libraries
- A newly generated FOSSA config (via `fossa init`) to cover Python, Node, and Golang
- Validated by running `fossa analyze --output`, which does not send results to the API
=> Complete FOSSA Configuration

docs/gitbook/historical-search/README.md
updating documentation
formatting and grammatical changes. replace compliance with cloud security
=> Update Historical Search Docs Page

package-lock.json, package.json
This PR fixes an issue where the central numbers of the donut charts were not being shown.
Closes #112 
- Change echarts version
- Locally
=> Fix donut chart numbers

README.md
One final edit
- Wording tweak in the 'why panther' section
- Atom
=> [docs] why panther? update

internal/log_analysis/log_processor/parsers/osquerylogs/status.go, internal/log_analysis/log_processor/parsers/osquerylogs/status_test.go
* make LogType optional
* add test for events currently failing
mage test:ci
=> osquery:status - make logType field optional

api/gateway/analysis/configmodels.go, internal/core/analysis_api/handlers/bulk_upload.go
Setting default dedup time period for rules uploaded through bulk upload
- Added default value
- Deployed and verified value is set to default for rules
=> Putting default value for bulk uploads

tools/mage/teardown.go
Fix clearing of s3 event notifications and add delay before deleting bucket bucket in mage:teardown
The api to clear event notifications requires an empty config struct to clear (not nil). Documentation was not clear. 
* Added empty config doc to api call, moved to section of code where we leave the bucket
* Added short delay before deleting bucket as I have experienced errors here saying bucket was not empty (but it was). This forced me to run teardown again (annoying). This delay make this much less likely.
Changed code to _just_ remove notifications (not delete bucket), ran, checked bucket in console to confirm notifications were not configured.
mage:teardown
=> Fix clearing of s3 event notifications and add delay before deleting bucket in mage:teardown

tools/dashboards/infra.go
analysis api was forgotten in cloudsec dashboard.
- added analysis api
deployed to dev account, checked
=> Add analysis_api to cloudsec dashboard

web/src/helpers/fireworks.ts
A lot of PRs just landed! This change is just applying a final pass of `mage fmt` in order to make sure everything is up to date.
- Ran `mage fmt`
=> Formatting

docs/gitbook/historical-search/README.md, docs/gitbook/historical-search/panther-fields.md
Final edits for historical search
- List all databases
- Cleanup headers
- Atom
=> [docs] final historical search edits

internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164_test.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424_test.go, web/src/constants.ts
- Add fluentd parsers to UI
- mage fmt
mage test:ci
deployed to dev account, saw tables in Athena
=> Add fluentd parsers to UI and run fmt

docs/gitbook/SUMMARY.md, docs/gitbook/log-analysis/supported-logs/fluentdsyslog.md
https://github.com/panther-labs/panther/issues/437
add fluentd syslog parser docs
=> add fluentd syslog parser docs

docs/gitbook/SUMMARY.md
- Fix broken link in summary for writing log parsers (file moved in previous commit)
=> Fix broken link in summary for writing log parsers (file moved in previous commit)

.all-contributorsrc
Fix UI issue with all-contributors badge in README 
- Add custom badge template
- README preview
=> add custom badge template

README.md
Forcing badge update until a new contributor joins in and creates a badge update
- Update README
- README preview
=> Force README update

.all-contributorsrc
PRs from all-contributors bots should pass through CI, since it's a required step for merging PRs
- Alter all-contributors configuration
- N/A
=> Force CI to run bot changes

internal/log_analysis/log_processor/parsers/osquerylogs/differential.go, internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go
Fixes #383 
For more details see issue. 
- Populating AnyIP fields for OsQuery differential
- Got samples of logs from existing installation, added unit tests.
=> Added enrichment of ip fields

docs/gitbook/log-analysis/log-processing/README.md
Fix incorrect endpoint in log processing SNS setup doc reported by customer.
=> Fix incorrect endpoint in log processing SNS setup doc

package-lock.json, package.json, web/src/pages/Users/Users.tsx
Bump pounce to latest 
- Fix typo
- Bump pounce to latest
=> bump pounce to latest

package-lock.json
This PR makes sure to bump the patch versions of our dependencies
- Update locked deps
- Site works
=> Bump patch versions 

web/src/constants.ts
Updated the link to our docs from the app dashboard.
=> Updated link to docs

internal/log_analysis/log_processor/destinations/s3_test.go, pkg/awsglue/glue.go
@dev reported on the Panther OSS Slack channel that running the test suite with -race flags issues.
The following files have reported issues:
internal/log_analysis/log_processor/destinations/s3_test.go
pkg/awsglue/glue.go
See: https://github.com/panther-labs/panther/issues/656
This test file had a test that was timing related. The -race made the timing related test not work. 
I change the test to use a signal on a channel rather than sleep and -race was happy.
This was a real data race caught, where the function was mutating shared data passed by the caller.
The fix was to copy , then mutate.
The first change in this function was to copy data returned from glueClient.GetPartition() before mutation.
The issue here is not the code,  but the test driver which returns the same results for all …
=> Fix data races found by testing with -race

internal/compliance/aws_event_processor/processor/process.go
- Whitelist cognito:ForgotPassword in event processor
mage test:ci
=> Whitelist cognito:ForgotPassword in event processor

internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go, internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go
- Add RecipientAccountID to panther fields (was missing)
- nil check on UserIdentity (not technically needed since UserIdentity is required BUT if we ever changed that , then w/out this change the code would panic
mage test:ci
=> Minor fixes for CT parser

internal/compliance/aws_event_processor/processor/process.go
- Whitelist cognitio:UpdateUserAttributes for event processor
mage test:ci
=> Whitelist cognitio:UpdateUserAttributes for event processor

cmd/opstools/s3queue/integration_test.go, cmd/opstools/s3queue/s3queue.go, cmd/opstools/s3queue/s3queue/main.go
- Detect the region of a bucket and use in session to allow cross region execution
mage test:ci
ran integration tests
testest in demo env
=> Add bucket region detection to s3queue

cmd/opstools/s3queue/s3queue/main.go
Add region to the output messages so it is clear where you are running.
mage test:ci
ran on dev desktop
=> Improve logging for s3queue

internal/core/source_api/api/get_integration_template.go
Previous PR forgot to bump version key in backend.
=> Bump template version in source api backend

docs/gitbook/enterprise/snowflake.md
typo in line 17: `myaccoutid` to `myaccountid`
=> fixed "accountid" typo

api/lambda/source/models/api.go, docs/gitbook/log-analysis/log-processing/supported-logs/GCP.md, internal/core/source_api/api/check_integration.go, internal/core/source_api/api/delete_integration.go, internal/core/source_api/api/delete_integration_test.go, internal/core/source_api/api/get_integration_template.go, internal/core/source_api/api/get_integration_template_test.go, internal/core/source_api/api/list_integrations.go, internal/core/source_api/api/list_integrations_test.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/put_integration_test.go, internal/core/source_api/api/sqs_utils.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/update_integration_test.go, internal/core/source_api/api/vars.go, internal/core/source_api/api/vars_test.go, internal/core/source_api/main/handler.go, internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go, tools/mage/deploy_onboard.go
Several style improvements
- Several style improvements 
- `mage deploy`
=> Several minor improvements

internal/log_analysis/rules_engine/src/main.py, internal/log_analysis/rules_engine/tests/test_main.py
Fixes #832 
- Fixes error identified during QA
- Updated unit test
- Deployed and verified in my account.
Error message before:
Error message after:
=> Fixing error message when test for rule fails

docs/gitbook/log-analysis/log-processing/README.md
Fix small docs issues I found while walking through the instructions
=> Small fixes in the log processing SNS instructions

docs/gitbook/SUMMARY.md, docs/gitbook/enterprise/log-compaction.md
Automatic log compaction to Parquet is an Enterprise feature. This is the documentation.
=> Document Parquet

internal/log_analysis/log_processor/parsers/csv_utils.go
See more context in discussion. https://github.com/panther-labs/panther/pull/869#discussion_r424497388
- Small change that was bugging me
- test:ci
=> Removing AWS dependency from CSV utils

README.md
Add link to our open positions on README
- Add jobs on README
- N/A
=> add carrers link

docs/gitbook/SUMMARY.md
- Add Suricata to doc summary
- mage test:ci
=> Add Suricata to doc summary

docs/gitbook/development.md, docs/gitbook/quick-start.md
Release candidate 1 for v1.3.0
=> Release candidate 1 for v1.3.0

docs/gitbook/historical-search/panther-fields.md, internal/log_analysis/awsglue/schema.go
- Added panther log fields that were missing from doc
- Fixed p_rule_reports description
- Sorted doc table
- mage doc
=> Update panther log documentation

web/src/components/utils/TableControls/TableControlsComplianceFilter.tsx
Minor update for background color of filtering buttons on Resource Table inside a Policy
- Changed background color options
- Locally
=> Updated background colors for Resources filtering buttons

internal/compliance/snapshot_poller/pollers/aws/kms_key.go
Logging at INFO level instead of error level when we don't have permissions to describe a KMS Key. Following same approach as we did with KMS ListTags operation.
=> Skipping AccessDenied errors when describing a KMS key

internal/compliance/snapshot_poller/pollers/aws/iam_user.go
We observed rate limiting during scanning of IAM users. This is because if an IAM credential report does not exist, we have to create and then wait for it to exist. While waiting for the report to be created, we sometimes get rate limited on our `GenerateCredentialReport` API call. In these cases, we just want to re-attempt the scan in a few minutes once the report has finished being created. But in order to do that, we have to know that the issue was related to rate limiting and not some other issue. To do this we attempt to explicitly catch the rate limiting error and when we see it re-queue the scan for some point in the future (hopefully after the rate limit has passed and the credential report has finished being generated).
Previously, we were attempting to catch the wrong type of …
=> Fixed error handling case

internal/compliance/aws_event_processor/processor/process.go, internal/compliance/aws_event_processor/processor/process_test.go
We've observed a number of errors in hosted accounts due to the `aws-event-processor` being unable to extract the AWS account ID for certain events. Previously we had just added these events to the ignore list, however the majority of events are from unsupported sources anyways. I moved the unsupported sources check to before the account ID extraction, this should alleviate many of these issues without the need for explicitly ignoring the events.
- Moved the supported source check to before the AWS account ID extraction
- Fixed typos in some log messages
- Unit tests
=> Move supported source check earlier

deployments/master.yml, docs/gitbook/quick-start.md
A patch release to fix a few bugs. See the [new milestone](https://github.com/panther-labs/panther/milestone/14?closed=1) for details
- Upgrade version in template/docs to v1.5.1
- `mage master:deploy`, both fresh deployment and upgrade from previous version
=> v1.5.1 release

docs/gitbook/enterprise/snowflake.md, docs/gitbook/operations/ops-home.md
- Update snowflake yml example with correct mage command
- add `compact` to list of ops tools
- mage test:ci
=> Update ops and snowflake docs

docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md, internal/log_analysis/log_processor/parsers/awslogs/awslogs.go, internal/log_analysis/log_processor/parsers/awslogs/cloudwatch_events.go, internal/log_analysis/log_processor/parsers/awslogs/cloudwatch_events_test.go, internal/log_analysis/log_processor/parsers/testutil/testutil.go, web/src/constants.ts
Closes #921 
- Added CloudWatch Events parser
- Unit tests
- Deployed to my account, verified end to end.
=> Added CloudWatch Events parser

web/src/hooks/useFormSessionRestoration.tsx
This was a weird one, `session-id` was used from the `useFormSessionRestoration` hook as a temporary draft storage engine for different forms across the app. For persisted forms, everything worked as expected as a unique id was provided upon submission. For new items created through form submissions, the session storage cache was not properly invalidated.
Using the `useFormikContext` hook I was able to detect form submissions and remove any relevant entries, furthermore, a debounce method was added as minor performance improvement. Upon changing the form's stage the storage will get triggered again.
Close #1053 
- Added proper sanitation and cleanup within the React lifecycle
- Successfully retrieved a persisted rule upon editing.
- Successfully retrieved a new rule upon closing the tab. …
=> Remove session storage entries upon form submission

docs/gitbook/enterprise/saml/generic.md
Minor readability updates to generic SAML IdP integration docs.
=> minor readability updates

docs/gitbook/enterprise/saml/overview.md
Minor clarification added to doc.
=> minor SAML doc clarification

web/__tests__/__mocks__/builders.generated.ts, web/codegen/buildGraphqlResourcesPlugin.js, web/codegen/buildGraphqlResourcesPlugin.ts
I accidentally split changes for a previous PR in two separate local clones of Panther.
This PR adds some forgotten work on #1187
=> fix: typo in generator

internal/compliance/snapshot_poller/pollers/aws/cloudwatchlogs_log_group.go, internal/log_analysis/log_processor/destinations/s3.go
Fixing a  nil-pointer dereference
- mage test:ci
=> Fixing nil pointer dereference

docs/gitbook/log-analysis/log-processing/log-setup/box.md
Adds docs for creating a new box application for fetching Box Events into Panther
=> Documentaion for creating a box app

docs/gitbook/enterprise/snowflake.md
- Added sf links to docs for creating users and roles
- Improved text
- mage test:ci
=> Update snowflake docs

internal/core/analysis_api/analysis/policy_engine.go, internal/core/analysis_api/main/integration_test.go, internal/log_analysis/rules_engine/src/main.py
Fix calculating test results summary
- Amended integration tests to catch this error + UI testing
=> Fix TestSummary calculation

internal/log_analysis/rules_engine/src/main.py, internal/log_analysis/rules_engine/tests/test_main.py
Small python test and formatting fixes after test:ci fail in #1235 
Sorry for the tiny PR
=> Fix python test and format

docs/gitbook/SUMMARY.md
Add missing docs link for box setup to release
=> Update SUMMARY.md to include Box setup docs

README.md
=> updating dark theme SS

README.md
fixing issue in naming of dark theme image files
replacing png with PNG
=> fixing issue in naming

web/src/components/forms/SigninForm/SigninForm.tsx
There is a minor issue on https://github.com/aws-amplify/amplify-js/pull/4427 that seems to affects us. This PR handles this and displays a valid error.
- Locally
=> Fix Sign In message on error 

docs/gitbook/enterprise/snowflake.md
Update snowflake docs for UI
- @georgeSkoumas is testing this
=> Update snowflake docs for UI

docs/gitbook/enterprise/snowflake.md
We had to update the documentation on how to integrate Snowflake with Panther.
- docs/gitbook/enterprise/snowflake.md modified
- Snowflake queries on how to setup Snowflake users and read only roles were added.
- Snowflake queries on how to provide a Snowflake user with read access on databases and tables were added. 
- The proposed integration pipeline was thoroughly tested and works properly?
=> Updated snowflake documentation

tools/mage/build_namespace.go
We are now attaching pre-compiled opstools to the [release](https://github.com/panther-labs/panther/releases/tag/v1.6.0):
Our current `mage build:tools` output puts each binary into a separate directory, I had to manually copy and rename them for the release, which is of course error-prone.
This PR flattens the `build:tools` output so the binaries can be directly uploaded to release assets.
- Windows binary names end in `.exe` (or they won't run correctly)
- `mage build:tools` now outputs the following tree:
```
out/bin/cmd
├── devtools
│   ├── logprocessor-darwin-amd64
│   ├── logprocessor-linux-amd64
│   ├── logprocessor-linux-arm
│   ├── logprocessor-windows-amd64.exe
│   └── logprocessor-windows-arm.exe
└── opstools
├── requeue-darwin-amd64
├── requeue-linux-amd64
├── …
```
=> Flatten mage build:tools output

docs/gitbook/enterprise/README.md
removed notes about premium detections, also made a couple of grammar updates
No longer holding back detections, removing reference to this from our enterprise page. 
Removed notes about premium detections in enterprise. Also made a few grammar updates for brevity and readability. 
n/a
=> removed note about prem detections

docs/gitbook/enterprise/saas-logs/saas-logs.md
Quick grammatical fixes to saas logs landing page.
Fixed a couple of minor grammatical issues. 
n/a
=> minor wording updates to SaaS logs landing page

cmd/opstools/requeue/requeue/main.go, cmd/opstools/s3queue/s3queue/main.go
This change adds an `-interactive` flag  to `requeue` and `s3queue` to make them easier to use. This was also done in the new opstool `gluesync`.
- prompt user for flags unset
- mage test:ci
- ran the tools, with and w/out flags
=> Make opstools interactive

deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml, deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
Update some descriptions on the CF stacks for improved clarity
- Slight wording changes on the CF stack param descriptions for cloudwatch events and log processing
- None
=> [deployments] improved clarity on CF stack descriptions

tools/mage/test_ci.go
On the last [CI master build](https://app.circleci.com/pipelines/github/panther-labs/panther/6406/workflows/1ade9aaa-806a-49cc-813c-e4600726604f/jobs/15375):
* `mage test:go` took 138 seconds (wall clock time)
* `mage test:web` took 78 seconds (wall clock time)
Unfortunately, these run sequentially - `test:go` runs by itself before `test:web` runs along with all the other tests. This means the total CI time is bounded below by the *sum* of our two slowest tests - not ideal.
@3nvi has suggested separating the CI task into separate components, so `test:go` and `test:web` can run in separate CI containers in parallel, for example. A great idea which we will definitely implement at some point! But that's a bit more work than we have time for at the moment, so this PR offers a very quick fix …
=> Don't run go tests in isolation in CI

.github/workflows/main.yml
Recently switched API tokens so that a service account can be used for the PR automation. This PR changes the `git config` to use the email of the related service account
- Update `git config`
- CI
=> Update `git config` for PR syncing automation

cmd/opstools/gluesync/gluesync/main.go
Processing the `-start` flag was missing (only interactive worked).
Closes: https://github.com/panther-labs/panther/issues/1388
- parse flag
- check for -start in the future
- output value of -start in logging
- ran cli
=> Fix start date flag for gluesync

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/master.yml
Version bump for fixes in v1.7.0 -> v1.7.1
- Changed version strings
- N/A
=> chore: update patch version

internal/log_analysis/alerts_api/table/list.go
` filterByTitleContains()` was not checking if the alert title was nil and there could be a nil ptr exception.
Closes: https://github.com/panther-labs/panther/issues/1468
Check if alert title is nil
- mage test:ci
=> Fix nil ptr in filterByTitleContains()

internal/core/source_api/api/check_integration.go
Fixes #1436
In order to describe a KMS key for a log source bucket, we used the region Panther was installed at.  As a result,
a user could not use a KMS key from a different region.
Use the region of the KMS key when making a `DescribeKey` request.
- Manual
=> Enable using a cross-region KMS key for log source

internal/log_analysis/log_processor/parsers/apachelogs/access_common.go, internal/log_analysis/log_processor/parsers/apachelogs/access_common_test.go
Response size in CLF maybe "-" instead of 0.
See https://httpd.apache.org/docs/current/logs.html#common
=> Fix clf responsesize parse

internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go
Fixes https://github.com/panther-labs/panther-enterprise/issues/681
- Wrote unit test that failed, updated code and seen test passing
=> Fixing source matching issue

package-lock.json, package.json, web/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap, web/src/components/fields/DateRangeInput/DateRangeInput.tsx, web/src/components/fields/DateRangeInput/index.tsx, web/src/components/fields/SensitiveTextInput/__snapshots__/SensitiveTextInput.test.tsx.snap
This is the initial `DateRange` component working along with Formik.
- Introduce a new Formik component, which parses and propagates dates in UTC format.
=> feat: add Formik date range component

internal/log_analysis/log_processor/parsers/apachelogs/access_common.go, internal/log_analysis/log_processor/parsers/apachelogs/apachelogs.go, internal/log_analysis/log_processor/parsers/fastlylogs/access.go, internal/log_analysis/log_processor/parsers/fastlylogs/access_test.go, internal/log_analysis/log_processor/registry/registry.go
Implement parser for the Fastly CLF logs
Unit + E2E QA
Fixes panther-labs/panther-enterprise#127
=> Implement Fasty parser for Common Log Format logs

pkg/awsutils/awsutils.go, tools/mage/clients/aws.go, tools/mage/deploy/deploy_template.go, tools/mage/master/publish.go, tools/mage/teardown/s3.go
Backporting a small function to help check for AWS error codes. 
- Backported from Enterprise
=> AWS Error checker utility 

internal/log_analysis/log_processor/parsers/gravitationallogs/audit.go
Updating Gravitational parser to use `pantherlog` types as described in documentation: https://docs.runpanther.io/development/writing-parsers
- Updating Gravitational parser to use `pantherlog` types. 
- mage test:ci
=> Updating Gravitational parsers

README.md
Fixes minor grammatical error
- Fix wording in README
- N/A
=> fix: grammatical error in docs

web/src/components/fields/SensitiveTextInput/SensitiveTextInput.test.tsx, web/src/components/fields/SensitiveTextInput/SensitiveTextInput.tsx, web/src/components/fields/SensitiveTextInput/__snapshots__/SensitiveTextInput.test.tsx.snap, web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.test.tsx, web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.tsx, web/src/components/forms/CustomWebhookDestinationForm/CustomWebhookDestinationForm.tsx, web/src/components/forms/GithubDestinationForm/GithubDestinationForm.tsx, web/src/components/forms/JiraDestinationForm/JiraDestinationForm.tsx, web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.tsx, web/src/components/forms/OpsgenieDestinationForm/OpsgenieDestinationForm.tsx, web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.tsx, web/src/components/forms/SlackDestinationForm/SlackDestinationForm.tsx, web/src/pages/CreateDestination/CreateDestination.test.tsx
Due to some inconsistencies with the Formik Field and the pounce components the `SensitiveTextInput` was a bit funky.
This PR fixes the UX and the working issues with the component.
- Fix Tooltip event encapsulation
- Add `shouldMask` flag prop
- Fix the pending tests
=> Sensitive TextInput fix

internal/core/source_api/main/handler.go
Fixes #591 
Followed this example: https://github.com/panther-labs/panther/blob/89b6dd7cfdfc97afa9007ecac1738057b3f37841/internal/core/outputs_api/main/lambda.go#L40
- mage test:ci
=> Fix component name

.github/ISSUE_TEMPLATE/epic.md
To better ensure consistency in larger projects, I'm adding an Epic issue template and adjusting our Story template to include new headers for designs and more.
- Update the story issue template
- Add a new Epic template
- None
=> [git] story and epic issue templates

cmd/opstools/gluesync/gluesync/main.go, tools/cfnstacks/cfnstacks.go
I made the mistake of doing this change in Enterprise. This PR backports the changes for https://github.com/panther-labs/panther-enterprise/pull/798
=> Backport gluesync fix to work with master stack

internal/core/source_api/api/put_integration.go
If an error happens when saving a new log source integration, the API responds with a generic error message but also tries to log the original error. The implementation had a bug and the generic error ended up being logged instead of the original one.
- Manually observing logs and API response
=> Fix error logging for PutIntegration

api/lambda/source/models/integration.go, cmd/opstools/gluesync/gluesync/main.go, internal/core/source_api/api/put_integration.go
I found a couple of issues while testing something locally. The Glue Sync will be replaced with a new tool soon, however the tool will not make it for 1.9.
- Fixing issue where gluefix would not fix tables added through SQS source. 
- Deployed and verified manually.
=> Fixing few issues with Glue Sync tool

internal/log_analysis/awsglue/schema.go, internal/log_analysis/awsglue/schema_test.go
Supporting custom types in slices/maps. Backporting fix from https://github.com/panther-labs/panther-enterprise/pull/819
- Unit testing
=> Supporting custom types in slices/maps

deployments/master.yml
Update template version to match tagged release
- master template move from RC to stable tagged release
- N/A
=> chore: change version to release tag

tools/mage/deploy/deploy.go
Fixing deployment issue
Found issues: 
```
15:26:21	ERROR	[deploy]	    X panther-core failed (3/9): failed to create change set for stack panther-core: ValidationError: Parameters: [ProcessedDataBucket] do not exist in the template
```
- Deployment was failing, now passing. Verified in dev account
=> Fixing deployment issue

deployments/bootstrap.yml
Fix a parameter validation bug.
- Allow the empty string as an input for some optional fields
- Deployed
=> Fix VPC input check

deployments/master.yml
Update version to match latest v1.10.0-RC2 release
- Update master template version
- N/A
=> fix: version bump for templates

deployments/master.yml
Update Panther version
- update master template
- N/A
=> chore: update version

deployments/master.yml
Updates the master version template to match release
- Update master template version
- N/A
=> chore: update version in release branch

internal/log_analysis/log_processor/parsers/osquerylogs/differential.go, internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go
Closes #1532
Pending ticket
- Adds missing indicator fields
- unit tests
=> Add extra indicators for OSQuery.Differential.

web/.eslintrc.js, web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx, web/src/pages/ComplianceOverview/PoliciesBySeverityChart/PoliciesBySeverityChart.tsx, web/src/pages/ComplianceOverview/PoliciesByStatusChart/PoliciesByStatusChart.tsx, web/src/pages/ComplianceOverview/ResourcesByStatusChart/ResourcesByStatusChart.tsx, web/src/pages/CreatePolicy/CreatePolicy.tsx, web/src/pages/CreateRule/CreateRule.tsx, web/src/pages/EditPolicy/EditPolicy.tsx, web/src/pages/EditRule/EditRule.tsx, web/src/pages/LogAnalysisOverview/LogAnalysisOverview.test.tsx, web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx, web/src/pages/LogAnalysisOverview/graphql/getOverviewAlerts.generated.ts, web/src/pages/LogAnalysisOverview/graphql/getOverviewAlerts.graphql
This PR fixes some small UX issues, we collected over the last days.
Closes #1617
Closes  #1609 
- Locally
=> Minor UX Improvements 

web/src/components/JsonViewer/JsonViewer.test.tsx, web/src/components/JsonViewer/JsonViewer.tsx, web/src/components/JsonViewer/__snapshots__/JsonViewer.test.tsx.snap
This one adds an Expand collapse button for the JSON view.
https://share.goabstract.com/56ae4caa-bebf-4f7d-92ba-7358bf5e4031?mode=design&sha=45ee05f75334fe2a184c7a8f9380b197d3d74146
=> Feat: add expand/collapse button for JSON view

internal/log_analysis/log_processor/parsers/sophoslogs/central.go, internal/log_analysis/log_processor/parsers/sophoslogs/central_test.go, internal/log_analysis/log_processor/parsers/sophoslogs/sophos.go, internal/log_analysis/log_processor/parsers/sophoslogs/testdata/central_tests.yml, internal/log_analysis/log_processor/registry/registry.go
Syncing PR from master (syncing workflow did not work because original PR was merged from a fork)
=> [Sync] Parser for Sophos Central logs (#1770)

api/graphql/schema.graphql, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/components/GenericItemCard/GenericItemCard.test.tsx, web/src/components/GenericItemCard/GenericItemCard.tsx, web/src/components/GenericItemCard/__snapshots__/GenericItemCard.test.tsx.snap, web/src/components/cards/AlertCard/AlertCard.tsx, web/src/graphql/fragments/AlertDetailsFull.generated.ts, web/src/graphql/fragments/AlertDetailsFull.graphql, web/src/graphql/fragments/AlertSummaryFull.generated.ts, web/src/graphql/fragments/AlertSummaryFull.graphql, web/src/pages/AlertDetails/AlertDetailsBanner/AlertDetailsBanner.test.tsx, web/src/pages/AlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx, web/src/pages/AlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
This one adds coloring and type checking for alerts listing and rule details page. This PR is the base for the upcoming ones and testing will follow at the end of the Saga.
=> Rule Errors UI in Alerts and listing options.

deployments/log_analysis.yml, internal/core/custom_resources/resources/log_processor_tables.go
- Remove unused env vars for the log processor tables custom resource
- mage test:ci
- mage deploy
=> Remove unused env vars for the log processor tables custom resource

package-lock.json, package.json
Update pounce to latest, including features & bugfixes
- Bump pounce
=> Chore: update pounce

internal/core/analysis_api/main/integration_test.go
Fixes broken integration tests for:
```
--- FAIL: TestIntegrationAPI (9.04s)
--- FAIL: TestIntegrationAPI/TestPolicies (1.79s)
--- FAIL: TestIntegrationAPI/TestPolicies/TestPolicyPass (1.33s)
--- FAIL: TestIntegrationAPI/TestPolicies/TestPolicyPass/RULE (1.02s)
integration_test.go:413: 
Error Trace:    integration_test.go:413
Error:          Not equal: 
expected: &models.TestRuleResult{Results:[]*models.RuleResult{(*models.RuleResult)(0xc000b38d00), (*models.RuleResult)(0xc000b38dd0)}, TestSummary:true}
actual  : &models.TestRuleResult{Results:[]*models.RuleResult{(*models.RuleResult)(0xc0000be4e0), (*models.RuleResult)(0xc0000be820)}, TestSummary:true}
Diff:
--- Expected
+++ Actual
@@ -10,3 +10,3 @@
ID: (string) (len=1) "0",
-   Passed: (bool) false,
+   Passed: (bool) true,
RuleError: …
```
=> fix: integration tests

web/src/constants.ts
Fixes #1946 
- Fix text
- mage test:ci
=> Fix wording

package-lock.json, package.json, web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
This PR fixes an issue with the datepicker and with the HTML of a test section.
Closes #1836 
- Bump Pounce
- Don't un-necessarily render an empty Card when no tests exist
=> Fix Datepicker bugs

internal/log_analysis/log_processor/processor/processor.go, internal/log_analysis/log_processor/sources/s3.go
Fixing bug in log processor
- Reverting to use bufio Reader instead of scanner
- mage test:ci
=> Reverting reading change

internal/log_analysis/log_processor/parsers/gcplogs/auditlog.go, internal/log_analysis/log_processor/parsers/gcplogs/gcplogs.go
GCP.AuditLog was out of sync with enterprise
=> Sync GCP.AuditLog with enterprise

internal/compliance/datalake_forwarder/forwarder/compliance.go, internal/compliance/datalake_forwarder/forwarder/forward.go, internal/compliance/datalake_forwarder/forwarder/internal/diff/comparisons.go, internal/compliance/datalake_forwarder/forwarder/internal/diff/comparisons_test.go, internal/compliance/datalake_forwarder/forwarder/internal/events/events.go, internal/compliance/datalake_forwarder/forwarder/resources.go, internal/compliance/datalake_forwarder/forwarder/source_api.go, internal/compliance/datalake_forwarder/forwarder/source_api_test.go, internal/compliance/datalake_forwarder/main/handler.go, internal/compliance/snapshotlogs/compliance.go, internal/compliance/snapshotlogs/resource.go, internal/compliance/snapshotlogs/snapshots.go, internal/compliance/snapshotlogs/snapshots_test.go, internal/compliance/snapshotlogs/testdata/snapshot_tests.yml, pkg/awsbatch/firehosebatch/firehosebatch.go, pkg/awsbatch/firehosebatch/firehosebatch_test.go
Partially merging changes already in the cloud-security-to-datalake feature branch
Trying to make the final merge more manageable. 
This code has already been code reviewed.
- mage test:go
=> Partially merging changes already in the cloud-security-to-datalake feature branch

internal/log_analysis/log_processor/parsers/gsuitelogs/gsuitelogs.go, internal/log_analysis/log_processor/parsers/gsuitelogs/reports.go, internal/log_analysis/log_processor/parsers/gsuitelogs/reports_test.go, internal/log_analysis/log_processor/parsers/gsuitelogs/testdata/reports_tests.yml
=> Port GSuite.Reports to pantherlog and add 'email' tag

deployments/Dockerfile
Fix Dockerfile syntax
- remove `=`
- `npm run test:ci`
=> fix: web dockerfile

build/actions/pr_sync/dist/index.js, build/actions/pr_sync/index.js
Prepend an empty space before `closes` tag
Closes #1324 (faked)
- Add empty space
- CI
=> fix: empty space in PR syncing

internal/log_analysis/log_processor/pantherlog/jsoniter.go, internal/log_analysis/log_processor/pantherlog/meta.go, internal/log_analysis/log_processor/pantherlog/result_test.go, internal/log_analysis/log_processor/sources/sources.go
(cherry picked from commit 64391f1e6a7d9cad18531655b8903af6c0a241b0)
=> [Sync] fix missing source id/label fields (#2181)

web/README.md
Replace a TODO with actual instructions
- Add minimal testing section
- Preview
=> [FE] update /web/README.md

package-lock.json, package.json
Bumps web packages' patch versions according to snyk findings
- Bump packages
- Force resolution for packages without an upgrade path
- Snyk CI check
=> Bump web packages based on Snyk reports

.circleci/config.yml, build/images/README.md, build/images/ci/Dockerfile, build/images/deployment/Dockerfile, dev.sh
Version bump for the two docker images `panther-buildpack` and `panther-development-pack`
- Update the versions to `1.15.0`
- N/A
=> fix: update both docker images

internal/log_analysis/alerts_api/table/list.go
Fixes a bug where filtering alerts by title was not working at all.
- fix conditional in the title filter
- visually/manually
=> Alert filtering by title

internal/log_analysis/log_processor/parsers/awslogs/extractor_test.go, internal/log_analysis/log_processor/parsers/awslogs/indicators.go, internal/log_analysis/log_processor/parsers/awslogs/indicators_test.go
Extracting ARNs from policy conditions
- Extracting ARNs from policy conditions
- unit test
=> Extracting ARNs from policy conditions

internal/compliance/datalake_forwarder/forwarder/forward_test.go, internal/compliance/datalake_forwarder/forwarder/resources.go, internal/compliance/snapshotlogs/resource.go, internal/compliance/snapshotlogs/testdata/snapshot_tests.yml
Closes #2287 
- unit test
- Deployed and verified E2E
=> Fix resources

web/__tests__/setupTests.ts
Bump test timeouts even more.
- Increase test timeouts
- CI
=> test: hail mary timeout increase

deployments/bootstrap.yml
Log subscriptions were missing prefixes for cloud_security and rule_errors
Log subscriptions have prefixes for cloud_security and rule_errors
-mage test:cfn
=> Add cloud_security and rule_errors to log subscription permissions

deployments/log_analysis.yml
Increase Updater Lambda SQS batch size
- Increase batch size for Lambda
- Deployed fresh Panther instance. Seen data in Athena
=> Increase updater batching

tools/mage/teardown/cfn.go
`mage teardown` fails on developer deployments with:
```
14:19:23	ERROR	[teardown]	stack panther-onboard: AWS::CloudFormation::Stack panther-onboard DELETE_FAILED: The following resource(s) failed to delete: [SelfRegistration].
14:19:23	ERROR	[teardown]	stack panther-onboard: Custom::SelfRegistration SelfRegistration DELETE_FAILED: Failed to delete resource. ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:571590349641:function:panther-source-api
```
This is due to the fact that `mage teardown` deletes most of the stacks in parallel. But we have some dependencies which need to be honored for a clean teardown. This is yet another reason why we need to move away from managing stacks directly with `mage` and instead handle them nested in the root template …
=> Fix teardown: run in stages

internal/compliance/aws_event_processor/processor/process.go, internal/core/source_api/api/update_integration.go
-
- Improve some error messages when updating a log source
- Change a log line to be logged at Debug level - there is no need to be at Warn level, after discussing with Nick H.
-
=> Trivial log/error tidying

internal/core/source_api/api/update_integration.go
Fix backwards compatibility issue already present in `master`
- mage test:ci
=> Fix backwards compatibility issue

package-lock.json, package.json, web/src/components/utils/ApiErrorFallback/ApiErrorFallback.tsx
Updating to latest pounce, that omits `maxWidth` from `Modal`
- Bump pounce
- Test multiple modals including Deletion, Network and Analytics Consent
=> Bump pounce 0.79.1

cmd/opstools/requeue/requeue.go
Make sure to include Message Attributes when requeuing SQS messages
- Include Message attributes when requeue SQS messages
- mage test:ci
=> Added message attributes to the messages requeued

package-lock.json, package.json
Bumping the newest Pounce version.
=> Bump pouncejs

web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx, web/src/pages/ListAlerts/ListAlerts.test.tsx
- Move the Log Types and Resource Types closer together in the filer. 
- Rename “Policy Fail” → “Policy Failures” 
Closes #2463
=> Modify list alerts filters content

deployments/appsync.yml
=> fix: deployment

web/src/components/wizards/S3LogSourceWizard/S3SourceConfigurationPanel/S3SourceConfigurationPanel.tsx, web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx, web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
Small text change for fields on S3 onboarding as discussed [here](https://panther-labs.atlassian.net/wiki/spaces/EN/pages/1033240589/2021-1-13+Dogfood+Session?focusedCommentId=1036222691#comment-1036222691)
=> fix: updated label for S3 log source fields

internal/core/source_api/api/put_integration.go
Thank you @giorgosp for bringing this issue to my attention! 
- Moved options up to `case models.IntegrationTypeAWSScan`
=> Hotfix: Cloud Security Source Options 

deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml, internal/core/source_api/api/testdata/panther-log-analysis-iam-updated.yml
Fix panther-log-analysis-iam.yml
- Properly check for `IsGenerated`
- Refactor for better readability
- Deployed stack twice: Once with populated `Mappings` and once by setting parameters on the AWS console.
- Used the role with `awscli` to fetch events from a bucket (with and without prefix in the key)
=> Fix panther-log-analysis-iam.yml

deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml, internal/core/source_api/api/testdata/panther-log-analysis-iam-updated.yml
=> [Sync] log analysis iam role changes

.github/ISSUE_TEMPLATE/design.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/rfc.md, .github/ISSUE_TEMPLATE/story.md, .github/ISSUE_TEMPLATE/sub-epic.md
Give a much-needed update to the Epic, Story, and Design templates used for software development
=> [github] update issue templates

tools/mage/deploy/deploy.go
Fixing mage deploy.
- Pass in required parameter
- ran `mage deploy`
=> Fix mage deploy

internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
Closes #2532 
- Ignore zero sized s3 objects
- mage test:go
=> Ignore zero sized s3 objects in the log processor

.github/ISSUE_TEMPLATE/design.md, .github/ISSUE_TEMPLATE/story.md
Issue templates in the private repo did not match template in the public repo
- updated design template
- updated epic template
=> updated templates in public repo

internal/core/source_api/api/delete_integration.go
Removing bucket notifications may fail, eg if user deleted the iam role before deleting the source.
This PR makes deletion of a source succeed even if removing bucket notifications fail.
- Log but don't fail deletion when Panther fails to remove bucket notifications
- manually
Closes #2657
=> Deleting an s3 source succeeds even if the iam role was deleted

deployments/core.yml, internal/core/analysis_api/handlers/clients.go, internal/core/analysis_api/handlers/github.go, internal/core/analysis_api/main/integration_test.go
Swap out key values for prod configuration.
- `mage test:ci` 
- `mage test:integration`
- deployed in both `us-west-1` and `us-west-2` and verified `PollPacks` is successful
=> Prep for key updates

internal/core/source_api/api/managed_bucket_notifications_test.go
Fix a flaky unit test
Closes https://app.asana.com/0/1199906407795548/1199984569871934
=> Fix flaky test

api/lambda/analysis/engine.go, internal/compliance/policy_engine/src/engine.py, internal/compliance/policy_engine/src/main.py, internal/compliance/policy_engine/src/policy.py, internal/compliance/policy_engine/tests/test_engine.py, internal/compliance/policy_engine/tests/test_main.py, internal/compliance/policy_engine/tests/test_policy.py, internal/core/analysis_api/analysis/policy_engine.go
This PR adds support for unit test mocking in Panther based on this RFC.
- Updated analysis-api to support unit test mocking
- Updated policy engine to properly unpack and setup mock patching
- Added naive unit test for mocking support
- Manual deployment to `us-east-1`
- Directly invoked the `panther-analysis-api` lambda with the following tests:
**Test Policy Engine - Bad Mock**
```
{
"testPolicy": {
"body": "import boto3\nfrom datetime import date\nfrom unittest.mock import MagicMock\n\ndef policy(resource):\n\treturn all([isinstance(boto3, MagicMock), isinstance(boto3.client, MagicMock), isinstance(date, MagicMock)])",
"id": "PantherApiTestingPolicy",
"resourceTypes": [
"AWS.S3.Bucket"
],
"tests": [
{
"expectedResult": false,
"resource": "{}",
"name": …
```
=> Support for Unit Test Mocking - Cloud Security
