.gitignore, go.mod, go.sum, tools/mage/build_namespace.go, tools/mage/fmt.go, tools/mage/setup.go, tools/mage/test_namespace.go, tools/mage/util.go
Running `mage setup` command failed with the following error on my laptop: 
```
Warning: Failed to create the file /usr/local/bin/swagger: Permission denied
0 17.1M    0 16360    0     0  12347      0  0:24:16  0:00:01  0:24:15 12347
curl: (23) Failed writing body (0 != 16360)
Error: running "curl -o /usr/local/bin/swagger -fL https://github.com/go-swagger/go-swagger/releases/download/v0.21.0/swagger_darwin_amd64" failed with exit code 23
```
It seems that setup was trying to download swagger file inside `/user/local/bin/swagger`. A non-root user by default has `rx` rights but no `w` rights. I think it is more safe choice to just download swagger in a subdirectory of the current directory (the directory where panther …
=> Updating mage setup command to download tools inside repository folder

web/config/.env.development, web/config/.env.local, web/config/.env.production, web/config/.env.staging, web/src/constants.ts, web/src/pages/create-source/subcomponents/create-infra-source/subcomponents/resource-scanning-panel.tsx
We now auto-populate Panther AWS Account ID in the Compliance CFN template
I have followed the style of the [log onboarding page](https://github.com/panther-labs/panther/blob/master/web/src/pages/create-source/subcomponents/create-log-source/subcomponents/cfn-launch-panel.tsx). 
* We now auto-populate Panther AWS Account ID in the Compliance IAM roles CFN template
* Removed unused constants
* Changed stack name to `panther-compliance-iam-roles`
* Small style changes - following style of log onboarding page
* Removing configuration values that should be no longer in the project
Ran UI locally with `npm run dev`. 
Tried the Wizard and it automatically populated the Panther AWS …
=> Updating Compliance onboarding page to populate Panther AWS Account ID

internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
When a user sets up S3 Event notifications, S3 sends a test event to verify that it has permissions to send messages to the topic. 
I modified the log processor code to handle these events
* Updated code to handle S3 Test events
* Unit test
* Deployed change and seen log processor handle the case gracefully.
=> Handling S3 Test events

internal/log_analysis/rules_engine/src/main.py
The rules expect that the events are Dict - we currently were passing the raw strings and the pre-canned rules were failing. 
* Parsing the string to Dict - Rules Engine input will always be JSON
* Deployed and verified rules are actually running on data.
=> Fixing rules engine

deployments/auxiliary/README.md, deployments/auxiliary/cloudformation/README.md, deployments/auxiliary/cloudformation/panther-aws-remediations-master-account.yml, deployments/auxiliary/cloudformation/panther-aws-remediations-satellite-account.yml, deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml, deployments/auxiliary/cloudformation/panther-compliance-iam.yml, deployments/auxiliary/cloudformation/panther-log-processing-iam.yml, deployments/auxiliary/cloudformation/panther-log-processing-infra.yml, deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml, deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml, deployments/auxiliary/terraform/README.md
We were hosting some CloudFormation templates in a public S3 bucket for use with Panther, decided to move them into the repo directly so they can be access by the frontend directly and users can configure their own custom default templates.
* Created an `auxiliary` directory under `deployments`, will be used to store templates that build auxiliary/non-core infrastructure for running Panther
* N/A
=> Adding public templates

deployments/compliance/alert_processing.yml
Fixed environment variable configuration issue on the `panther-alert-processor` lambda that was causing alerts to fail. Alerts are back in business.
* Changed an environment variable in `alert_processing.yml`
* Manually in my development account
=> Fixed alerting configuration issue

deployments/auxiliary/cloudformation/panther-compliance-iam.yml, internal/compliance/snapshot_poller/pollers/aws/acm_certificate.go
The ACM individual resource snapshot poller failed due to an incorrect intermediate step.
* Remove the `acm.GetCertificate` call from the ACM single resource snapshot poller
* local linting, formatting, unit testing
* deployed to dev account and manually tested
=> Removed incorrect ACM Certificate Scanning Step

tools/cfngen/gluecf/schema.go, tools/cfngen/gluecf/schema_test.go
Properly emit Glue table columns for composed Go structs (will be used for panther standard fields)
So we can define log events with Panther standard fields via composition.
Future PRs will include usage with log processing.
Looks like:
```
type VPCFlow struct {
Version     *int               `json:"version,omitempty" validate:"required"`
Account     *string            `json:"account,omitempty" validate:"omitempty,len=12,numeric"`
InterfaceID *string            `json:"interfaceId,omitempty"`
SourceAddr  *string            `json:"sourceAddr,omitempty"`
DstAddr     *string            `json:"dstAddr,omitempty"`
SrcPort     *int               `json:"srcPort,omitempty" validate:"omitempty,min=0,max=65535"`
DstPort     *int               `json:"destPort,omitempty" …
```
=> Properly emit glue table columns for composed Go structs 

deployments/compliance/snapshot.yml, internal/compliance/snapshot_api/api/put_integration.go, internal/compliance/snapshot_api/api/sqs_utils.go
Bad merge lost lambda perms, causes UI not to be able to onboard a Log Source.
*  Fix perms
* Improve error messages and logging
Deployed and tested UI manually.
*
=> [ENG-1340]  Cannot add new log sources

internal/core/alert_delivery/outputs/email.go, internal/core/alert_delivery/outputs/github.go, internal/core/alert_delivery/outputs/jira.go, internal/core/alert_delivery/outputs/msteams.go, internal/core/alert_delivery/outputs/opsgenie.go, internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/pagerduty.go, internal/core/alert_delivery/outputs/slack.go, internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sns_test.go
Improving the quality of email delivered through SNS -> Email subscription. 
Apparently SNS makes it possible to configure different message content per destination. 
I am updating existing code so that in case we have an Email subscription to an SNS topic. Note that this delivery doesn't allow us to use HTML markup. 
* Email subscribers to our SNS topic will get human readable email.
* Converted several `*string` to `string`
* Unit tests
* Deployed in my account. Created an SNS topic and added it as destination. Subscribed my email and an SQS queue to that topic. Performed an action that triggered a rule. 
Got the following email: 
And the …
=> Fix sns email

deployments/compliance/remediation.yml, deployments/template.yml, internal/core/organization_api/table/get.go, internal/core/organization_api/table/get_test.go, internal/core/organization_api/table/put.go, internal/core/organization_api/table/table.go, internal/core/organization_api/table/table_test.go, tools/mage/deploy.go
Creating an organization on first deployment. This is needed by UI but also for remediation capabilities. 
Using as organization email the email of the first user and as organization name the name of the user. This change is needed for the frontend PR https://github.com/panther-labs/panther/pull/25 that fixes a lot of UI issues. 
* On first deploy, creating an organization. 
* Modified the Organization.Get method to check for required field `email` instead of previous check that was checking optional field. 
* Deleted my user from cognito & `panther-users` DDB table. Ran deploy script again - seen it populate the Organization. Verified with @3nvi …
=> Creating organization

tools/mage/deploy_frontend.go
While running `mage deploy` I got the following warning: 
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
```
According to docker [docs](https://docs.docker.com/engine/reference/commandline/login/#provide-a-password-using-stdin): 
```
To run the docker login command non-interactively, you can set the --password-stdin flag to provide a password through STDIN. Using STDIN prevents the password from ending up in the shell’s history, or log-files.
The following example reads a password from a file, and passes it to the docker login command using STDIN:
```
* Switched docker login to use ``--password-stdin` command
* Using a pipe to pipe the password to …
=> Fix warning while uploading ECR image

internal/compliance/resources_api/main/integration_test.go, internal/core/organization_api/main/integration_test.go, internal/core/organization_api/table/update.go, internal/core/organization_api/table/update_test.go, internal/core/outputs_api/api/add_output.go, internal/core/outputs_api/api/api_test.go, internal/core/outputs_api/api/update_output.go, internal/core/outputs_api/api/update_output_test.go, internal/core/outputs_api/main/integration_test.go, internal/core/outputs_api/table/get_default.go, internal/core/outputs_api/table/query_defaults.go
Fixing flaky integration tests
* Changed some `assert` to `require` - thinking it was more appropriate. 
* Replacing `"1"` magic string with `orgID` in `UpdateOrganization` API. I believe this method is no longer used, but I will postpone removing it until we have a better plan for this. 
* Fixed `UpdateSns` & `UpdateSlack` output integration tests:
* In some parts of the code we are performing read-after-write on the DDB table `panther-default-outputs` and we need the reads to be consistent. Modified the GetDefault* methods to perform consistent queries. We make these operations upon user actions, so there is no real concern for increased costs
* Tests were failing because we …
=> Fixing flaky integration tests

deployments/compliance/snapshot.yml
@jacknagz identified an issue with the `snapshot-scheduler` failing to issue new scans. The root cause was that after migrating to the mono repo, in a few cases we simplified some things by calling functions directly instead of via invoking their lambda function. When doing so, we lost access to the environment variables of those functions.
* Updated the `snapshot-scheduler` environment variables and permissions to be able to send messages directly to the `panther-snapshot-queue`
* Tested manually in dev account
=> Updated scheduler ENV and permissions

README.md, internal/compliance/aws_event_processor/processor/cloudtrail.go, internal/compliance/snapshot_poller/pollers/aws/cloudtrail.go, internal/compliance/snapshot_poller/pollers/aws/cloudtrail_test.go
Previously we ignored shadow trails while building CloudTrail snapshots.
Shadow trails include two categories of trails:
* Multi region trails in the same account but in a different region
* Organization trails from another account
We don't want to include shadow trails of either variety in the actual resource list, but we do want to include shadow trails of the second variety in the `AWS.CloudTrail.Meta` resource. This PR is in support of that.
* Enabled shadow trails on while making `cloudtrail.DescribeTrails` calls
* Check the regions of the shadow trail to determine if the trail is from a different region/same account setup
* Note that this means we are ignoring shadow trails …
=> Added support for organization trails to snapshot poller

.gitbook.yaml
Adding .gitbook yaml will set the root folder for gitbook to be under `docs`. This will allow gitbook to compile it's content into Markdown files and sync the gitbook documentation with our github repo.
* Add .gitbook.yaml
=> Add .gitbook yaml

tools/cfngen/gluecf/schema.go, tools/cfngen/gluecf/schema_test.go
Developers can add a struct field tag called "description" which will be added to the Glue table column description. This shows up when users hover over columns in the Athena console.
* mage test:unit
* add to columns of log process types and confirmed works in dev account (future PR).
=> Add tag support to describe columns in Glue tables

deployments/auxiliary/cloudformation/panther-log-processing-iam.yml, deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
A small PR to update the description and param naming for two CloudFormation templates
* Change `PantherAccountId` to `MasterAccountId` for consistency across templates
* Remove the `>` in some param descriptions, this looks awkward in the AWS CloudFormation Console
* Just CFN-lint
=> [cfn] rename fields for consistency, formatting fixes

api/graphql/schema.graphql, web/__generated__/schema.tsx, web/src/components/forms/destination-form/jira-destination-form.tsx, web/src/components/forms/destination-form/sns-destination-form.tsx, web/src/components/forms/destination-form/sqs-destination-form.tsx, web/src/components/sidesheets/add-destination-sidesheet.tsx, web/src/components/sidesheets/update-destination-sidesheet.tsx, web/src/constants.ts, web/src/helpers/utils.tsx, web/src/pages/create-source/subcomponents/create-infra-source/subcomponents/remediation-panel.tsx, web/src/pages/create-source/subcomponents/create-log-source/subcomponents/source-details-panel.tsx, web/src/pages/destinations/index.tsx
Currently, when trying to edit some particular destinations, not all the fields get properly populated. This PR fixes just that and validates that everything works for all different types of destinations (8 in total). It also enhances some of our front-end form validation for particular fields
* Rename `assigneeID` to `assigneeId`
* Fix typo of `apiKey` in github destination
* Add validation for ARN input types
* Fix validation for AWS Accoount IDs
* Locally
=> [ENG-1350] Resolve issues with Destination Updates

internal/compliance/snapshot_poller/pollers/aws/cloudformation_stack.go, internal/compliance/snapshot_poller/pollers/aws/iam_user.go, internal/compliance/snapshot_poller/pollers/aws/poll.go, internal/compliance/snapshot_poller/pollers/utils/requeue.go
When doing AWS IAM User scanning, we need a credential report. Building credential reports can sometimes take a long time, but generally not too long, so we just wait for it to complete then continue the scan.
Sometimes, we get rate limited while waiting for it to complete (we're doing a polling wait with exponential backoff). In the past we've increased the wait time and interval which helped this issue, but it happened again on my dev account the other day while doing a fresh installation.
This is a more permanent fix than raising the limits, as we catch the rate limit exception explicitly and re-queue a scan for the account in 90 seconds. If we get rate limited again, we'll just re-queue the scan for another 90 …
=> credential report timeout handling

tools/cfngen/gluecf/schema.go, tools/cfngen/gluecf/schema_test.go
Before: Custom mappings only applied to slices. 
After: Custom mappings apply independent of type.
* mage test:unit
* used with new log processing changes
=> Glue schema generation: fix bug in applying custom mapping

api/lambda/alerts/models/api.go, internal/log_analysis/alerts_api/api/get_alert.go
Renaming field in `Alert` struct to match the name in `AlertSummary`. 
* `mage test:ci`.
=> Renamed api field

deployments/auxiliary/cloudformation/README.md, deployments/auxiliary/cloudformation/panther-remediations-iam.yml, deployments/compliance/remediation.yml, internal/compliance/remediation_aws/src/app/remediations/remediation_base.py, web/src/constants.ts, web/src/pages/create-source/subcomponents/create-infra-source/subcomponents/remediation-panel.tsx
All resources we create have the `Panther` prefix. Fixing remediations IAM role so that it has it as well. 
* Renamed `AwsRemediationsRole` to `PantherRemediationsRole`. 
* Updated README for aux CFN templates
* Updated remediation panel to follow the same style we use in the rest of the wizard panels. 
PR depends on https://github.com/panther-labs/cfn-templates-public/pull/58
* Deployed and verified in account
=> Fixing remediations IAM role

internal/compliance/resources_api/handlers/list_resources.go
Filtering by source account does not work - it still shows all resources
Turns out we parse and validate the `integrationId` in the query parameters but never actually use it!
* One-line fix for resource filtering
* @nhakmiller 's dev account
=> Fix resource filtering by source integration

docs/gitbook/SUMMARY.md
Just a quick follow-up to #63
* Add the newly added Supported Logs page to the Gitbook index
* N/A
=> [gitbook] add supported-logs to summary index

api/graphql/schema.graphql, web/__generated__/schema.tsx, web/src/components/forms/destination-form/jira-destination-form.tsx, web/src/components/sidesheets/add-destination-sidesheet.tsx, web/src/components/sidesheets/update-destination-sidesheet.tsx, web/src/constants.ts, web/src/pages/destinations/index.tsx
The JIRA destination currently defaults to creating a `Task`. We don't have `Task`s enabled in our JIRA account so this fails. I've switched it over to create a `Bug` and it works, but theoretically another organization may have and prefer `Task`s and not even have `Bug`s enabled. Please add an input named `type` or something similar, which can accept the values `Bug`, `Story`, and `Task`. Preferably in a convenient little dropdown select thingy or something so users don't have to type it 
In addition, we'll change the user name to email address
* Add `issueType` into the jira destination form which is reflected in `schema.graphql`, list destinations component and the jira form
> …
=> [ENG-1355]Add issue type for jira destination

web/src/components/navigation.tsx, web/src/components/sidesheets/add-destination-sidesheet.tsx, web/src/components/sidesheets/update-destination-sidesheet.tsx, web/src/pages/list-sources/log-source-columns.tsx
S3 buckets on log sources table can overlap, leading to a small visual glitch where a bucket name is split into multiple lines and concatenated with another.
This PR makes sure that each S3 bucket occupies exactly one line and that the navigation doesn't overflow for small screens.
* Make sure not to break line on S3 bucket values on log source table
* Make sure that the vertical navigation doesn't overflow when the screen has a small height
* Rename GraphQL mutation & query, since there was a typo (unnecessary `Slack` prefix)
Locally
=> [UI FIX] Fix minor UI issues

api/lambda/outputs/models/api.go, internal/core/alert_delivery/delivery/dispatch.go, internal/core/alert_delivery/models/api.go, internal/core/alert_delivery/outputs/asana.go, internal/core/alert_delivery/outputs/asana_test.go, internal/core/alert_delivery/outputs/github_test.go, internal/core/alert_delivery/outputs/jira.go, internal/core/alert_delivery/outputs/jira_test.go, internal/core/alert_delivery/outputs/msteams.go, internal/core/alert_delivery/outputs/msteams_test.go, internal/core/alert_delivery/outputs/opsgenie.go, internal/core/alert_delivery/outputs/opsgenie_test.go, internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/pagerduty.go, internal/core/alert_delivery/outputs/pagerduty_test.go, internal/core/alert_delivery/outputs/post.go, internal/core/alert_delivery/outputs/post_test.go, internal/core/alert_delivery/outputs/slack.go, internal/core/alert_delivery/outputs/slack_test.go, internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sqs.go, internal/core/outputs_api/api/add_output_test.go, internal/core/outputs_api/api/utils.go, internal/core/outputs_api/validator/validator.go, internal/core/outputs_api/validator/validator_test.go
Related to https://github.com/panther-labs/panther/issues/70 . Supporting Asana as a destination. When a policy fails or a rule has a match, we will create a new Asana task in an Asana project. 
When users create an Asana destination, they need to add an access token and one (or many) projects that they want the task to associated with. 
Ref: https://developers.asana.com/docs/#create-a-task
- Adding Asana as a destination
- Fixing an issue in the alert_delivery Lambda API - marking the `createdAt` field from an alert as required. It was a field always required by the code, just the API didn't have the appropriate mark. 
- Small cleanup here and there
- Added unit test
- Created an Asana destination …
=> Adding Asana destination

.github/CODEOWNERS
Move to public GitHub usernames vs a Github team name
- ^^
- YOLO
=> [git] swap secret team for distinct usernames

web/src/client.ts, web/src/pages/list-sources/subcomponents/infra-source-table.tsx, web/src/pages/list-sources/subcomponents/log-source-table.tsx
This PR fixes a bug where a page refresh was needed in order to see the source you deleted. Now the source will be instantly removed from the table, without the need for a page refresh.
- Add missing `integrationType` field
- Add apollo cache normalization to Integration types
Locally
=> [ENG-1469] Real-time source deletion

deployments/core/cognito.yml
I noticed while testing a previous deployment that it appears Panther currently fails to deploy on a fresh (no prior existing infrastructure) deployment due to the Cognito User pool configuration.
Note that MFA is re-enabled via API calls in the `enableTOTP` step of the deploy process.
- Removed an unnecessary field from Cognito user pool causing deployments to fail
- Deployed to a new region to test a fresh deployment
=> Removed MFA configuration that causes fresh deployments to fail

tools/mage/deploy_certificate.go
@gavinelder reported that the deploy process fails when deployed in either of the `cn` regions at the upload ACM certificate step. Further investigation by @austinbyers showed that ACM is in fact not supported in those regions.
This change modifies the deploy process to fallback to uploading a certificate to IAM in cases where the ACM service is not available.
Closes: #67 
- Added a check to see if the ACM service is available
- When the ACM service is not available, upload the self signed certificate to IAM instead of ACM
- None yet, looking into setting up an account in `cn`
=> Add IAM fallback for ACM certificate import

deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml, deployments/auxiliary/cloudformation/panther-compliance-iam.yml, deployments/auxiliary/cloudformation/panther-log-processing-iam.yml, deployments/auxiliary/cloudformation/panther-log-processing-infra.yml, deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml, deployments/auxiliary/cloudformation/panther-remediations-iam.yml, deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml, deployments/backend.yml, dev.sh
The following change moves to using AWS Supported [Pseudo paramaters](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html) where possible enabling deployment in AWS partitions `aws-cn` & `aws-govcloud`
* Allow passing of `AWS_PARTITION` into the dev docker 
* Change to using AWS Pseudo variables as part of the SDK & Cloud formation templating. 
* Deploy to `AWS-CN`
* Deploy to `AWS (West)`
=> Support AWS Partition deployment within Cloudformation.

api/graphql/schema.graphql, web/__generated__/schema.tsx
This PR fixes #93 by allowing `eventsLastEvaluatedKey` to take `null` values
- Allow `eventsLastEvaluatedKey` to be `null`
This fix hasn't been tested E2E due to lack of reproducibility. The instructions on #93 were not reproducible. The reported issue though is definitely a bug according to the [related api](https://github.com/panther-labs/panther/blob/1ba51ff74fdb09f9e6c40106fb0926cac48ebe28/api/lambda/alerts/models/api.go#L113), thus this PR is considered safe
=> [Bugfix] Allow `eventsLastEvaluatedKey` to accept `null` values

web/src/components/utils/table-compliance-filter-control.tsx, web/src/pages/policy-details/index.tsx, web/src/pages/resource-details/index.tsx
This PR fixes #92 by making sure that `status` and `ignored` filters are mutually exclusive and don't overlap with one another
- Make sure that when `ignored` is toggled, then `status` is disabled and vice versa
> How did you test your change?
Locally
=> Fix issue with persistent compliance filters

deployments/compliance/alert_processing.yml, deployments/compliance/aws_event_processor.yml, deployments/compliance/compliance_api.yml, deployments/compliance/remediation.yml, deployments/compliance/resources_api.yml, deployments/compliance/snapshot.yml, deployments/core/admin_api.yml, deployments/core/analysis_api.yml, deployments/core/appsync.yml, deployments/core/outputs.yml, deployments/log_analysis/alerts.yml, deployments/log_analysis/log_processor.yml, deployments/log_analysis/rules_engine.yml, deployments/web/ecr.yml, deployments/web/server.yml
Following up from #61 to use a cfn psuedoparameter for all URL suffixes and AWS partitions
- Replace `.amazonaws.com` with `.${AWS::URLSuffix}`
- Replace `:arn:aws:` with `:arn:${AWS::Partition}:`
- Remove the `Xray` policy we conditionally attach - SAM does this automatically (much like the `BasicExecutionRole` policy it attaches to all Lambda functions so they can generate logs)
- Add missing TracingConfig from alert processor
- Deployed to my dev account
=> Generic URL suffix + AWS partition

internal/log_analysis/log_processor/common/common.go
Increase SDK retries from 10 to 20.
Before this change I was seeing 1 SNS failure every 2 days regularly (likely due to DNS ttls). After this change it stopped. 
Ran for 1.5 weeks in dev account.
=> Increase retries for log processing.

docs/gitbook/quick-start.md
> Why are you making this change? Please provide a reference to any related issues and PRs
This PR adds a section in the docs that has to do with using an EC2 instance as the deployment host (instead of a local machine). It also resolves #96 
- Add section in `Get started`
Markdown checker
=> [Docs] Add segment for EC2 deployment

api/lambda/users/models/api.go, internal/core/users_api/api/invite_user.go, internal/core/users_api/api/invite_user_test.go, internal/core/users_api/api/list_users.go, internal/core/users_api/api/list_users_test.go, internal/core/users_api/api/remove_user.go, internal/core/users_api/api/remove_user_test.go, internal/core/users_api/api/update_user_test.go, internal/core/users_api/gateway/add_user_to_group.go, internal/core/users_api/gateway/add_user_to_group_test.go, internal/core/users_api/gateway/delete_user.go, internal/core/users_api/gateway/delete_user_test.go, internal/core/users_api/gateway/mock_gateway.go, internal/core/users_api/gateway/users_gateway.go, tools/mage/deploy.go
Add ListUsers and RemoveUser endpoints for #90 
- Add `ListUsers` and `RemoveUser` endpoints, as we had them originally
- Remove `Role` from `InviteUser` input struct - only one role is actually supported
I left the "userPoolID" as part of the request. Since we only have one user pool, the `users-api` could look it up, but for simplicity I just left it how we had it before. The users-api and organization-api could use a more thorough redesign for the open-source single-tenant model to address tech debt like that.
Haven't had a chance to deploy it and invoke it in my test account, but wanted to get the PR up for @3nvi to work with
=> Add ability to list and remove users

internal/compliance/resources_api/handlers/compliance.go, internal/core/analysis_api/handlers/compliance.go
Fixes #97 
The policy and resource overview pages include a summary of their compliance status - is this policy/resource PASS or FAIL (or ERROR) in aggregate?
That information is not explicitly stored anywhere - to determine overall pass/fail status, we have to scan the `compliance-api` to find all applicable (policy, resource) entries and compute the aggregate status.
Since this is a relatively expensive operation, the original idea was to cache the overall pass/fail status for every policy and resource to avoid constantly scanning the compliance table. However, this may have been a premature optimization and creates an unexpected user experience (#97)
I was going to remove the caching completely, but it turns out we do still need it in one place - `ListPolicies` and `ListResources` both …
=> Reduce compliance caching

tools/mage/deploy.go, tools/mage/deploy_test.go
@rleighton reported an issue where deployments in `us-east-1` would fail. This was corroborated by another user is `us-east-2`. I was not able to reproduce in `us-west-2`.
It turns out the s3 global endpoint format we were converting to is not viable in certain regions, and also the regional endpoint we were trying to convert from was actually a global endpoint in some regions. It appears the `aws cli` is region aware when producing these template URLs, so we need to be more resilient in handling them.
- Changed format of transformed template URLs to match globally supported format suggested by @kostaspap 
- Added checks to not change the URL if it is already a global endpoint
- deployed in `us-west-2`, `us-east-1`, `us-east-2`, and `eu-west-1`
=> Make CFN post-processing more resilient

internal/log_analysis/log_processor/parsers/pantherlog_test.go, internal/log_analysis/log_processor/parsers/patherlog.go
Previously I changed the "set" serialization to emit nothing when set is empty. This was wrong because the set is "non-nil" and the omit empty tag will still emit the  field which results in incorrect json.
This only happens when we parse something like: "arn": "" . We skip blank strings populating the set BUT the set gets made (non-nil) but empty. A corner case.
Emit a [] when set is empty.
mage test:ci
ran in dev account
=> Fix regression dealing with empty sets in panther log

internal/log_analysis/rules_engine/src/engine.py, internal/log_analysis/rules_engine/src/main.py
During development of a CloudWatch dashboard for the rules engine I needed to make some improvements to logging and error handing.
* put try/except around json event parsing in case of bad data (found some, source of another PR)
* log number of matches and match time (will be graphed in dashboard)
* log name of rule if a rule exception was thrown (I was testing a crashme rule and found this)
In my dev account using new dashboard.
=> Handle bad json data in rules engine, log matches and execution time

internal/log_analysis/log_processor/sources/s3_client_cache.go
It is not necessary or desired to set the external id in the s3_client_cache.
Removed.
Ran for 3 hours in dev env with no issues.
=> Remove use of session external id in s3_client_cache.go

internal/core/analysis_api/handlers/dynamo.go, internal/core/analysis_api/handlers/util.go, internal/core/analysis_api/handlers/util_test.go
Fixes: #159 
Standard string sorting depends on capitalization, which leads to unexpected results. For example, `AWS.EC2.Volume` comes before `AWS.EC2.VPC` in the resource type dropdown in the policy editor, but the response from the backend is sorted in the other order.
- Sort policy/rule tags, resource types, and suppressions case-insensitive
- Added unit tests for case-insensitive sorting
- Deployed to dev account, verified EC2 example has been fixed:
=> Case-insensitive attribute sorting for analysis-api

internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/rules_engine/src/engine.py
Rules were not being cleared on update and were accumulating. Disabled/deleted rules would continue to run.
Clear dict before update.
Tested in dev account where disabled rules continued to run, after change they did not.
=> Clear rules on update

deployments/backend.yml, deployments/core/analysis_api.yml, deployments/core/buckets.yml, internal/core/analysis_api/main/integration_test.go, tools/mage/test_namespace.go
Fixes: #120
Panther currently creates five S3 buckets, which have names of the form "panther-(name)-(accountId)-(region)".  We chose this format because this is how AWS names default buckets: the accountId + region generally guarantee global uniqueness. However, there are security problems associated with a predictable name, especially one that includes an accountID (#120)
So what does an ideal bucket name look like?
- Must be globally unique (S3 is a global service)
- Must persist across deployments
- Should not leak any information about the account
- Should resist enumeration attacks (i.e. include randomness)
Fortunately, CloudFormation can autogenerate bucket names which satisfy all of the above requirements: `(stack)-(resource)-(random suffix)`
**This is a breaking change**, but we …
=> Autogenerate S3 bucket names

deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml, deployments/auxiliary/cloudformation/panther-log-processing-infra.yml, deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml, deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml, deployments/backend.yml, deployments/compliance/compliance_api.yml, deployments/compliance/remediation.yml, deployments/compliance/resources_api.yml, deployments/compliance/snapshot.yml, deployments/core/admin_api.yml, deployments/core/analysis_api.yml, deployments/core/appsync.yml, deployments/log_analysis/alerts.yml, deployments/web/server.yml
The following is a fix for an earlier PR #61 however it turns out AWS IAM service principals do not use the regional suffix. 
- Update IAM Service principals to use hardcoded values.
- Confirmed IAM SP within AWS CN.
=> Update AWS IAM Service principals

api/lambda/organization/models/api.go, api/lambda/organization/models/table.go, internal/core/organization_api/api/create_organization.go, internal/core/organization_api/api/update_organization.go, internal/core/organization_api/api/update_organization_test.go, internal/core/organization_api/main/integration_test.go, internal/core/organization_api/table/update.go, internal/core/organization_api/table/update_test.go, tools/mage/deploy_frontend.go
Provides backend support for users to opt into error reporting.
Closes #152 
- Support `errorReportingConsent` in the org database
- I wanted to put "consent" in the name so it was explicitly clear that the field is populated by user consent
- This is just for frontend errors logs, right? We could in theory also send backend error logs, but that would take more work. Should the same consent flag apply to both? I don't see why not
- Hide `docker push` output by default (per @3nvi suggestion), which is more consistent with the rest of the deploy process
- Unit tests
- Deploy + integration test
=> Support errorReportingConsent

internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go, internal/log_analysis/log_processor/parsers/awslogs/s3_server_access_test.go, internal/log_analysis/log_processor/sources/s3_client_cache.go
Monitoring detected a failed log parse for s3 access logs. Looking into it a 'S3.EXPIRE.OBJECT' event was not able to be parsed because we require an http status code be set. This seems to be a backend triggered transaction that is logged that has no http associated attributes.
Removed required validations for HttpStatus field.
mage test:ci
deployed to dev account
=> S3accesslogs do not require httpstatus

go.mod, go.sum, internal/compliance/aws_event_processor/processor/classify.go, internal/compliance/aws_event_processor/processor/ec2.go, internal/compliance/aws_event_processor/processor/ecs.go, internal/compliance/snapshot_poller/models/aws/ecs_cluster.go, internal/compliance/snapshot_poller/pollers/aws/acm_certificate.go, internal/compliance/snapshot_poller/pollers/aws/awstest/ecs.go, internal/compliance/snapshot_poller/pollers/aws/clients.go, internal/compliance/snapshot_poller/pollers/aws/ec2_volume.go, internal/compliance/snapshot_poller/pollers/aws/ecs_cluster.go, internal/compliance/snapshot_poller/pollers/aws/ecs_cluster_test.go, internal/compliance/snapshot_poller/pollers/aws/poll.go, internal/compliance/snapshot_poller/pollers/lambda_test.go, internal/compliance/snapshot_poller/pollers/utils/logging.go, web/src/constants.ts
This change adds support for ECS Cluster scanning to the Cloud Security suite. Closes #166.
- Updated the snapshot poller to be able to scan ECS Clusters
- Updated the aws event processor to be able to process ECS API calls
- Updated the frontend constants list to include `AWS.ECS.Cluster`
- A few minor tweaks of various inconsistencies on some unrelated aws event processor and snapshot poller code
- Removed the `ServicePollersOrdered` slice, it was just place we were duplicating work for a feature that has been deprecated (feature is still supported, it's just less efficient now but again its deprecated)
- Manually tested in my dev account the following activities:
- Tested with both long and short names (full ARNs and just the name)
- Account wide ECS scans
- Updating tags on an ECS …
=> ECS Cluster Scanning Support

internal/log_analysis/log_processor/sources/s3_client_cache.go, tools/mage/glue_namespace.go
Users needed to pick a time range to update partitions. Users may not know the appropriate time range.
The start time is taken from the CreateTime of the table and end time is the current time. This will ensure all partitions are bought current and the user need not specify.
ran locally
mage test:ci
=> Update mage glue:sync to not require input of time range

web/src/components/forms/signin-form/index.tsx, web/src/components/utils/auth-context.tsx
This PR makes sure that the label part of the OTP url  is not `undefined`, but contains the associated user's email.
Closes #187 
- Rename `username` to `email` on the signin flow params
- Pro-actively add `email` attribute on cognito user 
- Locally & Remotely
- With same & new user
- Safari, Mozilla & Chrome
=> Fix undefined TOTP label

.gitignore, deployments/auxiliary/README.md, deployments/auxiliary/cloudformation/Makefile, deployments/auxiliary/cloudformation/README.md, deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml, deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml, deployments/auxiliary/terraform/README.md, deployments/auxiliary/terraform/panther-deployment-role.tf, docs/gitbook/quick-start.md, web/src/pages/overview/index.tsx
Adding a Panther deployment role and other minor doc changes
Closes #145 
Closes #178 
- Add a Panther deployment role (CloudFormation and Terraform versions)
- Reset our public templates S3 bucket with what is in the master branch of this repo
- Add `makefile` so Panther team can easily upload public templates to our bucket
- Fix small typo in frontend error message
- Deployed Panther end-to-end with this IAM role
- Was able to successfully create with CloudFormation and with Terraform
=> Deployment role and doc updates

deployments/backend.yml, deployments/core/admin_api.yml, deployments/core/cognito.yml, internal/core/custom_message/api/forgot_password.go, internal/core/custom_message/email/clients.go, internal/core/custom_message/main/lambda.go
We have a custom format for password reset emails, but Cognito wasn't using it. Turns out we had the custom message Lambda function, it was just never connected to Cognito (we used to build the Congito user pool with an API call instead of CloudFormation)
Closes #190 
- Connect `panther-custom-message-trigger` Lambda function to Cognito
- Remove some dead code in `users-api` related to how we used to set up Cognito pools
- Deployed to dev account, triggered password reset flow:
Clicking the link in the email worked and I was able to reset the password and login with the new password
We are redesigning the `users-api` before v1; the custom message trigger can probably go there as well. It's a bit strange having an entire Lambda function for just this 1 use case (forgot password)
=> Connect Cognito custom message trigger to Lambda function

docs/gitbook/quick-start.md, tools/mage/build_namespace.go, tools/mage/deploy.go
#99 added a `deploy_precheck` routine which fails early if something is wrong with the user environment. I included `swagger` in those checks, but I forgot swagger is actually not required to deploy Panther.
`swagger` generates the Go files in `api/gateway`, but those files are already checked into the repo. So a fresh clone + deploy should not require swagger at all.
Closes #204 
Closes #198 
- Remove `swagger` from the deploy precheck
- Explicitly check for swagger existence right before invoking it so that we can still show the same helpful error message
- A few minor updates to the quick start / deployment documentation
- Deployed from a fresh clone of Panther without running `mage setup:all`
=> Remove swagger from deploy precheck

deployments/auxiliary/cloudformation/panther-compliance-iam.yml, go.mod, go.sum
An external contributor reported an error in the snapshot poller when trying to call `ListTagsForResources` on an SNS Topic. Although we do not scan SNS Topics, we scan CloudFormation stacks and do drift detections, so we need to grant the snapshot poller the permissions needed to do drift detections on these resources.
Note that even without the correct permissions, we can still perform the stack drift detections. The resources we don't have permissions to scanned just won't be in the results. So if a stack creates two IAM roles (supported resources) and one SNS Topic (unsupported resource), we are still able to get the drift results from the two IAM roles, just not the SNS Topic. This change allows us to still get drift detection results for SNS Topics despite us not supporting them as …
=> Updated audit role permissions

web/src/components/linkify.tsx, web/src/pages/alert-details/subcomponent/alert-details-info.tsx, web/src/pages/policy-details/subcomponents/policy-details-info.tsx, web/src/pages/rule-details/subcomponents/rule-details-info.tsx
This PR makes sure that all the URLization from data that the user has entered gets treated the same way. This helps with:
1. Not having to re-write the same logic more than once
2. Having a unified visual experience
3. Giving us parse safety
This doesn't include links that we create, but links that get parsed from stuff like runbook, reference, etc.
- Add a single `linkify` component
- Migrate all user-based linkification to it
- Manually & Locally
=> Generalize user-based input linkification

.github/CODEOWNERS
Automatically add Alex as a reviewer to PRs
- Add Alex to default group within CODEOWNERS
N/A
=> Add Alex to default owners

deployments/log_analysis/log_processor.yml
Fixing permissions issue. 
Closes #201 
- Log processor needs to confirm SNS->SQS subscription. It was missing the appropriate permissions. 
- Setup SNS->SQS cross-account in my dev environment. I was able to get the subscription setup.
=> Adding permissions required for cross-account subscription confirmation 

web/src/components/utils/auth-context.tsx
- First time users had to re-enter email/pass and MFA the first time the login in UI
This PR resolves this #142 
- Added authenticated as true when a first time users MFA is verified
- Locally
=> Added setAuthenticated when users verify their MFA for the first time

deployments/backend.yml, deployments/log_analysis/alerts.yml, deployments/log_analysis/rules_engine.yml, internal/core/alert_delivery/models/api.go, internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go, internal/log_analysis/alert_forwarder/forwarder/models.go, internal/log_analysis/alert_forwarder/forwarder/models_test.go, internal/log_analysis/alert_forwarder/main/lambda.go, internal/log_analysis/log_processor/parsers/osseclogs/eventinfo.go, internal/log_analysis/log_processor/parsers/osseclogs/eventinfo_test.go
This PR introduces the Alert forwarder Lambda. This Lambda listens for changes in the `panther-alert-dedup` table. `panther-alert-dedup` table is used for alert deduplication 
The Lambda takes the DDB update and stores the associated information on the `panther-log-alerts-info` table. This table will eventually replace `panther-log-alerts` table. 
Closes #183 
- Added new Lambda and DDB table. 
- Unit tests
- Deployed in my account
=> Adding Alert forwarder component

deployments/panther_config.yml
The initial policies/rules set was set to a specific tagged release of the `panther-analysis`, this switches it to latest so it doesn't have to be updated all the time.
- Pointed initial analysis set at latest
- Copied the URL into my browser and the proper pack was downloaded
=> Updated initial analysis sets to always point to latest

web/src/components/utils/auth-context.tsx, web/src/routes.tsx
Small perf optimization in order to skip un-necessary re-renders. Will save a few `ms` of CPU time in certain user actions
- Add component memoization in `AuthProvider` and `Routes`
- Locally
=> Add memo to key components

web/src/client.ts
Loading UI with no session throws an unhandled rejection for Auth.currentSession()
- Catching error and returning null jwtToken
- Run locally with clear cache no error should be thrown
=> Catching currentSession error and returning null jwtToken

docs/gitbook/quick-start.md, tools/mage/util.go, web/src/client.ts
A few critical fixes before releasing v0.3.0, found during QA testing
- Update documentation to reference 0.3.0 as the latest version
- We should consider making a `stable` tag or similar that follows the latest release
- Revert #250 - it breaks the login flow (I was not ever able to login to a fresh deployment)
- Allow spaces in user input during first-time setup (e.g. company name = "Panther Labs")
- Deployed fresh to dev account, logged in, viewed/edited policies, reset password, invited more users, etc
=> v0.3.0 release

web/src/client.ts, web/src/components/guarded-route.tsx
- Fixing issue with login getting an exception
- Checking referrer exists before access pathname
- Locally:
a. Login with newly invited user
b. Logout and re-login
c. Login in a clean browser
Closes #229
=> Safeguard pathname when referrer in undefined on guarded-route

web/src/components/modals/delete-user-modal.tsx
- When user deletes himself can still navigate to the UI
Resolves #231  
- Triggering the signOut on delete modal onSuccess function
- Locally
=> Added signOut as props onSuccess of delete modal

web/src/app.tsx, web/src/components/fields/checkbox.tsx, web/src/components/fields/radio.tsx, web/src/components/fields/switch.tsx, web/src/components/forms/common/rule-form-test-fields.tsx, web/src/routes.tsx
Currently there is an issue with the way our cache-friendly radio buttons work with our form-management library and pounce.  This causes bugs where a value update is applied on the wrong fields.
I reported the [caching issue to the related repo and I got some upvotes](https://github.com/jaredpalmer/formik/issues/2268), so until this is fixed, I'm removing all memoization & caching from our:
* checkboxes
* radio
* switches
Closes #210 
- Remove caching & optimizations from button-like form elements
- Remove un-needed props
=> Fix radio buttons on policy tests

web/src/app.tsx, web/src/routes.tsx
Currently, we perform API calls to check for user error reporting consents even when the user is not authenticated. This PR moves the component in the "authenticated user" part of the app, in order to only fire if the user is authenticated
- Move `PromptController` component
- Observed XHR requests remotely & locally
=> Move prompt controller to authenticated section

api/lambda/users/models/api.go, go.mod, go.sum, internal/core/users_api/api/list_users.go, internal/core/users_api/api/list_users_test.go, internal/core/users_api/api/remove_user.go, internal/core/users_api/api/remove_user_test.go, internal/core/users_api/gateway/list_users.go, internal/core/users_api/gateway/list_users_test.go, internal/core/users_api/gateway/mock_gateway.go, internal/core/users_api/gateway/users_gateway.go, tools/mage/deploy.go
Some small changes to the `users-api`, following up from #213 
Closes #217 
- The `users-api` service will refuse a user deletion request if that user is the last one remaining
- The `limit` and `paging` info in the `ListUsers` endpoint has been removed
- There will almost certainly only ever be 1 page of users, the frontend does not and will not add paging here. In the rare event we do need to page over the results, the backend handles this before returning
- Deployed to dev account, was able to list users but not able to delete myself (because I was the only user)
(we may want a more helpful error message)
=> users-api: prevent deleting last user and move pagination to backend

docs/gitbook/log-analysis/supported-logs/README.md
A new parser was introduced in #215, updating the supported-logs docs.
* Add section for OSSEC logs to supported-logs
* Fixed typo in nginx url
- Verified the URLs point to the correct resources
- Ran `mage test:ci` for spell checks
=> Update docs for OSSEC.EventInfo logs

deployments/core/outputs.yml, web/src/components/auth-page-container.tsx, web/src/pages/compliance-overview/index.tsx, web/src/pages/compliance-overview/skeleton.tsx
I found a bug in the alerting workflow after we split the pages. The policy/alert links were missing the new path prefixes.
Made some additional wording edits too.
Request - @3nvi can we make the "Resource Platforms" breakdown by type?
- Fix alert/policy urls
- Reword the auth page text again (can we also increase the padding around the text?)
- Rename the chart headers on the Cloud Security overview.
- Deployed into my test account
=> Policy/Alert URLs + Cloud Sec Overview Wording

deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
After renaming the SQS queue where Panther receives notifications for new S3 data, we need to update our CFN templates that create subscriptions. 
- Updated name of the SQS queue
=> Fixing name of Panther SQS queue

api/lambda/source/models/api.go, api/lambda/users/models/api.go, go.mod, go.sum, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/update_integration_test.go, internal/core/source_api/ddb/update_item.go, internal/core/source_api/main/integration_test.go, internal/core/users_api/api/get_user.go, internal/core/users_api/api/invite_user.go, internal/core/users_api/api/invite_user_test.go, internal/core/users_api/api/update_user.go, internal/core/users_api/api/update_user_test.go, internal/core/users_api/gateway/create_user.go, internal/core/users_api/gateway/create_user_test.go, internal/core/users_api/gateway/mock_gateway.go, internal/core/users_api/gateway/update_user.go, internal/core/users_api/gateway/update_user_test.go, internal/core/users_api/gateway/users_gateway.go, tools/mage/fmt_license.go
Fixes `UpdateUser` and `UpdateIntegration` endpoints to return the modified settings.
Closes #324 
Closes #325 
Closes #326
- `users-api`
- `UpdateUser` returns the new user settings. The Cognito update API does not have this information, so we just get it in the backend before returning.
- Removes some redundant structs
- `source-api`
- All of the update endpoints return the full integration model in their response
- bugfix: `ScanEnabled` in `PutIntegration` is optional, but if omitted the API panics with a nil pointer dereference
- bugfix: `UpdateIntegrationSettingsInput` includes an `AWSAccountId` field, but that field is completely ignored in the backend. It doesn't make sense to update the account ID of an existing source, so this field has been removed.
- bugfix: The integration …
=> Update endpoints return modified settings

internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go, internal/compliance/snapshot_poller/pollers/aws/s3_bucket_test.go
The snapshot poller was failing to scan buckets in `us-east-1`. That is because the `get-bucket-location` API call does not work for buckets in `us-east-1`.
- If the `get-bucket-location` API call returns `null`, then assume the bucket is in `us-east-1`
- Deployed to development account and manually verified
- Added new unit test to handle this case
=> Bug scanning buckets in us-east-1

docs/gitbook/log-analysis/supported-logs/README.md, go.mod, go.sum, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164_test.go, internal/log_analysis/log_processor/registry/registry.go, web/src/constants.ts
This PR introduces a new Parser for Syslog RFC3164 formatted logs as planned in #200.
* Created new parser for RFC3164 format (BSD syslog messages)
* Updated parser documentation for syslog.
* Added `Syslog.RFC3164` as a whitelisted log type for the frontend UI.
* Added `sysloglogs.RFC3164Parser` to the log registry.
* Added examples from https://tools.ietf.org/html/rfc3164#section-5.4 as unit tests.
- Unit tests
Waiting on #304 and #261 to merge before merging from master and running an end-to-end test.
=> Syslog parser for RFC3164 formatted logs

deployments/auxiliary/cloudformation/panther-log-processing-iam.yml, deployments/core/source_api.yml, docs/gitbook/operations/runbooks.md, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164_test.go
A function was renamed in some places but not others it appears.
- Renamed the function
- `mage fmt` caught some things
- Unit tests
=> Fixing a misnamed function

internal/compliance/snapshot_poller/pollers/aws/ecs_cluster.go, internal/compliance/snapshot_poller/pollers/aws/ecs_cluster_test.go
Sometimes a request gets to the snapshot poller to scan a non-existent resource. This is most common right after the resource is deleted, as typically before it is deleted there are several API calls removing things from it which trigger a scan before the actual delete API call comes through, then the resource gets deleted before we can scan it. When that happens, the snapshot poller needs to be resilient and not log an error and certainly not panic. This change adds more graceful handling of non-existent resource scanning to the ECS cluster poller. This functionality is already present for most other pollers.
We observed this behavior in our internal deployment of Panther.
- When DescribeClusters returns no error but also no clusters, assume it's because we received a scan request for a …
=> Poller Scanning Nonexistant ECS Clusters Fix

package-lock.json, package.json
`Acorn`, a JS package that other packages have it as a dependency, recently reported a vulnerability. The packages that we are using have not yet updated to the patched version and [some won't](https://github.com/webpack/webpack/issues/10516) due to the fact that it requires bumping their packages to a  breaking change version.
Instead of waiting a few days or removing the auditing all-together, I opted for a local resolution. Specifically, I installed a hook for forcing the resolution of the `acorn` package (for all packages that have `acorn` as a dependency) to the patched version. Whenever `webpack` and `eslint` upgrade their dependencies to handle it themselves, we can safely remove this hook. Until then, it's the only way to fix the `npm audit` outputs.   
---
**These changes will be …
=> Force npm resolutions for acorn

package-lock.json, package.json
Funnily, another sec vulnerability was reported today, which created 605 issues for us. This PR forces all upstreams to use a stable version of this dependency.
Related issue: [https://www.npmjs.com/advisories/1490](https://www.npmjs.com/advisories/1490)
- Force upstreams to install stable `kind-of` package
- Locally by running `npm audit` and through the CI checks of this PR
=> Patch kind-of to secure version

deployments/auxiliary/cloudformation/panther-compliance-iam.yml, deployments/onboard.yml
Currently it is not possible to deploy from master due to an issue in the CFN templates. The `onboard.yml` is providing property `DeployAuditRole` to the `panther-compliance-iam.yml` template, but such property doesn't exist. 
- Removed `DeployAuditRole` property from `onboard.yml`
- Removed default `MasterAccountId`. Such a default doesn't really make sense, the template cannot be deployed without it. 
- Successfully deployed to my dev account.
=> Fixing deployment issue

internal/compliance/alert_processor/processor/processor_test.go, internal/compliance/aws_event_processor/processor/process.go, internal/compliance/compliance_api/main/integration_test.go, internal/compliance/resource_processor/processor/analysis_api.go, internal/compliance/resource_processor/processor/handler.go
When #357 merged, the resource-processor was broken because it relied on the default behavior of `GetEnabledPolicies` which was removed in that PR. This adds the explicit analysis type to the call.
Additionally, I added two more events to the aws-event-processor ignore list that were pointed out by @rleighton as particularly noisy.
- Added explicit analysis-type to `GetEnabledPolicies` call
- Updated `policy-api` references to `analysis-api`
- Added two new events to `aws-event-processor` ignore list 
- Deployed to dev account and manually verified
=> Minor Fixes

api/graphql/schema.graphql, api/lambda/alerts/models/api.go, internal/log_analysis/alerts_api/api/api.go, internal/log_analysis/alerts_api/api/get_alert.go, internal/log_analysis/alerts_api/api/get_alert_test.go, internal/log_analysis/alerts_api/api/list_alerts.go, internal/log_analysis/alerts_api/api/list_alerts_test.go, internal/log_analysis/alerts_api/table/table.go, web/__generated__/schema.tsx, web/src/pages/AlertDetails/AlertDetails.tsx, web/src/pages/ListAlerts/ListAlerts.tsx
Return the dedup string that was used in alert creation. This value will eventually be displayed by frontend. 
Closes #345 
- Modified Alerts API to return the dedup string that was used in generation of an alert.
- Added unit test for ListAlerts API operation
- Unit tests
- Deployed and verified in my dev environment
=> Returning the dedup string that was used in an alert creation

tools/mage/deploy_certificate.go
ACM has a default limit of 20 imported ACM certificates within a one year period. Once that limit is reached, you have to open a case with AWS support to get your limit raised to 1000. Either way, it is possible to hit the maximum number of imported ACM certificates for an AWS account in which case the Panther deployment will fail unless you specify an existing certificates ARN.
Since we already support falling back to IAM server certificates for cases where ACM is not available at all, this PR allows us to also fall back to IAM server certificates if the maximum number of ACM imports has been reached already.
- Updated the deploy certificate step of mage deploy
- Tested by deploying in an account where I had reached the max ACM certificate import limit
=> Fallback to IAM when ACM limit reached

package-lock.json, package.json
When packages were vulnerable, we added forced resolutions for the vulnerable packages, in order to install the resolved versions of those.
All upstreams have now updated their installations and all hotfixes have been issues by the related packages as bugfix versions. Thus we don't need to force resolutions anymore.
Closes #371 
- Remove forced resolutions
- Update package-lock
- `npm audit`
=> Remove hotfix for auditing

internal/log_analysis/datacatalog_updater/main/lambda_test.go, pkg/awsglue/glue.go, pkg/awsglue/partition.go, pkg/awsglue/partition_test.go
The datacatalog updater used a function that hard coded elements of the StorageDescriptor for a table.
We made a change to the cloudformation defining tables but the change was not made in the hardcoded description in partition.go. This caused mis-matches from old partitions to new partitions created by the lambda.
The datacatalog updater now uses the common code (used by SyncPartitions()) that does not used hard coded StorageDescriptor config but reads it from the partition's table.  This avoids updating duplicated code and future-proofs this lambda for a time when we no longer will have StorageDescriptors hard coded anywhere in the code base, since the config is read from the live table.
* Refactor the partition's CreatePartition() to call the metadata table's CreateJSONPartition()
* …
=> Have datacatalog updater us the common function to create partitions 

README.md
Make it easier to sign up for Slack and find out about our tutorials!
=> [readme] add explicit link to Slack and tutorials

internal/core/alert_delivery/models/api.go, internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/outputs_test.go, internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go, internal/log_analysis/alert_forwarder/forwarder/models.go, internal/log_analysis/alert_forwarder/forwarder/models_test.go, internal/log_analysis/log_processor/parsers/awslogs/pantherlog.go, internal/log_analysis/rules_engine/src/__init__.py, internal/log_analysis/rules_engine/src/alert_merger.py, internal/log_analysis/rules_engine/src/engine.py, internal/log_analysis/rules_engine/src/output.py, internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_output.py, internal/log_analysis/rules_engine/tests/test_rule.py
Allowing users to customize alert title using Python
Closes #238 
- Rule's can now have an additional `title` method. When a rule matches an event, we run the "title" method to specify the title of the alert. 
- Added unit tests
- web was failing on `npm audit` command. Did `mage setup:web` and that modified the `package-lock.json` and now it passes
- Unit tests
- Deployed to my account. A rule with the following body: 
Generated the following alert:
=> Allowing users to customize alert title using Python

internal/log_analysis/log_processor/parsers/patherlog.go, tools/athenaviews/athenaviews_test.go
Found wrong name in one of Panther fields. 
- Renamed `p_any_ip_domain_names` to `p_any_domain_names`
- unit tests
=> Fixed naming issue

api/gateway/analysis/api.yml, api/gateway/analysis/models/enabled_policy.go, internal/core/analysis_api/handlers/get_enabled_policies.go, internal/core/analysis_api/main/integration_test.go, internal/log_analysis/rules_engine/src/__init__.py, internal/log_analysis/rules_engine/src/alert_merger.py, internal/log_analysis/rules_engine/src/analysis_api.py, internal/log_analysis/rules_engine/src/engine.py, internal/log_analysis/rules_engine/src/main.py, internal/log_analysis/rules_engine/src/output.py, internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_engine.py, internal/log_analysis/rules_engine/tests/test_output.py, internal/log_analysis/rules_engine/tests/test_rule.py
Finalizing the backend changes that will make it possible to configure the dedup time period. 
Closes #348 
- Modified the `GetEnabledPolicies` (used to return rules) to return the optional `dedupPeriodMinutes` property
- Modified rules-engine to use that property when doing the deduplication. In case no value is specified, it falls back to 60'. This gives us backwards compatibility with rules that have no value configured. 
- Updated the way Rule is initialized to avoid excessive number of constructor arguments (and make sure the python linter is not complaining)
- Unit tests for new functionality
- Integration tests for new analysis-api functionality
- Deployed to my account and seen the new functionality working.
=> Modified rules-engine to use the dedup time period returned by the analysis-api

.circleci/config.yml, tools/mage/test_namespace.go
This PR removes `npm audit` call from `mage test:ci` and adds it as a separate non-required check
- Alter `mage test:ci`
- Create separate circleci optional check
- CI of this PR
=> Move npm audit outside of mage

cmd/opstools/s3queue/integration_test.go, cmd/opstools/s3queue/s3queue.go, cmd/opstools/s3queue/s3queue/main.go, cmd/opstools/s3queue/s3queue_test.go, cmd/opstools/testutils/testutils.go, docs/gitbook/operations/ops-home.md, tools/mage/build_namespace.go
There is a need operationally for customers to backfill data into log processing. This tool will list an S3 bucket and push processing notifications into log processing.
This tool is also useful for testing log processing as specific files can be pushed through the processing.
* Added ops tool s3queue
* Refactored test code
* Added ability to cross compile so customers can run both on desktop and on ec2 instances.
mage test:ci
I've been using this for load testing log processing.
=> New opstool: s3queue

internal/core/analysis_api/handlers/create_rule.go
Setting default value for dedup time period
- Setting default value for dedup time period. Golang swagger doesn't respect the swagger defaults
=> Setting default value

api/lambda/source/models/api.go, api/lambda/source/models/integration.go, deployments/core/source_api.yml, deployments/log_analysis/log_processor.yml, internal/core/source_api/api/check_integration.go, internal/core/source_api/api/get_integration_template.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/update_integration.go, internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go, pkg/testutils/awsmocks.go
The last backend change to support the new onboarding flow. 
In the new flow, we have one CFN stack per log source onboarded. This means we are having one IAM Role per log source. IAM roles have as suffix the integration label (lowercased, with empty spaces replaced with `-`)
This change modifies the log processor so that it assumes the appropriate role for the S3 object it is about to process. 
- Sources API now stores the LogProcessing role ARN in the sources DB
- Log processor maintains a cache of log sources. When it receives an S3 Object it checks it if comes from a known S3 bucket+ S3 prefix. If it comes, it assumes the given role and reads data from S3. If it doesn't come from a known s3 bucket, we throw an exception. The message will eventually be retried. This protects us from …
=> Log processor assumes role retrieved from sources api 

docs/gitbook/quick-start.md, internal/core/users_api/api/cognito_trigger.go, tools/mage/deploy.go, tools/mage/setup_namespace.go
A few very small fixes to close some issues
- To be safe, Swagger is now required for deployment (relying on timestamps to not run swagger has proved unreliable). Closes: #455 
- `mage deploy` warns you if you're not deploying a tagged release. Closes: #454 
- Reword password reset email - it is required. Closes: #308 
- `mage test:go`
=> Check swagger and git tags when deploying

tools/mage/deploy.go
#472 actually doesn't work because you need to run `swagger version` , not just `swagger`. I had the fix locally but forgot to push it before merging!
- `mage deploy` worked
=> Add 'version' to swagger command

api/lambda/source/models/integration.go, internal/core/source_api/api/get_integration_template.go, internal/core/source_api/api/get_integration_template_test.go, internal/core/source_api/api/put_integration.go
The frontend is currently generating the CFN stack name for an integration when a user clicks the "Launch Stack" button. This stack name is used subsequently in order to provided guidance to the users when they need to edit/update their sources. 
The problem is, the frontend was currently generating the stack name using the IntegrationLabel. If a user however updates the label of an integration, then the instructions provided by the frontend will be wrong since they will be using the *current* label, not the label with which the source was created. 
After discussion with @3nvi  we decided to move the stack-name generate mechanism to the backend and make sure the backend keeps the CFN stack name that will be used when instructing users to update their templates. 
- Sources_api now …
=> Generating and storing CFN stack name

internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_rule.py
Fixes #460 
In case title or dedup functions throw exception, we use default values instead of dropping event. 
This is meant to improve system stability and to make sure that no crucial events will be ignored. 
- Switching to use default values for alert title and dedup string in case the dedup function or title function throw exception
- Unit testing.
=> Improving stability when running rules

.all-contributorsrc, docs/CONTRIBUTING.md
Add an easy way to manage people that have contributed to the platform
- Update `CONTRIBUTING.MD`
- Add `.all-contributorsrc`
N/A
=> Add all-contributors spec

tools/mage/util_cfn.go
Deploying on a clean account was not succeeding. 
- Mage uses a utility method to identify if the error returned when describing a stack is that a stack doesn't exist. The utility method is here: https://github.com/panther-labs/panther/blob/master/tools/mage/util_cfn.go#L131-L138
Updated code to return original exception
- Was able to deploy
=> Returning original error

web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
Passing additional parameter needed by CloudSec stack
- Passing parameter where panther is deployed
@3nvi I think it looks good
@rleighton  this should fix the template
=> Fixing launch template

internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_engine.py, internal/log_analysis/rules_engine/tests/test_rule.py
Currently the default dedup string value is the rule id, which even though is a good way to distinguish, it can be confusing to people when looking the alerts through the UI (and seeing the dedup string having same value as rule id). 
- Updating default dedup string to have different value: `defaultDedupString:` + rule ID
- unit testing
=> Changing default dedup string value

api/gateway/analysis/api.yml, api/gateway/analysis/models/rule.go
Marking dedup period as required. See discussion: https://github.com/panther-labs/panther/pull/533#discussion_r396813968
- Marking dedup period as required. 
Dedup period was already being populated to default value [here](https://github.com/panther-labs/panther/blob/6d3f3887be8c4b9f704986d81d06190df0dcfe7d/internal/core/analysis_api/handlers/bulk_upload.go#L216-L223) and [here](https://github.com/panther-labs/panther/blob/afc9e3f4ced443341b46f8a9f5bbb981924c20bb/internal/core/analysis_api/handlers/create_rule.go#L76-L79). 
- Deployed and was able to list pre-existing rules, edit rule ,update rule, create rule. 
- Verified that I was able to upload rules through analysis tool
```
(venv) kostas@jaguar projects $ pather_analysis_tool upload --path …
```
=> Marking dedup period as required

tools/mage/deploy_onboard.go
Pinning real-time events template to specific version. This is needed since in case the template is updated, users running older versions of the software might fail to deploy since latest template might be incompatible
- I've set the version to the latest one in the S3 bucket. 
- Deployed. Seen stackset deployed.
=> Pinning template to specific version

internal/compliance/aws_event_processor/processor/process.go
- add appsync StartSchemaCreation to whitelist (sets off alarms during deployments)
mage test:ci
=> Whitelist StartSchemaCreation in aws event processor

README.md, docs/gitbook/development.md, docs/gitbook/quick-start.md, tools/mage/deploy.go
If Swagger needs to be built, sometimes there will be a race condition on a fresh deploy:
```
08:07:46        INFO    build:api: generating Go SDK for 4 APIs (api/gateway/*/api.yml)
08:07:46        FATAL   failed to read deployments/bootstrap.yml: open deployments/bootstrap.yml: no such file or directory
```
This happens because `build:api` (swagger) has to change the working directory (due to a bug in swagger). If the bootstrap stack is trying to deploy while the directory is different, it will fail.
The fix is to build swagger apis before starting the bootstrap goroutine
Closes: #492 
- Update v1 in documentation
- Build swagger before starting bootstrap goroutine
- Technically, `build:api` now happens twice, since `build:lambda` also calls it, but the second time no changes will need …
=> Fix swagger/build race, add v1 tags to docs

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/terraform/panther-deployment-role.tf, docs/gitbook/troubleshooting.md
We haven't updated the deployment role in awhile, and there are some new resources involved in deploy and teardown that we need to add permissions for.
- Add support for GuardDuty, CloudFormation stack sets, VPC flow logs, and IAM server certificates in the deployment role
- Troubleshooting documentation
- The error mentioned in the deploy process was actually fixed by #556 
- I mistyped an email in the deploy process, adding some clarification for how to remove the user from Cognito. They can re-add the user in Cognito, as originally suggested, but that won't add custom attributes (name), and in enterprise it won't work at all (they need a role). So it's easier to just people to redeploy in this case, it only takes about a minute now.
- Deploy and teardown using the deployment policy
=> Fix deployment role

deployments/cloud_security.yml, internal/compliance/remediation_aws/src/app/remediations/remediation_base.py
Remediation role ARN construction was not updated after changing to regionally suffixed roles.
- Change role generation to take suffix into account
- Deployed internally and observed remediations work
=> Fix remediation role construction

deployments/panther_config.yml, internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go, internal/log_analysis/rules_engine/src/engine.py, internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_rule.py, pkg/awsglue/partition.go, tools/config/config.go, tools/mage/deploy.go, tools/mage/deploy_onboard.go
While testing log alerting I encountered two issues: 
- If the rule was deleted before the alert was propagated, the alert-log-forwarder would keep retrying to fetch the rule .
- Rule's engine was not handling properly the case were a user had written an invalid dedup function. 
- Data Catalog updater was not updating rules matches properly
- Fixed above issues. 
- Improved logging in some cases
- Moved onboarding configuration for S3 Server Access logs to be in the same section as CT and GD onboarding since this seems more appropriate. It is not about "monitoring" of the app (in the sense that it monitors the app stability) it is more about log onboarding/auditing of accesses to panther resources&the account where panther is deployed. 
- Fixed data catalog updater
- Unit tests
- Deployed …
=> Fixing stability issues

docs/gitbook/policies/policies/README.md
The `pip` versions listed in the documentation do not match the config file
- Update `pip` versions of pre-installed libraries
- Explain that you can also bring your own pip libraries or lambda layers
=> Update policy library versions

README.md, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164_test.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424_test.go
While testing the new Fluentd parsers with real world data I found some issues. This PR is fixing them. 
- Fixing description of RFC5424
- According to the [documentation](https://docs.fluentd.org/parser/syslog#parameters), the only non-required field is `pri` field since it can be tuned on/off using  the parameter `with_priority`. In our tests we noticed that most of the logs were failing to parse because of this issue. Updated validations.
- Added extra unit tests
- Changing PID to be stored as integer instead of string. 
- Unit tests
- Deployed in my account processing real data. Verified data was flowing normally.
=> Fixing fluentd parsers

internal/core/users_api/api/list_users.go, internal/core/users_api/cognito/list_users.go
The `users-api` supports filtering users by name or email, though this functionality isn't yet exposed in the web app.
Adding URL-decoding to the search field in the backend (see: #576)
- URL-decode the "contains" filter in `users-api`
- Tiny optimization - trim and lowercase the search string once at the beginning instead of for each scanned user
- `mage fmt test:go deploy`
- `PKG=./internal/core/users_api/main mage test:integration`
=> URL-decoding for list users filter

.circleci/config.yml
Add `build:api` to CI (trying to reproduce #605 )
- Add `build:api` to CI (it used to be part of `test:go`, when we moved it out we didn't update CI)
- CI
=> Build swagger in CI

api/graphql/schema.graphql, deployments/appsync.yml, web/__generated__/schema.tsx, web/src/components/modals/DeletePolicyModal/graphql/deletePolicy.graphql, web/src/components/modals/DeleteRuleModal/DeleteRuleModal.tsx, web/src/components/modals/DeleteRuleModal/graphql/deleteRule.generated.ts, web/src/components/modals/DeleteRuleModal/graphql/deleteRule.graphql
Deleting a Rule in Log Analysis is using a deletePolicy query that is defined from DeletePolicyResolver in appsync right now. We need to split this to a separate resolver DeleteRuleResolver and a separate query for clarity and consistency.
Closes #464 
- Added `DeleteRuleResolver` in Appsync
- Added new graphql queries in web and schema
- Update `DeleteRuleModal` to use new query
- Locally
- Dev enviroment
=> Separated Delete Rule Query in schema & AppSync

tools/cfngen/cloudwatchcf/alarms_appsync.go, tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
Observed that some app sync queries (especially on a cold start) were taking longer than 1 second to respond under normal circumstances, but our alarms trigger when more than 5 queries hit 1 second latency in a short period. Increasing the latency required to trigger an alarm to 2 seconds.
- Bumped latency threshold for app sync alarms from 1 second to 2 seconds
- None
=> Updated latency threshold

README.md, deployments/bootstrap.yml, tools/mage/deploy.go, tools/mage/util_cfn.go
Cognito has an [advanced security mode](https://aws.amazon.com/blogs/security/how-to-use-new-advanced-security-features-for-amazon-cognito-user-pools/) which checks for compromised credentials. Advanced security also allows for adaptive authentication (require MFA only for high-risk logins), but we always require MFA for now, so we won't use that feature yet.
However, high-risk logins are at least logged to CloudWatch (which Panther should monitor!)
Related to https://github.com/panther-labs/panther/issues/606
- The Cognito user pool MFA is now configured in CloudFormation instead of manually via an API call. There's a weird string bug in CFN itself (which is presumably why we couldn't get CFN to work for this before), but I was able to work around it
- Enforce advanced cognito security - …
=> Enforce Cognito advanced security

tools/cfngen/cloudwatchcf/alarms_apigw.go, tools/cfngen/cloudwatchcf/alarms_appsync.go, tools/cfngen/cloudwatchcf/alarms_elb.go, tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
After some discussion as a team, we decided to remove the appsync latency alarm completely - API calls can take a few seconds on occasion for any number of reasons (cold starts, AWS service outages, etc). Users will notice exceptionally slow pages anyway
We should still graph the latency to understand opportunities for performance improvements, but there's no actionable response to a high latency alarm
By the same argument, API gateway and ELB do not need latency alarms. API gateway is used for internal services as well, but latency issues aren't generally actionable and don't really cause issues unless it causes other lambda functions to timeout, which we will see on those alarms instead
- Remove appsync, API gateway, and ELB latency alarms
- `mage build:cfn test:go`
=> Remove API latency alarms

deployments/bootstrap.yml, tools/mage/deploy.go
#633 tried to configure MFA for Cognito user pools in CloudFormation. It turns out that worked only on an *existing* deployment, fresh deployments from master fail with:
> SMS configuration and Auto verification for phone_number are required when MFA is required/optional
We *only* allow software token MFA, because SMS is not as secure. But CloudFormation literally cannot configure a user pool without SMS MFA (unless it already exists, apparently). I tried a couple workarounds (e.g. specifying dummy values for the SMS config block), but no luck - CFN forces real SMS MFA.
So we're forced to revert to what we were doing before - enable MFA on the user pool manually via the SDK
- Revert part of #633, adding more comments explaining why we have to do it that way
- Fresh deploy from master
=> Fix MFA for cognito user pools on fresh deployments

internal/log_analysis/log_processor/parsers/awslogs/alb.go, internal/log_analysis/log_processor/parsers/awslogs/alb_test.go, internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit.go, internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit_test.go, internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go, internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go, internal/log_analysis/log_processor/parsers/awslogs/extractor.go, internal/log_analysis/log_processor/parsers/awslogs/extractor_test.go, internal/log_analysis/log_processor/parsers/awslogs/guardduty_test.go, internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go, internal/log_analysis/log_processor/parsers/awslogs/s3_server_access_test.go, internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go, internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424_test.go, internal/log_analysis/log_processor/parsers/nginxlogs/access.go, internal/log_analysis/log_processor/parsers/nginxlogs/access_test.go, internal/log_analysis/log_processor/parsers/osquerylogs/differential.go, internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go, internal/log_analysis/log_processor/parsers/osseclogs/eventinfo.go, internal/log_analysis/log_processor/parsers/pantherlog.go, internal/log_analysis/log_processor/parsers/pantherlog_test.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164_test.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc5424.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc5424_test.go, internal/log_analysis/log_processor/parsers/zeeklogs/dns.go, internal/log_analysis/log_processor/parsers/zeeklogs/dns_test.go
Verifying that a field is a valid IP address before adding it to the "any" field. This helps avoid issues like adding a "domain" as an IP domain (seems to appear very often in our fields) and protect us from mistakes in the parser code in the future.
Using the `net.ParseIP` library from golang which seems to be pretty efficient (Olog(N))
- Added `AppendAnyIPAddressPtr` and `AppendAnyIPAddress` methods. These methods will attempt to add an IP address to the `any IP address` field. The method returns true if the value was an IP address, false otherwise. This feedback seems to be useful for some parts of the code. 
- Removed `AppendAnyIPAddresses` and `AppendAnyIPAddressesPtr`. I felt that having 4 methods for adding IP addresses might be an overkill.  This lead to some extra verbosity in …
=> Verifying IP addresses

README.md, internal/compliance/aws_event_processor/processor/process.go
The aws-event-processor cannot process events of the type `ConfirmDevice` from the cognito service because these events do not specify a userIdentity field with an account ID set, and we rely on this account ID for processing. Since this event type will never require a scan, I'm adding it to the ignore list.
- Add `ConfirmDevice` to the aws-event-processor ignore list
- None
=> Add ConfirmDevice to ignore list

deployments/auxiliary/cloudformation/osquery-firehose.yml
A template for an upcoming tutorial on sending logs to Panther via osquery!
New template to create:
* Osquery firehose
* IAM Roles
* S3 bucket for data
* Ec2 instance profile
We have been running an internal version of this template for a while, but I have adapted it for public use.
=> [deployments] aux template for sending osquery to Firehose

tools/mage/deploy_onboard.go
When upgrading Panther, the self onboarding step assumes that users have not changed the label for the self onboarded cloud security source. In at least one of our internal deployments, this is not the case. This assumption doesn't break anything, but it causes an error to be logged in the backend which sets off alarms and pages people. Updating this check to be more accurate to how the backend performs the same check.
- Update the checks performed to determine whether self onboarding is necessary
- Deployed in dev account, upgraded, observed error. Made changes, deployed, no error observed.
=> Change onboarding check

web/src/helpers/utils.tsx, web/src/pages/ListPolicies/ListPolicies.tsx, web/src/pages/ListResources/ListResources.tsx, web/src/pages/ListRules/ListRules.tsx
Initial problem from issue #576 : 
> Filtering Resources with quotes in the name returns all result
This PR addresses this issue by url encoding all free text fields for `names` and `ids`
Specifically: 
- Cloud Security -> Policies, Resources
- Log Analysis -> Rules
Related to #642
Closes #576
- Added new util functions for encoding parameters
- Encode parameters in `ListPolicies`, `ListRules` and `ListResources`
- Locally
=> Filtering based on "free" text field passed encode data to API 

internal/compliance/alert_processor/processor/processor.go
Do not error when getStatus returns a 404, just skip.
mage test:ci
=> Fix error handling for 404 in compliance alert processor

tools/mage/deploy_template.go
We need some sense of billing breakdown by component for Panther deployments, but manually tagging resources is fairly time consuming and not all resources support tagging.
It's much simpler to let CloudFormation automatically propagate tags to all supported resources, so for now we can just tag resources in each stack with that stack's name. That will identify Panther components as one of the following:
* `panther-bootstrap` - Critical common functionality like S3 buckets, networking, GraphQL API, KMS keys, etc. Most of the costs here will presumably be with the S3 buckets (all of which are defined in this stack)
* `panther-bootstrap-gateway` - API gateway
* `panther-cw-alarms`, `panther-cw-metric-filters`, `panther-cw-dashboards` - CloudWatch monitoring
* `panther-core` - shared …
=> Include CFN stack name as billing tag

go.mod, go.sum, tools/mage/build_namespace.go, tools/mage/deploy.go, tools/mage/fmt.go, tools/mage/fmt_license.go, tools/mage/setup.go
A few small fixes to setup/build/fmt which will help those commands run faster and avoid changes when building a fresh clone.
Closes: #691 
- Remove the https://github.com/fatih/color package - it is no longer maintained. We were only using it for one line of the deploy output; removing it clears several modules that users and CI no longer need to install.
- `mage setup` now pins the version of `goimports` and runs `go mod download` instead of `go get./...`. This will download exactly the modules in `go.mod`, preventing changes to that file during setup (#691). This is also faster than asking go to scan the whole repo looking for which modules to download.
- `mage fmt` now includes `go mod tidy` to cleanup `go.mod` and `go.sum` on every PR
- `mage build:api` adds license headers and …
=> Stabilize Go modules, format generated API files

.circleci/config.yml, tools/mage/build_namespace.go, tools/mage/setup.go, tools/mage/test_namespace.go
CircleCI currently spends 40 seconds installing python/go/npm/other dependencies on every build. But most of the time these dependencies don't change, so this is a waste of time and compute. Thankfully, CircleCI has native support for [dependency caching](https://circleci.com/docs/2.0/caching/) for exactly this reason!
- Cache each language's dependencies in CircleCI. Any changes to dependencies will rebuild just the dependencies for that language
- Simplify `build:tools` and build in parallel (saves 10-30 seconds in CI)
- Added `--no-audit` to npm install (saves a few seconds, we have a separate test for auditing)
- Dozens of CI builds
- Restoring from the cache usually saves ~20 seconds during the setup phase, though CircleCI cache performance seems to vary. We can always revert this if …
=> Cache dependencies in CI

internal/log_analysis/log_processor/common/common.go, internal/log_analysis/log_processor/main/lambda.go, internal/log_analysis/log_processor/processor/processor.go, internal/log_analysis/log_processor/sources/s3.go
Ran across some minor issues while working on a recent task
- Removed Lambda#SQSEvent dependency from S3 Source public API. No need to tie it to SQS specifically since events can come from any source. 
- Defining constant for event delimiter
=> Minor refactoring

docs/gitbook/enterprise/rbac.md
In Panther enterprise, changing a user's role / role permissions will not take effect until the next time the user logs in. This is because their [Cognito groups are encoded in a token sent to AppSync](https://docs.aws.amazon.com/appsync/latest/devguide/security.html#amazon-cognito-user-pools-authorization) and so persist for the duration of their session.
> When using Amazon Cognito User Pools, you can create groups that users belong to. This information is encoded in a JWT token that your application sends to AWS AppSync in an authorization header when sending GraphQL operations.
Add a note so enterprise users understand when permission changes will take effect
=> Add note about rbac permission changes

tools/mage/build_namespace.go, tools/mage/util.go
#696 started compiling Go binaries in parallel. While faster, this will completely consume all available compute resources, and @kostaspap started noticing his laptop struggling to do other things while building/testing.
This PR introduces a compromise - instead of launching a new goroutine for every unit of work, we launch a goroutine for each logical CPU (-1) and feed a stream of work units. In this model, you have to introduce a "poison pill" into the stream so the workers know when to stop.
- `mage build:lambda` and `mage build:tools` will only use `runtime.numCPU() - 1` concurrent goroutines
Since these commands themselves run in parallel in `mage test:ci`, it's still possible to be consuming all cores, but hopefully by reducing the parallelism of both commands the system can keep up …
=> Use worker model to limit max number of parallel go builds

docs/gitbook/enterprise/rbac.md, tools/mage/build_namespace.go
Output path for tools executable was deeply nested and confusing:
```
./out/bin/cmd/opstools/s3queue/s3queue/darwin/amd64/s3queue 
```
Now path starts with tool name: 
```
./out/bin/s3queue/darwin/amd64/s3queue
```
mage test:ci
mage build:tools
=> Fix output path for mage build:tools

deployments/web_server.yml, tools/mage/deploy.go, tools/mage/deploy_frontend.go
Setting expiration time for web server logs
- Added expiration time for web server logs
- Deployed in my account, verified CW Log group has expiration time.
=> Setting expiration time for panther-web-logs

cmd/opstools/requeue/integration_test.go, cmd/opstools/requeue/requeue.go, cmd/opstools/requeue/requeue/main.go
While running the `requeue` tool in my account I was in the wrong region. The error thrown was:
```
2020/04/18 13:25:28 cannot get source queue url for panther-input-data-notifications-queuelq
```
Updating the output to:
```
2020/04/18 13:26:14 cannot find source queue panther-input-data-notifications-queuelq in region eu-west-1:
```
I think the second error makes more clear to the operator that they might have mistyped the name of the queue or just be in the wrong region. 
- Minor output update
- Verified in my account by running the requeue tool.
=> Updating error output for requeue tool

docs/gitbook/SUMMARY.md, docs/gitbook/log-analysis/log-processing/supported-logs/Fluentd.md, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164_test.go, internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go, internal/log_analysis/log_processor/parsers/pantherlog.go, internal/log_analysis/log_processor/parsers/pantherlog_test.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164.go, internal/log_analysis/log_processor/parsers/sysloglogs/rfc5424.go
It's common for IPs to land in the authentication information generated from the SSH daemon and collected with syslog. We want to search this easily with the standardized data fields, so this change extracts them out.
```
Accepted publickey for ubuntu from 8.103.222.11 port 51454 ssh2: RSA SHA256:...
```
- Remove the validate:"required" tag on the FluentdSyslog.RFC3164 struct
- Pull out IPs from log messages using a regexp
- Enable IP extraction on all syslog log messages
- Update tests
- Unit testing
=> Tune Syslog, Pull IPs from Syslog Messages

README.md, deployments/bootstrap.yml, docs/gitbook/log-analysis/log-processing/supported-logs/GitLab.md
Fixes deployments in ap-southeast-1 as reported in https://github.com/panther-labs/panther/issues/747
- Fixed deployments in ap-southeast-1. 
- Updated audit bucket permissions to allow deployments in ap-northeast-3
- Deployed successfully to ap-southeast-1
=> Fix Audit bucket permissions

tools/athenaviews/athenaviews.go, tools/athenaviews/athenaviews_test.go
athenaviews.generateLogViews() creates SQL views over the Panther tables.
This is the entry point needed for Snowflake integration to generate these views so it needs to be a public function.
- athenaviews.generateLogViews() to athenaviews.GenerateLogViews()
mage test:ci
=> Make athenaviews.generateLogViews package public

api/graphql/schema.graphql, deployments/appsync.yml, internal/core/database_api/athena/driver/api/integration_test.go, web/__generated__/schema.tsx
The UI is not ready ready to use subscriptions to be notified on Athena query completion (but the backend has this implemented). 
This PR removes the GraphQL and CF configuration for the subscriptions but adds instructions in the athena_api integration tests for restoring this configuration. This will be used when we start adding support in the UI in the future.
- Removed queryDone subscription support in both the graph ql schema and appsync cloudformation
- Added a comment to the athena_api integration test explaining how to re-enable this capability.
mage test:ci
ran integration tests
=> Remove GrapQL and CF for athena query subscriptions (not yet used by UI)

docs/gitbook/development.md, docs/gitbook/quick-start.md, web/src/helpers/utils.tsx
This is the candidate commit for the 1.1.0 release! 
The link to documentation versions has been changed with a `-docs` suffix (e.g. https://docs.runpanther.io/v/v1.0.1-docs/). The reason is that gitbook automatically saves branches with the same name as the variant. When we had a `v1.0.1` variant, gitbook created a branch with that same name, which was confusing and actually broke deploys. Our documentation says to
```
git clone https://github.com/panther-labs/panther --depth 1 --branch v1.0.1
```
The `--branch` flag clones branches or tags with that name. Before, we just had a tag with that name, but now there was a branch as well! In that branch, `git describe --tags` does not work (there are no tags), which fails the deploy.
Removing the `v1.0.1` branch fixed the problem - we will now …
=> v1.1.0 release - fix doc link

deployments/bootstrap.yml, internal/core/database_api/athena/driver/api/integration_test.go
Remove AdditionalAuthenticationProviders from GraphQLApi in boostrap.yml, this was an oversight in previous PR taking out the config for AppSync subscriptions.
mage test:ci
mage deploy
=>  Remove AdditionalAuthenticationProviders from GraphQLApi in boostrap.yml

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/terraform/panther_deployment_role/main.tf, deployments/auxiliary/terraform/panther_deployment_role/variables.tf, go.mod, go.sum
#647 added Panther's first step functions, which means we need to update the deployment role
- Add `states:*` IAM permission to deployment role
- Fix a bug with `iam:ListServerCertificates` permission
- Permissions are now region-agnostic
- Update `go.mod` and `go.sum` with whatever was there after `mage clean setup`
- Deploy and teardown with the deployment role
=> Add state machine permission to deploy role

web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx, web/src/components/wizards/LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
The source onboarding wizards were sending the wrong account ID when requesting a template. This fixes so they send the correct account ID.
- Updated cloud security & log analysis source wizards to send the master account ID and not the satellite account ID when requesting a template
- Started the web server locally and verified it created the template correctly
- Going to test a full end to end source onboarding before merging
=> Fixed parameter

deployments/auxiliary/cloudformation/panther-cloudsec-iam.yml, internal/core/source_api/api/testdata/panther-cloudsec-iam-updated.yml
Fixed the template used to generate cloud sec sources.
- Correctly interpolated master account region
- Tested in a dev account by downloading the old template, making these changes to it, then uploading to cloudformation
Note: we'll need to publish this to the public s3 bucket for changes to take effect
=> Fixed template format

package.json, web/scripts/serve.js
We are missing security headers for the server serving the webapp. This is not a exploitable risk but it is consider a good practise to add them to prevent escalation of low severity issues.
Below you can find links that explain what some of them prevent or do: 
[X-XSS-Protection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)
[Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)
[Feature-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy)
[X-Content-Type-Options](https://stackoverflow.com/questions/18337630/what-is-x-content-type-options-nosniff)
[Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security)
[Content Security …
=> Added Security headers for server responses

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/terraform/panther_deployment_role/main.tf
The main functional change is adding some CloudTrail permissions so that the deployment role can succesfully deploy an account where `SelfOnboard` and `EnableCloudTrail` are both set equal to `true` in the `deployments/panther_config.yml` file. I also merged two permission blocks that I didn't actually understand why they were separate, but I can revert that change if need be.
- Added `cloudtrail:CreateTrail` and `cloudtrail:DescribeTrails` actions to the `Resource: *` permission
- Created a new permission that grants `cloudtrail:DeleteTrail`, `cloudtrail:StartLogging`, `cloudtrail:StopLogging`, and `cloudtrail:AddTags` on the CloudTrail that is created by Panther for self-onboarding
- Condensed two separate permissions that allowed various actions on `Resource: *` into one permission
- …
=> Update deployment role

docs/gitbook/quick-start.md
The current deploy docs do not specify that `mage setup` needs to be run before `mage test:ci`, even though they suggest users may run `mage test:ci` before deploying. This small update just clarifies that `mage setup` is a requirement for `mage test:ci`.
- Clarified some docs
- Viewed in markdown renderer of IDE
=> Clarify deployment docs

docs/gitbook/log-analysis/log-processing/supported-logs/GCP.md, docs/gitbook/operations/runbooks.md, tools/cfndoc/cfndoc.go, tools/cfndoc/cfndoc_test.go, tools/mage/teardown.go, tools/mage/util_cfn.go, tools/mage/util_hash.go
Teardowns often fail when trying to delete the audit logs bucket after any length of time (see #398), which then blocks the rest of the teardown.
This, combined with a few other small mage fixes, is the last set of mage bugs I'm aware of. After this, I won't be working on `mage` for awhile unless we need new features
Closes: #458 
- Generate operations documentation in a consistent order
- Enforce generated documentation in CI
- Set the S3 bucket ACL to "private" when deleting buckets to prevent new audit logs from arriving (closes: #398)
- Refactor stack set deletion to exit early if the stack instance is INOPERABLE (closes: #557 
)
- `teardown` succeeds with a large S3 audit bucket
- `teardown` in an empty region succeeds
- `teardown` in a region with an inoperable stack set:
``` …
```
=> Teardown fixes and consistent doc ordering

tools/cfngen/cloudwatchcf/alarms.go, tools/cfngen/cloudwatchcf/alarms_elb.go, tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
For SOC compliance we are required to have latency and 5XX alarms on the alb.
- Add support for p95 stats
- Add 5XX and latency alarms
mage test:ci
mage deploy
=> Add alb latency and 5XX alarms

internal/compliance/aws_event_processor/processor/process.go
See errors like "unable to get AWS region from CloudTrail event" for CreateResolver in aws event processor
- Whitelist CreateResolver  in aws event processor
- mage test:ci
- mage deploy
=> White list CreateResolver for aws event processor

internal/compliance/aws_event_processor/processor/ec2.go, internal/compliance/resources_api/handlers/add_resources.go
Updated the resources API to set a default timeout for resources of three days. This means that existing resources would have to get missed in 2-3 consecutive daily scans to accidentally be forgotten, but we won't have forgotten resources sitting around forever without any compliance status never being updated.
Additionally, corrected handling for the `DeleteVpc` event in the `aws-event-processor`.
- Updated the `resources-api` to set a three day expiration window for all resources by default
- Updated the `aws-event-processor` to appropriately handle `DeleteVpc` events (it was previously treating them as a regular resource update, not a resource deletion)
- Deployed to dev account, manually verified both changes
=> Resource Timeouts

internal/log_analysis/log_processor/processor/stream_test.go, pkg/testutils/awsmocks.go
Move log processor sqs mocks to pkg/testutils to allow sharing.
- Move log processor sqs mocks to pkg/testutils
- mage test:ci
=> Move log processor sqs mocks to pkg/testutils

tools/mage/deploy_template.go
When having more than one deployment, it easy to forget which is Enterprise and which is OpenSource.
This can also be useful for troubleshooting customer issues to definitively know the edition deployed.
* Add a "PantherEdition" tag.
* mage test:ci
* mage deploy
=> Add PantherEdition tag so it easy to tell apart Enterprise vs OpenSource

deployments/log_analysis.yml
Un-needed permissions were on some objects in  log_analysis.yml
* Remove un-needed permissions in log_analysis.yml
-  mage test:ci
-  mage deploy
=> Remove un-needed permissions in log_analysis.yml

web/src/components/forms/EditProfileForm/EditProfileForm.tsx, web/src/components/utils/AuthContext/AuthContext.tsx
For security reasons, we need to block updates on user's first and last name that include HTML fragments. This check is supported from `users-api` but from cognito which we are currently usign for user updates.
This PR addresses this issue by update the `EditProfileForm` to use `users-api`
Closes #817 
- Updated `EditProfileForm` to use `useEditUser` instead of cognito's `updateUserInfo`
- Locally
=> Updated EditProfile to use 'users-api' instead of Cognito

internal/compliance/aws_event_processor/processor/lambda.go
When processing the `PublishLayerVersion` event, the `aws-event-processor` would panic. This is because we erroneously assumed that a `functionName` field would be present in those events.
- Updated the `aws-event-processor` to explicitly handle all layer events appropriately
- Deployed to a dev account and observed before/after behavior
=> Proper handling of layer related events

pkg/awsathena/integration_test.go, pkg/awsathena/query.go
We discovered during release testing that athena views were not being deployed. Digging into the problem there were 2 issues:
1) the new gcp logs have a type declaration that Athena does not like, causing view creation to fail
2) an error path was not handled in the Athena query code, so deploys succeeded
See issue: https://github.com/panther-labs/panther/issues/834
This PR fixes the second issue.
There was a test for execution failures in this code, however, it was validating the wrong error path (failure in SQL planning). The proper test is to force a failure AFTER the planner. This was achieved by creating a table with a  non-existent bucket. The test was further updated to validate the error message from the check for execution failures to confirm the proper code path.
The Athena API …
=> Fix error handing in awsathena.WaitForResults

api/lambda/source/models/api.go, internal/compliance/snapshot_scheduler/scheduler/schedule.go, internal/compliance/snapshot_scheduler/scheduler/schedule_test.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/put_integration_test.go
Some recent refactoring of the `source-api` prevented the `snapshot-scheduler` from initiating the daily scans, as the `snapshot-scheduler` had previously been directly invoking a function defined in the `source-api` (a function that had previously existed in the now defunct `snapshot-api`). The recent updates to the `source-api` to instantiate all the clients in a `Setup` function broke this because the SQS client would no longer be defined.
- The `snapshot-scheduler` now communicates to the `source-api` via API call instead of just by importing it and running the code
- Deployed into my dev account
=> Fix scheduler bug

internal/core/custom_resources/resources/lambda_metric_filters.go, internal/core/custom_resources/resources/map.go
As I was getting ready to work on the next custom resource (alarms), I realized there's a slight problem with the way #872 implemented the custom resource ID.
I was putting the names of each metric filter in the resourceID, so we could extract them later for deletion/updates. However, that makes it hard to add new filters in the future:
1. We deploy the custom resource: `custom:metric-filters:log-group:memory/warns/errors`
2. Some time later, we want to add a new metric filter. We add some dummy parameter which forces CFN to re-evaluate the custom resources
3. CFN does an UPDATE, which now returns `custom:metric-filters:log-group:memory/warns/errors/newfilter`
4. Because the resource IDs are now different, CFN does a DESTROY on the old resource, which removes all filters except the one we …
=> Simplify metric filters

internal/core/custom_resources/resources/clients.go
I got a lot of the following exceptions at some point: 
```
09:49:01        ERROR   stack panther-log-analysis: Custom::LambdaMetricFilters RulesEngineMetricFilters CREATE_FAILED: Failed to create resource. failed to put panther-rules-engine-errors metric filter: ThrottlingException: Rate exceeded
status code: 400, request id: 151b519f-cee4-4f35-808b-eba0bcbfdc4f
09:49:01        ERROR       X panther-log-analysis failed (6/11): UPDATE_ROLLBACK_IN_PROGRESS
09:49:02        ERROR   stack panther-cloud-security: Custom::LambdaMetricFilters AlertForwarderMetricFilters CREATE_FAILED: Failed to create resource. failed to put panther-alert-forwarder-memory metric filter: ThrottlingException: Rate exceeded
status code: 400, request id: e965c34e-d430-4ccd-b28d-c513fb853509
09:49:02        ERROR …
```
=> Increase retries for custom resources

internal/log_analysis/alerts_api/api/get_alert.go
Fix error merging from Enterprise to OSS (caught when merging from OSS to Enterprise) in get_alerts.go
- mage test:ci
=> Fix typo in get_alerts from merge from enterprise

internal/core/source_api/api/put_integration.go, internal/core/source_api/api/utils.go
One of the latest refactoring was failing to populate "stackName" property for Scan integrations. 
- Populating Scan table property
- deployed and verified proper behavior
=> Fixing bug with stack name

internal/core/custom_resources/resources/alarms_elb.go
#887 added ELB alarms, but changed some default settings right before merging that broke fresh deploys.
Alarms can have either `Statistic` or `ExtendedStatistic`, but not both
- Remove `Statistic` from p95 alarm
- Fresh deploy + teardown
=> Remove extraneous statistic from ELB alarm group

.circleci/config.yml
NPM modules have a lot of sec vulnerabilities. The packages are vulnerable most of the times are the ones that we use for local development which **don't end up in production**.
This PR makes sure to only audit the packages that actually end up in production, so that the CI checks report fewer false positives.
- Run `npm audit` only on production dependencies 
- Related CI checks pass
=> enable auditing for prod deps only

deployments/bootstrap.yml, deployments/core.yml, tools/mage/deploy.go
Since the key-value store is designed to be accessed from user-defined Python, it would be very easy for DynamoDB costs to skyrocket. To prevent that, we're adding provisioned capacity with autoscaling.
This also adds a TTL column `expiresAt` so Python rules/policies can choose to expire items automatically if they want to.
- Add provisioned capacity to panther-kv-store
- Add autoscaling IAM role and targets
- Add TTL column to panther-kv-store
Deployed
Confirmed capacity settings are as expected:
=> Provisioned capacity and TTL for key-value store

internal/core/custom_resources/resources/alarms_appsync.go
The AppSync::Alarm custom resource is not being deleted when CloudFormation deletes the resource. This is because we were using the API id for the physical ID:
`custom:alarms:appsync:dp5ghc6zkfhkhgsu6qdiaqkwtm`
But we were using the API *name* for the alarm itself:
`Panther-AppSyncClientErrors-panther-graphql-api`
When the DELETE request was processed, the custom-resources Lambda function tried to delete the alarm named
`Panther-AppSyncClientErrors-dp5ghc6zkfhkhgsu6qdiaqkwtm`
The physical resource ID is how we know which alarm to delete - this succeeded because it's not an error to delete an alarm that doesn't exist, but the actual alarm remained after a teardown.
Closes: #918
We can either change the physical resource ID to use the API name or change the alarm name to use the API ID
The …
=> Use API ID (not name) for appsync alarms

deployments/bootstrap.yml, deployments/panther_config.yml, tools/config/config.go, tools/mage/deploy.go
This change adds support for deploying the `processed-data` bucket with data replication. Currently the data replication is for same account GLACIER storage class data replication. This is the use case we have for this feature internally and seems like the most common use case, but could be expanded to cross account or different status data replication in the future if needed.
I considered making more parameters configureable, such storage class or cross account or even a prefix list (if for example you only want to replicate some of the processed data), but I decided against over complicating the feature and polluting the config file and bootstrap stack parameters for a feature that will likely only be used lightly.
Question to reviewers: should we replicate the data in other buckets? I …
=> Added support for backing up processed data

internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
S3 Event notifications contain the S3 keys URL encoded. Trying to use URL encoded keys with the S3 client results to issues. 
- URL decoding S3 object key. 
- Unit test
- Ran in my account for few hours, verified it works fine.
=> Fixing issue with url-encoded S3 object keys

docs/gitbook/enterprise/snowflake.md
Panther Enterprise now uses a mage target to generate the snowpipe config file. Update docs to reflect that.
=> Update snowflake documentation to be consistent with changes this release

.gitignore
Mage can leave a temp file on the root path if it doesn't exit gracefully.
- Add the file to .gitignore to avoid pushing by mistake
=> Add mage temp file to .gitignore

deployments/master.yml
In #985 , the documentation link in the wev app doesn't work. I didn't notice this until now because I didn't push the docs branch until *after* finishing the release. We can either make a new tiny release or just bump the v1.4.0 tag forward with this change.
When deploying the pre-packaged template, the version passed to the web stack is '1.4.0' But that version is used for the docs link, which expects `v1.4.0`
- Prefix Panther version with 'v' when passing to web stack
- Deployed via master template, link works correctly
=> Prefix version in web app with 'v'

deployments/bootstrap_gateway.yml
One of our deployment upgrades failed because the custom-resources Lambda was missing a `glue` permission
=> Add glue:CreatePartition permission

internal/log_analysis/log_processor/destinations/s3_test.go, tools/mage/test_namespace.go
Small updates to the way we run go testing
- Now running go testing with `-race` flag for all codebase. We were skipping `-race` for one specific package due to performance issues - it seems to not be the case. `mage test:ci` for this PR takes around ~75seconds to complete on my laptop.  More or less the same as before. 
- Enabling the `-v` flag for `go test` command which became available with Go 1.14. For more info see here: https://golang.org/doc/go1.14#go-command 
-  `mage test:ci`
=> Small updates to go testing

tools/mage/test_namespace.go
Removing `-v` argument for `go test` operation.  Since we run multiple tests in parallel, if we stream test output, it is hard to identify the output of the failing tests
- Removed -v argument
- mage test:ci
=> Removing  -v argument

.prettierrc, package-lock.json, package.json, web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.tsx, web/src/components/forms/CompanyInformationForm/CompanyInformationForm.tsx, web/src/components/forms/ForgotPasswordForm/ForgotPasswordForm.tsx, web/src/components/forms/JiraDestinationForm/JiraDestination.tsx, web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.tsx, web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.tsx, web/src/components/forms/RuleForm/RuleForm.tsx, web/src/components/forms/SigninForm/SigninForm.tsx, web/src/components/forms/SlackDestinationForm/SlackDestinationForm.tsx, web/src/components/forms/SqsDestinationForm/SqsDestinationForm.tsx, web/src/components/wizards/S3LogSourceWizard/S3LogSourceWizard.tsx
Updated prettier version. Seeing speed improvements. 
- Version bump for prettier
- Seeing some changes in `*.tsx` files, apparently it is [expected](https://prettier.io/blog/2020/03/21/2.0.0.html#improved-method-chain-breaking-heuristic-6685httpsgithubcomprettierprettierpull6685-by-mmkalhttpsgithubcommmkal). 
- Prettier now runs much faster. `mage fmt` used to take ~17 seconds on average, now takes ~8 seconds
- `mage fmt`
=> Updated prettier version

api/lambda/outputs/models/api.go, internal/core/alert_delivery/delivery/outputs.go, internal/core/outputs_api/api/add_output.go, internal/core/outputs_api/api/add_output_test.go, internal/core/outputs_api/api/get_outputs.go, internal/core/outputs_api/api/get_outputs_unredacted.go, internal/core/outputs_api/api/update_output.go, internal/core/outputs_api/api/update_output_test.go, internal/core/outputs_api/api/utils.go, internal/core/outputs_api/table/update.go, internal/core/outputs_api/table/update_test.go, pkg/encryption/encrypt.go
Previously, configuration secrets such as API keys were displayed in plain text to users when viewing the destination configurations. This change both redacts those secrets before returning them to the frontend, and also allows the frontend to make partial updates to destinations.
Notes to the frontend team: All API calls that return an `AlertOutput` object should now have all secret fields redacted. I redacted them with asterisks `********` but if it would be easier to just return `nil` and have you guys put in a place holder on the frontend let me know. I also changed the signature for `UpdateOutput` API calls, the `displayName`, `defaultForSeverity` and `outputConfig` fields are now optional. Feel free to still send them if you want, but at least for `outputConfig` you need to not send …
=> Redact destination secrets

internal/log_analysis/log_processor/sources/s3_client_cache.go
When processing an s3 object stscreds.NewCredentials() was called each time.
Now  stscreds.NewCredentials() is called only when needed.
- mage deploy, checked for any errors (were none)
=> Improve log processor assume role usage

web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx, web/src/constants.ts
There was a hardcoded URL pointing to the old doc URL located on `StackDeployment` page. In this PR, I changed that to use generated doc URL as prefix.
Broken link now redirects correctly [here](https://docs.runpanther.io/v/v1.4.0-docs/log-processing#sns-notification-setup).
Also, did a check for any other stray doc URL and didn't find any. 
Closes #1026  
- Created a specific section in `constants` file for doc URLs, including the missing doc URL described on #1026 
- Locally
=> Fixed hardcoded doc url in StackDeployment

deployments/cloud_security.yml, deployments/core.yml, deployments/master.yml, internal/core/outputs_api/main/integration_test.go, tools/mage/deploy.go, tools/mage/test_namespace.go
#1033 broke the `outputs-api` integration tests
- Fix `outputs-api` integration tests
- Change `mage test:integration` so that errors are not blocking
It takes several minutes to run all integration tests, a failure halfway through is frustrating because `mage` will stop immediately and you'll have no way to know if the remaining tests would have passed.
Now, all errors are logged so you can address all integration test failures at once
- `mage test:integration` 3 times plus `PKG=./internal/core/outputs_api/main mage test:integration` a few times
=> Fix outputs-api integration tests

deployments/cloud_security.yml, deployments/log_analysis.yml
Give the policy and rules engines permissions to communicate to AWS secrets manager.
I gave the two engines access to different 'paths' in secrets manager, because we separate permissions for policy/rule writing so technically one could have a secret that the other shouldn't have access to. But generally any rule can access any secret put in by any other rule.
They also have a shared path for shared secrets.
We're considering adding something to the `panther_analysis_tool` to assist in uploading these secrets, so you can securely store the initial secret. But currently you'll have to load the secret in from the AWS console.
- Updated permissions of policy/rules engines
- Doing a deployment to dev account currently to test this
=> Secrets manager permissions

deployments/web_server.yml, internal/core/custom_resources/resources/alarms_elb.go
~Configuration ALB alarms to trigger only if we see persistent issues. AWS can occasionally encounter some "glitches", with this update we make sure we trigger an alarm only if the issues persist.~
After some consideration, thinking the best way to move forward is to get rid of the 4XX alarms. 
Some reasons why I think this is the best way of action: 
1. There is a very high chance for a false positive due to "expected" user activity. 
2. If the increased 4XX is due to some of our Lambdas experiencing issues, we will identify such issues from Lambda alarms.
3. Elevated 4XX might be a sign of a security issue. We should rely on Panther log (ALB) processing for this instead of CW Alarms. 
* `mage test:ci`
* Deployed
=> Removing 4XX alarms for ALB

deployments/appsync.yml, deployments/bootstrap_gateway.yml, deployments/cloud_security.yml, deployments/core.yml, deployments/log_analysis.yml, deployments/master.yml, deployments/onboard.yml, deployments/web_server.yml, docs/gitbook/development.md, tools/mage/deploy.go, tools/mage/deploy_frontend.go, tools/mage/master_namespace.go
Like all CloudFormation resources, custom resources are not updated until their input parameters change.
This is not necessarily intuitive - for example #1049 tried to update an alarm group by changing the Go code in the custom resources Lambda function. That will work for new deployments, but will not be applied to existing deployments. Similarly, @rleighton is working on correcting the Python metric filters.
In both cases, the input parameters must change in some way to update existing deployments. To that end, this PR introduces a "CustomResourceVersion" parameter to most stacks which isn't used for anything except triggering custom resource updates.
For pre-packaged deployments, this will be the Panther release version, which will guarantee bug fixes like #1049 are applied. For `mage …
=> Add CustomResourceVersion

deployments/bootstrap.yml, deployments/master.yml, deployments/onboard.yml, tools/mage/deploy.go
VPC flow logs moved from the bootstrap stack to the onboard stack when preparing the pre-packaged deployment because of a SAR compatibility issue. Our hosted deployments generally do not enable self-onboarding, meaning the entire onboard stack, including VPC flow logs, does not exist in those environments.
VPC flow logs are similar to S3 access logs - they are enabled on each resource, not account-wide like CloudTrail/GuardDuty. Like S3 access logs, VPC flow logs should always be enabled if possible, even if they aren't being ingested by the Panther deployment in the same account.
- Move FlowLogs resource from onboard into bootstrap stack (SAR compatibility is no longer a concern)
The configuration can't just be copied exactly without a migration:
```
11:43:31	INFO	deploy: update …
```
=> Move VPC flow logs to bootstrap stack

docs/gitbook/SUMMARY.md, docs/gitbook/log-analysis/log-processing/log-setup/gsuite.md
Adding instructions on how to create GSuite application that Panther can use to pull logs
The UI will point to this documentation as part of the GSuite logs onboarding. Feedback/recommendation about the text the structured are more than welcomed!
=> Add GSuite application instructions

deployments/log_analysis.yml
Fixes https://github.com/panther-labs/panther/issues/961
- Reducing retries for log processor messages to 4. If that threshold is breached, the message will move to the DLQ. 
Given that the visibility timeout is 15', this means we will retry for 1hr until giving up. When giving up, the message will go to the DLQ. 
An "absolutely correct" number of retries is hard to hit. Too few and people will have to be paged/notified for the slightest issue, too high can lead to "pointless" retrying. 
I think retrying for 1hr is reasonable for our scenarios, but we can always adjust in the future. 
- Mage test:ci
=> Reducing retries for log processor messages

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/terraform/panther_deployment_role/main.tf, deployments/bootstrap.yml, deployments/bootstrap_gateway.yml, deployments/master.yml, docs/gitbook/quick-start.md, internal/core/organization_api/api/get_settings.go, internal/core/organization_api/api/update_settings.go, internal/core/organization_api/table/get.go, internal/core/organization_api/table/get_test.go, internal/core/organization_api/table/table.go, internal/core/organization_api/table/update.go, internal/core/organization_api/table/update_test.go, tools/mage/deploy.go, tools/mage/teardown.go
This will be the v1.5.0 release tag once merged
- Add `s3:ListAllMyBuckets` permission to the deployment role - this is required for `mage teardown`
- Bump version in docs and master template to v1.5.0
- Backport some restructuring from https://github.com/panther-labs/panther-enterprise/pull/264 for easier merging
- Full release testing ongoing
- Paid special attention to new alerts page, adding multiple globals, reset password, and upgrading a deployment with the pre-packaged template
=> v1.5.0 Release

api/lambda/source/models/api.go, api/lambda/source/models/integration.go, internal/core/source_api/api/delete_integration.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/update_status.go, internal/core/source_api/api/utils.go, internal/core/source_api/ddb/get_item.go, internal/core/source_api/ddb/items.go, internal/core/source_api/ddb/scan.go, internal/core/source_api/ddb/update.go, internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go, internal/log_analysis/log_processor/sources/s3_test.go
Current `Sources` page contains little information the current status of a source. 
While we are looking to provide more rich monitoring around a source status, adding a small piece of information as a stop-gap solution. 
With this solution, the log processor updates the "status" of the source with the timestamp of the most recently received event. The status will have 1 minute accuracy. 
- Added new API method "UpdateStatus" to the panther-source-api Lambda.
- Updated log processor to invoke the source-api
- Shortening `ddb.IntegrationItem` to just `ddb.Integration`. The namespace `ddb` adds context that this is a resource related to DynamoDB. 
- Added "omitempty" to several fields returned by the UI. While we do this for most of our other APIs, it seemed we were not following this …
=> Log processor update source status with the time it received the last event

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/terraform/panther_deployment_role/main.tf
When testing panther-enterprise v1.5.0, I found the deployment role was missing `firehose:*` permissions for the event bridge delivery stream.
We added that permission in the enterprise repo, but not here in the community edition. We only have one deployment role template, and the one that we had published to S3 does not work for enterprise.
- Add `firehose:*` permission for `panther-*` delivery streams to the deployment role
- Enterprise deployment with this role
- Copied template from community into enterprise to ensure there were no other differences
I'm not going to move the v1.5.0 git tag, but I did overwrite the v1.5.0 S3 template in the public bucket.
=> Add firehose permissions to deployment role

deployments/bootstrap_gateway.yml, internal/core/custom_resources/resources/guardduty_destination.go
When trying to upgrade one of our deployments to v1.5.0, I encountered this error:
> stack panther-onboard: Custom::GuardDutyDestination GuardDutyDestination UPDATE_FAILED: Failed to update resource. BadRequestException: The request failed because a publishingDestination already exists with the destinationType value provided in the request.
Here's what happened:
1. Because we added the `CustomResourceVersion` to most custom resources, CloudFormation triggered an update to the `Custom::GuardDutyDestination` resource, as intended
2. Our implementation of the custom resource used the same code path for both create and update, which leads to the error you see above
3. GuardDuty is disabled by default, so my release testing didn't catch it when I did an upgrade
- Implement GuardDuty …
=> Support updates to Custom::GuardDutyDestination resource

internal/log_analysis/log_processor/classification/classifier.go, internal/log_analysis/log_processor/classification/classifier_test.go, internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go, internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go, internal/log_analysis/log_processor/parsers/juniperlogs/access.go, internal/log_analysis/log_processor/parsers/testutil/testutil.go
Changed classifier so that it considers a parser invocation failed only if parser returned an error. 
If a parser returns no error and empty result, we consider the parsing successful (parser matched the event), just there was no output event. This can happen in case of e.g. CSV files when processing header lines. 
- Modified classifier to treat empty result as an acceptable result. 
- After chat with @alxarch  Changed parsers to return `nil, nil` in cases where a log line is matched but no event is returned. Ι basically searched the parser package, it seems that the only parsers that had to deal with such a scenario where the VPC FL parsers and Juniper Access logs. 
- unit tests
- Deployed and verified in my account (before this change we were getting warnings for VPC FL files)
=> Fixing classifier behavior

api/lambda/source/models/integration.go, internal/compliance/snapshot_scheduler/scheduler/schedule.go, internal/compliance/snapshot_scheduler/scheduler/schedule_test.go, internal/core/source_api/api/list_integrations_test.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/update_status.go, internal/core/source_api/ddb/items.go
Changing API for sources-api to return null when a timestamp is not configured. Current API was returning `0001-01-01T00:00:00Z` when a timestamp was not configured (this is zero time for Golang's `time.Time`). 
However the above default value doesn't make sense for other languages, it is Go specific. 
Given that the APIs are also used by the frontend, it makes sense that optional `time.Time` fields are defined as pointers, so that they are omitted when they are serialized. 
- Changed optional time fields from source-api to be `*time.Time`
- Deployed and verified behavior.
=> Changing API for sources-api to return null when a timestamp is not configured

api/graphql/schema.graphql, web/__generated__/schema.tsx, web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.graphql, web/src/pages/ListLogSources/LogSourceTable/LogSourceTable.tsx
We want to show to users when was the latest event received for each integration. The purpose of that is to primarily understand if an integration is active (or recently active) and not just "healthy". The backend functionality for this is implemented on #1054. This PR introduces the changes needed to display that field in UI.
Note: Ignore backend changes on this PR, they should be handle on #1054 
Closes #1055 
- Added `lastEventReceived` field to `S3LogIntegration`
- Updated `LogSourceTable` to display field
- Locally
- Deployed env
=> Log Source Table to display "lastEventReceived" for each source

deployments/bootstrap_gateway.yml, deployments/core.yml, internal/core/custom_resources/resources/alarms_elb.go, internal/core/users_api/api/cognito_trigger.go, internal/core/users_api/main/lambda.go
Backporting some bug fixes and refactoring from https://github.com/panther-labs/panther-enterprise/pull/305
- acm:ImportCertificate apparently requires '*' as the IAM resource permission when importing from a file - the custom-resources Lambda was logging a "not authorized" warning and falling back to IAM
- the elb alarm removal intended as a migration triggers on every create as well as every update, which meant that a fresh deployment was logging a warning trying to delete an "invalid physical ID". Fixed to only run on updates
- Removed unnecessary IAM permissions from `users-api` and consolidated IAM permissions for `custom-resources`
- Slightly restructured Cognito trigger handling to match enterprise code
=> Custom resource and IAM bug fixes

api/lambda/users/models/api.go, api/lambda/users/models/validator_test.go, deployments/appsync.yml, deployments/core.yml, internal/core/custom_resources/resources/panther_user.go, internal/core/users_api/api/api.go, internal/core/users_api/api/invite_user.go, internal/core/users_api/api/invite_user_test.go, internal/core/users_api/api/list_users_test.go, internal/core/users_api/api/remove_user.go, internal/core/users_api/api/remove_user_test.go, internal/core/users_api/api/reset_user_password.go, internal/core/users_api/api/reset_user_password_test.go, internal/core/users_api/api/update_user.go, internal/core/users_api/api/update_user_test.go, internal/core/users_api/cognito/delete_user.go, internal/core/users_api/cognito/delete_user_test.go, internal/core/users_api/cognito/list_users.go, internal/core/users_api/cognito/list_users_test.go, internal/core/users_api/cognito/mock_cognito_client.go, internal/core/users_api/cognito/mock_gateway.go, internal/core/users_api/cognito/users_gateway.go, internal/core/users_api/main/integration_test.go
When a Panther user is deleted, we remove them from the Cognito pool immediately, but their access token is still valid for up to 1 hour. That is a common limitation in many auth systems, Cognito included - we don't have any way to invalidate that token nor is the expiration configurable.
But we can take some steps to limit the damage a deleted account can do. In particular, today it is possible for a deleted account to continue to create new user accounts every hour to maintain indefinite access to the system. To prevent that, all user management write operations now require proof of the requester identity, which is validated against the Cognito pool.
We will address this more fundamentally in the next quarter with some kind of unified API where a single point of entry can handle extra …
=> Prevent persistence after user deletion

internal/core/analysis_api/handlers/bulk_upload.go, internal/core/analysis_api/handlers/create_global.go, internal/core/analysis_api/handlers/delete_global.go, internal/core/analysis_api/handlers/modify_global.go, internal/core/analysis_api/handlers/sqs.go
When we added support for multiple globals we moved the `rebuild global layer` API call out of the `WriteItem` helper that all the analysis-api endpoints rely on to write to dynamo and into the API endpoints directly. But we forgot to do this for the `ModifyGlobal` endpoint. This meant that the global layer was only rebuilt when new globals were created, globals were deleted, or a global was uploaded via the bulk upload endpoint. Modifying a single global (e.g. via the web UI) did not actually rebuild the global layer. This fixes that.
- Rebuild the global layer after a global is modified via the web UI
- Deploying into dev account now to verify
=> Rebuild global layer when modified from web UI

api/gateway/analysis/api.yml, api/gateway/analysis/engine.go, api/gateway/analysis/models/unit_test_swagger.go, api/graphql/schema.graphql, internal/core/analysis_api/handlers/bulk_upload.go, internal/core/analysis_api/handlers/test_policy.go, internal/core/analysis_api/handlers/util.go, internal/core/analysis_api/main/integration_test.go, internal/core/analysis_api/main/lambda.go, web/__generated__/schema.tsx, web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx, web/src/components/forms/PolicyForm/PolicyForm.tsx, web/src/components/forms/RuleForm/RuleForm.tsx, web/src/graphql/fragments/PolicyDetailsExtra.generated.ts, web/src/graphql/fragments/PolicyDetailsExtra.graphql, web/src/graphql/fragments/RuleFull.generated.ts, web/src/graphql/fragments/RuleFull.graphql, web/src/pages/EditPolicy/graphql/updatePolicy.generated.ts, web/src/pages/EditPolicy/graphql/updatePolicy.graphql, web/src/pages/EditRule/graphql/ruleDetails.generated.ts, web/src/pages/EditRule/graphql/ruleDetails.graphql
The Resource Type (and Log Type) field in Policy/Rule unit tests are not needed and don't offer any extra feature
to the user. See #610 for more context.
These fields are removed both from the web and backend/api code.
With `mage test:integration` and manually.
@3nvi the frontend change (cleaning up the fields) seemed trivial and went ahead and implemented it in the 3rd commit but I can split it to a different issue/PR if you wish.
=> Remove policy test resourcetype fields

web/src/components/Navigation/NavLink.tsx, web/src/helpers/utils.tsx
Navlink component's active URL checking does not actually work with URLs without a trailing slash, this PR fixes this minor bug.
- Introduced a minimaL helper utility for URL checking
- Patched the `web/src/components/Navigation/NavLink.tsx` component.
- Manually and visually.
=> Fix Navlink active URL checking

package-lock.json, package.json
Safari versions prior to [13.0.1](https://caniuse.com/#feat=resizeobserver) do not support the Resize Observer API, thus the app is crashing due to `pouncejs` misconfiguration of the polyfill. This issue is related to this [pounce pull request](https://github.com/panther-labs/pounce/pull/78) and we shall bump a new `pounce` release before merging. Also, there is a pending commit missing updating the `package-lock.json` file.
- Bump the `pouncejs` dependency on the latest one.
- Checkout the branch and run `npm I && npm run start` when the server fires up navigate to the app using Safari.
=> Update pouncejs to ^0.45.1

pkg/lambdalogger/logger.go
The `lambdalogger` package loaded by all of our Lambda functions has a hack to work around a go-swagger limitation. Thankfully, swagger has since fixed this issue, so we can remove this code. This frees up lambda functions to inspect the `DEBUG` environment variable without having to worry about silent modifications to it from another package.
- Deployed, integration tests
=> Remove debug env hack

web/src/apollo/cleanParamsLink.ts, web/src/apollo/createErrorLink.ts, web/src/components/modals/ResetUserPasswordModal/ResetUserPasswordModal.tsx, web/src/components/sidesheets/PolicyBulkUploadSidesheet/PolicyBulkUploadSidesheet.tsx, web/src/hooks/usePolicySuppression.tsx, web/src/hooks/useResourceRemediation.tsx
**This is  pre-cursor to the  test suite  setup**
This PR changes  the imports of some common Apollo functions, from `@apollo/client/utilities/graphql/getFromAST` to `apollo-utilities`.  The `apollo-utilities` package is already  present and is a dependency of almost all of our apollo OSS packages. 
The reason behind this change  is  that the former doesn't have commonJS exports, while the latter does. This will helps us during testing,  since Jest won't be forced to transpile any ES6 or TS  to commonJS in `node_modules` packages. 
- Change  import of utility functions from deep non-transpiled paths to separate  commonJS utility package
- App works as expected
- Utility funcs have the  same  code
=> Refactor: stabilize module imports

docs/gitbook/SUMMARY.md, docs/gitbook/operations/advanced-setup/configuring-custom-domains.md, docs/gitbook/operations/configuring-custom-domains.md
It appears when I wrote the custom certificate docs I never correctly updated the summary page to link to them, so they were inaccessible unless you knew the link off hand. This fixes that summary page, and additionally updates the custom certificate documentation with some details about pre-packaged deployments.
- Add the `configuring-custom-domains` page to the `SUMMARY.md` file
- Updated the documentation on configuring a custom domain to include references to pre-packaged deployments
- Viewed in markdown renderer in IDE
=> Fix up custom certificate documentation

web/src/components/modals/DeleteComplianceSourceModal/DeleteComplianceSourceModal.tsx, web/src/components/modals/DeleteDestinationModal/DeleteDestinationModal.tsx, web/src/components/modals/DeleteGlobalPythonModuleModal/DeleteGlobalPythonModuleModal.tsx, web/src/components/modals/DeleteLogSourceModal/DeleteLogSourceModal.tsx, web/src/components/modals/DeletePolicyModal/DeletePolicyModal.tsx, web/src/components/modals/DeleteRuleModal/DeleteRuleModal.tsx, web/src/components/modals/DeleteUserModal/DeleteUserModal.tsx
With the latest apollo upgrade, we can substitute `cache.modify` code for deletions with one liners `cache.evict`. This will provide clarity as well with getting us up to date with the latest version. Users shouldn't notice any difference. 
- Replace cache.modify in `DeleteComplianceSourceModal`, `DeleteDestinationModal`, `DeleteGlobalPythonModuleModal`, `DeleteLogSourceModal`, `DeletePolicyModal`, `DeleteRuleModal`, `DeleteUserModal`
- Verified cached object are removed both from apollo cache and from the UI.
=> Replaced cache.modify with cache.evict for deletions 

requirements.txt, tools/mage/setup.go
The snowflake driver needs the latest cfn-lint specs.
- Bump cnf-lint version
- Add code to `mage setup` that updates the cfn lint specs
- mage clean setup test:ci
=> upgrade cfn-lint and ensure specs are current

deployments/bootstrap.yml, deployments/master.yml, deployments/panther_config.yml, tools/config/config.go, tools/mage/deploy.go
The ALB security group which allows HTTP(S) access to the web app (ALB) is currently 0.0.0.0/0
Not everyone wants an open security group like this, we need to provide a configuration option for the ingress cidr block.
- Add `LoadBalancerSecurityGroupCidr` parameter to `bootstrap` and `master` stacks
- `STACK=bootstrap mage deploy`
=> Configurable ALB ingress security group

web/src/components/charts/BarChart/BarChart.tsx
`echarts` is a **huge** library. Due to that up until recently we had it code-splitted. Somehow, this got removed and ended up being bundled in our main bundle.
This PR makes sure  it's code-split again
- Code-split `echarts`
See the data below. The reduction is `300KB` big (only see Gzipped sizes0.
=> Feat: Lazy-load charting library

api/gateway/analysis/api.yml, api/gateway/analysis/models/rule.go, api/gateway/analysis/models/threshold.go, api/gateway/analysis/models/update_rule.go, internal/core/analysis_api/handlers/create_rule.go, internal/core/analysis_api/handlers/dynamo.go, internal/core/analysis_api/handlers/modify_rule.go, internal/core/analysis_api/main/integration_test.go, internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go, internal/log_analysis/alert_forwarder/forwarder/rule_cache.go, internal/log_analysis/alert_forwarder/main/config.go, internal/log_analysis/alert_forwarder/main/lambda.go
Closes #1110 
Added support for rule threshold. 
Now every Rule has a "threshold" field. If we see more than N matched events for a rule within a deduplication window, we create a new alert. If the number of matched events is below the threshold, no new alert will be created (however, we will store the matched events in S3/Athena)
- Added new field in rule
- Added logic to ignore events if we haven't reached a threshold
- Made some improvements in the `alert_forwarder` package. Avoiding global variables allows us now to run all unit tests for forwarder in parallel
- Unit tests
- Integration tests
- Deployed and verified behavior
=> Support rule threshold

web/__tests__/__mocks__/builders.generated.ts, web/codegen/buildGraphqlResourcesPlugin.js, web/codegen/buildGraphqlResourcesPlugin.ts
Currently, the way `...overrides` is written in test builders, allows for endless circular dependencies. Specifically:
```ts
const buildUser = overrides => {
id: '123',
role: buildRole(),
// ... more stuff
...overrides
}
const buildRole = overrides => {
id: '345',
users: [buildUser()],
// ... more stuff
...overrides
}
```
This way, even if you tried to write `buildUser({ role: null })` , you wouldn't escape the `    RangeError: Maximum call stack size exceeded` issue.
This PR fixes that by inlining `overrides` like so:
```ts
role: overrides.role ? role : buildRole(),
```
and doesn't depend on the
```ts
...overrides
```
spread anymore
=> fix: overriding technique on FE test builders

.circleci/config.yml
Follow up to #1221 to see if we can run `fossa test` in CI more quickly now that the project has been bootstrapped.
EDIT: Indeed, we can! Now each PR will show a failing check if the license scan fails. If this continues to work well, we can make it a required check sometime in the future
=> Add FOSSA test to CI

internal/core/analysis_api/analysis/policy_engine.go, internal/core/analysis_api/analysis/rule_engine.go, internal/core/analysis_api/handlers/create_policy.go, internal/core/analysis_api/handlers/create_rule.go, internal/core/analysis_api/handlers/modify_policy.go, internal/core/analysis_api/handlers/modify_rule.go, internal/core/analysis_api/handlers/test_policy.go, internal/core/analysis_api/main/integration_test.go
When a rule/policy unit test contains invalid json as the event/resource input, an http 500 was returned and user wouldn't
know what the problem would be as the UI redirects to a generic page for server errors.
This PR returns a user friendly message along with an http 400 (bad request) status code.
Added integration tests
**UI screenshot**
Clicking Run All
Clicking Save
=> Return http 400 and user friendly message when rule/policy test input is invalid json

go.mod, go.sum, internal/log_analysis/log_processor/pantherlog/omitempty/omitempty.go, internal/log_analysis/log_processor/pantherlog/omitempty/omitempty_test.go
The current log parsers require adding `omitempty` to all fields. Forgetting to set omitempty could result in `null` values being written on output JSON. We do not like that. This PR adds a `jsoniter.Extension` that forces `omitempty` behavior on all struct fields.  
- Adds a `jsoniter.Extension` to force omitempty.
- mage test:ci
=> Add jsoniter extension to force `omitempty` on all fields

docs/gitbook/development.md, tools/mage/test_namespace.go
One of the backend engineers asked for separate `mage test` commands for Go code, so that he could iterate more quickly, I believe it was @alxarch 
- Add `test:go`, `test:python`, `test:cfn`, and `test:web` commands - these run a subset of `test:ci` which apply only to the specific languages (no formatting)
- Allow the go linter to use multiple threads - it was the slowest task and would finish 30 seconds or more after every other task, it's better to let it run (by itself) with full parallelism rather than run it with only 1 process
- Ran each `test` command independently
=> Add separate mage test commands

docs/gitbook/SUMMARY.md
The Box setup docs where missing from gitbook
- Adds link to Box setup docs to SUMMARY.md
=> Update SUMMARY.md to include Box setup docs

deployments/appsync.yml
Cognito actually has 2 different user kinds of user IDs: a *username* and a *sub*:
From [the AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-identity), the `identity` context contains both:
> sub: The UUID of the authenticated user.
> username: The user name of the authenticated user. In the case of AMAZON_COGNITO_USER_POOLS authorization, the value of username is the value of attribute cognito:username.
For all users so far, these values have been the same:
However, with the addition of SAML users in Panther Enterprise, the username looks like `PantherSSO_email@example.com` while the `sub` is still a UUID. Currently, AppSync is sending the *sub* but all of the [AWS …
=> Send Cognito username from AppSync instead of sub

docs/gitbook/SUMMARY.md, docs/gitbook/log-analysis/log-processing/log-setup/box.md, docs/gitbook/log-analysis/log-processing/log-setup/okta.md, docs/gitbook/log-analysis/log-processing/log-setup/onelogin.md
Closes #1084 
Added documentation on onboarding Okta and OneLogin logs. 
=> Added Okta & OneLogin documentation

tools/mage/deploy.go, tools/mage/master_namespace.go
I went to publish the release: `mage master:publish`, and got a nil pointer panic.
Turns out that's because `master:publish` runs the same pre-checks as a standard `deploy`, which includes checking for old stack versions that may need special migrations. That stack check was failing because there was no aws session initialized.
We don't need that check when publishing the release, so I just made it optional
- add parameter to `deployPreCheck()` to control whether the old version check runs
- `mage master:publish`
=> Fix mage master:publish

docs/gitbook/quick-start.md
World's smallest PR - adding a single missing "/" to the quick-start documentation.
=> Missing a slash in the quick-start docs

pkg/README.md, pkg/prompt/prompt.go, tools/mage/deploy.go, tools/mage/glue_namespace.go, tools/mage/master_namespace.go, tools/mage/teardown.go, tools/mage/test_namespace.go, tools/mage/util.go
I will be moving `mage gluesync` into an ops tool so it can be more easily shared with customers.
This change factors our the user prompt code in `mage` as a package in `pkg`
- Factor out prompt code
- Bring README.md current
- mage test:ci
=> Factor user prompt code from mage to pkg/prompt

docs/gitbook/README.md
removed note about premium detections, as they are now all open sources
In Panther v1.6, we open sourced all our detections. This change to the docs removes the note indicating that there were premium detections in enterprise. 
removed from "Premium" the note that Enterprise includes more detections. 
n/a
=> removed premium detection packs

api/graphql/schema.graphql, api/lambda/source/models/integration.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/put_integration_test.go, internal/core/source_api/api/sqs_utils.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/utils.go, internal/core/source_api/ddb/items.go, pkg/awssqs/permissions.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/components/wizards/SqsSourceWizard/SqsSourceConfigurationPanel/SqsSourceConfigurationPanel.tsx, web/src/components/wizards/SqsSourceWizard/SqsSourceWizard.tsx, web/src/graphql/fragments/SqsLogSourceIntegrationDetails.generated.ts, web/src/graphql/fragments/SqsLogSourceIntegrationDetails.graphql, web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.tsx, web/src/pages/CreateLogSource/CreateSqsLogSource/__tests__/CreateSqsLogSource.test.tsx, web/src/pages/EditSqsLogSource/EditSqsLogSource.tsx
When a user goes through the new SQS source onboarding, Panther will create a new SQS queue for them to send their data to. 
During the onboarding process (and later on during editing of the source) the users can choose which Principal ARNs (IAM roles, users) and which Source ARNS (S3 buckets, SNS Topics) will be allowed to send messages to the SQS queue. 
The user could choose to specify no Principal and source arns - in that case only the principals inside the Panther AWS account could send data to the queue. Current backend code had a bug would result in an error
- Renamed `allowedPrincipals` to `allowedPrincipalArns` property to be aligned with `allowedSourceArns` property naming. 
- Fixed bug mentioned above
- mage test:ci
- deployed in my account. 
- Created a new SQS source with no …
=> Fix bug when no permissions where specified for the SQS queue

internal/log_analysis/log_processor/classification/classifier_test.go, internal/log_analysis/log_processor/pantherlog/jsoniter.go, internal/log_analysis/log_processor/pantherlog/jsoniter_test.go, internal/log_analysis/log_processor/pantherlog/meta.go, internal/log_analysis/log_processor/pantherlog/meta_test.go, internal/log_analysis/log_processor/pantherlog/result.go, internal/log_analysis/log_processor/pantherlog/result_test.go, internal/log_analysis/log_processor/pantherlog/scanners.go, internal/log_analysis/log_processor/pantherlog/values.go, internal/log_analysis/log_processor/parsers/factory.go, internal/log_analysis/log_processor/parsers/pantherlog.go, internal/log_analysis/log_processor/parsers/testutil/testutil.go
These changes result from observations when using the `pantherlog` module to define parsers and from the requirements of some new parsers regarding timestamp handling. The changes where collected in a single PR to avoid scattering these in multiple PRs lumped together with parser definitions. 
- Removes `Meta` field from `Result` since it's use restricted the `ResultBuilder` to a single log type without real benefits.
- Pass log type as an argument to `ResultBuilder` since it was restricting a `ResultBuilder` to a single log type.
- Add `EventTimer` interface for custom event time requirements
- Add `Result.EventIncludesPantherFields` for better workaround visibility
- Add `pantherlog.FieldSet` to handle sets of fields when building the event schema
- Fix bug with embedded structs in …
=> Simplify pantherlog Result handling and schema generation

cmd/opstools/gluesync/gluesync/main.go, cmd/opstools/requeue/requeue.go, cmd/opstools/requeue/requeue/main.go, cmd/opstools/s3queue/integration_test.go, cmd/opstools/s3queue/s3queue.go, cmd/opstools/s3queue/s3queue/main.go, cmd/opstools/s3queue/s3queue_test.go, docs/gitbook/operations/ops-home.md
The `requeue` opstool forced a user to enter both the `-from.q` and the `to.q`. 
Since Panther has a naming convention for associating a dlq, make the that default if `-from.q` if not specified.
- applied our naming convention as default for `-from.q` flag for `requeue`
- enhanced logging in `requeue`
- fixed logger initialization in all opstools to respect the `-verbose` flag
- updated user docs with more context
- mage test:ci
- ran integration test
- ran manually against a q with dlq entries
- ran manually against a fifo
=> Improve flag default behavior for requeue

docs/gitbook/operations/ops-home.md
As of this writing (August 2020) Pager Duty cannot [handle composite CloudWatch alarms](https://community.pagerduty.com/forum/t/composite-alarm-in-cloudwatch-not-triggering-pd-integration/1798) which Panther uses to avoid duplicate pages to oncall staff.
This PR documents a work around is to use a [Custom Event Transformer](https://www.pagerduty.com/docs/guides/custom-event-transformer/) in our ops doc.
=> Update ops doc with notes on how to configure PagerDuty

web/src/components/dropdowns/UpdateAlertDropdown/UpdateAlertDropdown.tsx
The wording of the snackbar informing the user of a successful change to an alert's status is awkward. 
- Change the wording from "Set alert to triaged" --> "Alert set to Triaged".
- tests pass, but this change shouldn't affect any tests
=> fix: reword the alert status snackbar

web/src/helpers/utils.tsx
Errors coming from the backend and directly presented in the frontend are sometimes not capitalized. We should show errors in a more natural way, i.e. capitalizing the first letter of the string or sentence describing an error.
- Modified the frontend helper `extractErrorMessage` to return an error string with the first letter capitalized.
- tests pass, although this change shouldn't affect testing.
=> fix: error extractor does not return capitalized error strings

internal/log_analysis/log_processor/pantherlog/meta.go
The helper got dropped somewhere along the way
- Adds `pantherlog.RegisteredFieldNamesJSON` helper
=> Add missing pantherlog.RegisteredFieldNamesJSON helper

build/actions/pr_sync/dist/index.js, build/actions/pr_sync/index.js
There was an issue in our sync automation where milestones were not cloned correctly. The issue was that milestones have different IDs across different repos.
This PR fixes that by comparing the "names" of milestones when choosing which one to assign
- Attempt to clone milestone based on name
- Verified in forked repos
=> Fix Sync automation milestone issue

cmd/devtools/logprocessor/logprocessor/main.go, cmd/opstools/gluesync/gluesync/main.go, cmd/opstools/requeue/integration_test.go, cmd/opstools/requeue/requeue.go, cmd/opstools/requeue/requeue/main.go, cmd/opstools/s3queue/integration_test.go, cmd/opstools/s3queue/s3queue.go, cmd/opstools/s3queue/s3queue/main.go, cmd/opstools/s3queue/s3queue_test.go, cmd/opstools/testutils/testutils.go, tools/mage/fmt_license.go
The dir for the tools was specified as "tools" but it should have been "cmd"
- Fixed dir
- Updated licenses in tools
- mage test:ci
=> Fix wrong dir for tools in fmt_license.go, update tools

cmd/devtools/logprocessor/logprocessor/main.go, internal/log_analysis/log_processor/destinations/s3.go, internal/log_analysis/log_processor/destinations/s3_test.go, internal/log_analysis/log_processor/processor/stream.go
There was a bug introduced when writing `pantherlog.Result` in S3 where all results were placed in a zero timestamp S3 object when the event being written specified the event time via a struct tag. 
- Serialize the event *before* picking a bucket to put it into
- Pass the `jsoniter.API` to use as an argument in `CreateS3Destination`
- Adds `s3BufferSet.writeEvent(event *pathnerlog.Result) (*s3Buffer, error)` method to handle the writing of events.
- mage test:ci
- e2e tests with mage:deploy and verified query results + bucket tree
=> Fix bug with log processor destination S3 object key

web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
Make  sure that events threshold doesn't appear on policy form page
Closes #1352 
- Exclude `events threshold` from policy form screen
- Visual. No need to write a  test case for that
=> fix: events threshold appearing on policy form. Closes #1352

web/src/components/Navigation/Navigation.tsx
Log Analysis is our main subproduct, so we want to emphasize on this by putting it first in the navigation bar. Now the first navigation entry is Log Analysis, followed by Cloud Security
- Change order of  nav items
- Visually
=> Fix: Order of Nav Entries

internal/log_analysis/log_processor/logtypes/registry.go, internal/log_analysis/log_processor/pantherlog/jsoniter.go, internal/log_analysis/log_processor/pantherlog/jsoniter_test.go, internal/log_analysis/log_processor/parsers/gravitationallogs/audit_test.go
These fixes exist in an the crowdstrike parsers branch and should be included in OSS as well
- Fix regression on indicator values sorting
- Ensure `panther:"event_time" struct tag sets UTC timestsamp
- Implement `fmt.Stringer` on logtypes entry
- maget test:ci
=> Backport pantherlog fixes from EE

internal/core/custom_resources/resources/alarms_lambda.go
Currently we will trigger an CW Alarm in case one AWS Lambda invocation runs for more than 90% of its configured timeout. 
Updating the alarm to fire only if this happens for 3 consecutive evaluation periods - if the problem persists. Many times a lambda could timeout due to some network hiccup.
=> Firing Max Duration alarm only in case a problem persists

web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
On small screens the chart tooltip overflows. This fixes it.
- Remove fixed tooltip positioning. Allow e-charts to handle it internally
- Viz
=> Fix: issue with tooltip on charts

internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
AWS.CloudTrail logs are delivered in an Array in a single JSON object. This strains the memory requirements of the log processor Lambda since it has to read the whole file to memory to parse it. Currently the parser uses `jsoniter.UnmarshalFromString` to parse the log line which *copies* the log line buffer by casting to `[]byte`. This means we require double the file size to parse the log line. This PR uses a `strings.Reader` to avoid this. It also pre-allocates the results slice to avoid multiple slice expansions during parsing and skips the duplication of slices that was needed to convert from `[]*CloudTrail` to `[]*parsers.PantherLog`.
- Changes `AWS.CloudTrail` to use a `strings.Reader` and iterate over the `Records` array avoiding allocations
- mage test:ci
=> Minimize allocations in AWS.CloudTrail parser

deployments/log_analysis.yml, internal/log_analysis/message_forwarder/config/config.go, internal/log_analysis/message_forwarder/forwarder/forwarder.go, internal/log_analysis/message_forwarder/forwarder/forwarder_test.go, pkg/awsbatch/kinesisbatch/put_records_test.go, pkg/testutils/awsmocks.go
As part of 1.7 we have introduced SQS source. 
One usecase is that users can forward messages to Panther making use of SNS->SQS subscription. 
However, if the SNS topic is in a different account than SQS, a confirmation message is sent. We need to confirm that message for the SNS topic to be able to forward messages to SQS. 
- Message Forwarder Lambda now confirms SNS->SQS subscription messages
- unit test
- deployed and verified cross-account subscription confirmation
=> Fix SNS subscription

web/src/components/GenericItemCard/GenericItemCard.tsx, web/src/pages/ListDestinations/DestinationCards/AsanaDestinationCard.tsx, web/src/pages/ListDestinations/DestinationCards/CustomWebhookDestinationCard.tsx, web/src/pages/ListDestinations/DestinationCards/DestinationCard.tsx, web/src/pages/ListDestinations/DestinationCards/GithubDestinationCard.tsx, web/src/pages/ListDestinations/DestinationCards/JiraDestinationCard.tsx, web/src/pages/ListDestinations/DestinationCards/SnsDestinationCard.tsx, web/src/pages/ListDestinations/DestinationCards/SqsDestinationCard.tsx
While testing I spotted that:
- Webhook URLs are not returned from the API so they shouldn't be displayed
- The severities don't have the necessary visual margin
- Add line breaks where needed
- Fix margin issues
- Remove webhook URL from destination card
- Manually
=> fix: visual issues with destinations

internal/compliance/snapshot_poller/pollers/aws/clients.go, internal/log_analysis/log_processor/common/common.go, pkg/awsretry/connection_retryer.go, pkg/awsretry/connection_retryer_test.go
The DefaultRetryer used was not initializing the NumMaxRetries, fix defaulted to 0 and no retries were being attempted.
- Set NumMaxRetries in constructer 
- Set log processor MaxRetries to 15 (reverting previous change from 15 to 25, 25 is uneccessary)
- Used recommended request.WithRetryer() to apply retryer
- mage test:ci
- deployed to security account where we have significant activity
=> Fix awsretry to initialize with NumMaxRetries

internal/compliance/snapshot_poller/pollers/aws/clients.go, internal/log_analysis/log_processor/common/common.go, pkg/awsretry/connection_retryer.go, pkg/awsretry/connection_retryer_test.go
Fix awsretry to initialize with NumMaxRetries (#1418)
=> Fix awsretry to initialize with NumMaxRetries (#1418)

deployments/bootstrap.yml
Require secure access to s3 buckets always, even when log principals are not configured.
- Added secure access requirement to two buckets
- Dev deployment
=> Require secure access

internal/log_analysis/log_processor/pantherlog/meta.go, internal/log_analysis/log_processor/pantherlog/scanners.go, internal/log_analysis/log_processor/parsers/awslogs/indicators.go
The indicator fields for AWS logs where not yet defined, pending the porting of AWS parsers.
This PR adds the indicator fields without modifying any parsers so APIs can query all the available indicator fields.
- Defines and registers indicator fields for AWS indicators
- mage test:ci
=> Adds AWS indicator fields

package-lock.json, package.json, web/src/components/BorderedTab/BorderedTab.tsx, web/src/components/Navigation/NavLink/NavLink.tsx, web/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap, web/src/pages/ListAlerts/ListAlertsTable/ListAlertsTable.tsx, web/src/pages/LogAnalysisOverview/AlertsTable/AlertsTable.tsx, web/src/pages/LogSourceOnboarding/LogSourceCard/LogSourceCard.tsx
The latest pounce has some  breaking changes. This PR makes sure to migrate safely to the  latest API
- Replace `css` with `sx`
- Replace `PseudoBox` with `Box`
- `npm run validate`
=> Migrate to latest pounce

.circleci/config.yml, internal/core/analysis_api/handlers/list.go
When sorting compliance policies by status, they do not appear to be grouped correctly:
The "Disabled" status shows up among the "Pass" status - this is because even disabled policies are still evaluated, we just don't yet show its underlying status to the user (we should eventually).
Until then, the backend will first sort by enabled/disabled status so that the column sorts as you would expect
Closes: #1179 
- When sorting policies by status, sort first by enabled/disabled (to group all disabled policies together at the end)
- Add some clarifying comments
- After applying the change and sorting on the column:
- `PKG=./internal/core/analysis_api/main dev -- mage test:integration`
=> Group disabled policies together when sorting by status

deployments/bootstrap.yml, tools/mage/test_cfn.go
Some of Panther's buckets were missing the `ForceSSL` bucket policies until the last release, so I've added a check to `mage test:cfn` to flag buckets without the appropriate statement.
It's very simple, just checking for "Sid: ForceSSL" attached to every bucket. It's not actually evaluating the policy, which can get quite complex. But this will catch the most common problem - devs forget to add it to new buckets
Closes: #1421 
- `mage test:cfn` fails if an S3 bucket does not have a `ForceSSL` statement attached in the same template
- Collapse the ProcessedData bucket policy into a single resource with conditional statements (rather than two completely separate policy resources). Having two separate resources is harder to check with automation and also more prone to errors when CFN …
=> Update mage test:cfn with check for S3 bucket ForceSSL statement IDs

internal/log_analysis/log_processor/processor/processor.go, internal/log_analysis/log_processor/processor/processor_test.go
The log processor lambda currently silently ignores invalid log types in a source configuration. Such an error would be hard to pinpoint. This PR fails the log processor if a source has an unknown log type in it's configuration
- Fails the log processor if the incoming source has an unknown log type
- mage test:ci
=> Fail when a source has an unknown log type

internal/core/alert_delivery/api/deliver_alert.go, internal/core/alert_delivery/api/deliver_alert_test.go, internal/log_analysis/alerts_api/table/table.go
The alert model for DDB contained an unused field `OutputIds` which is not stored in DDB nor used in the application.
This issue did not cause any bugs, it is superfluous and is being removed.
- removed `OutputIds` from the model
- updated tests to reflect the change
- updated application code where this field was being set
- mage test:go
- mage test:ci
=> Remove unused model field from the alert

web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
The link existing on the label of `LogSourceCards` it's wrongly hardcoded as SQS, this PR fixes that by generating the correct link based on source type.
- Added and used `sourceType` for each card
- Locally
- Deployed env
=> hotfix: Fix Label link for source

web/src/pages/RuleDetails/RuleDetails.tsx
When re-visiting a rule  that you have visited  in the past, the page won't attempt to re-fetch the previously fetched alerts. This might cause inconsistencies, since more  alerts might have fired since then.
The solution up until now, was to refresh the page. This fix makes that not required
- Add `cache-and-network` to alert-related  queries
- Locally
=> Re-fetch alerts on every rule page visit

internal/log_analysis/log_processor/parsers/apachelogs/access_common.go, internal/log_analysis/log_processor/parsers/apachelogs/access_common_test.go
Response size in CLF maybe "-" instead of 0.
See https://httpd.apache.org/docs/current/logs.html#common
=> Fix parsing response size in Common Log Format logs

internal/core/alert_delivery/outputs/pagerduty.go, internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sns_test.go, internal/core/alert_delivery/outputs/sqs.go, internal/core/alert_delivery/outputs/sqs_test.go, internal/core/alert_delivery/outputs/utils.go
Closes #1486 
- Returns a response status for SQS and SNS destinations
- Return more descriptive error payloads
- mage test:ci
=> fix: return a success response for sqs and sns

magefile.go, tools/mage/master/build.go, tools/mage/master/deploy.go, tools/mage/master/publish.go
After the mage refactor (#1458 ), `master:deploy` fails with:
```
Error: Unable to upload artifact ../out/deployments/embedded.bootstrap_gateway.yml referenced by TemplateURL parameter of BootstrapGateway resource.
TemplateURL parameter of BootstrapGateway resource is invalid. 
```
The problematic template is the one where we directly inject the Swagger specification. After the refactor, the CloudFormation-Swagger build moved to a different place and it just needs to be re-added explicitly.
I also took the opportunity to quickly fix up `master:deploy` so that it's easier to run - it will automatically create an S3 bucket and ECR repo for developers instead of requiring them to be specified as env variables.
-`master:deploy` now builds the API gateway template before packaging it
- Fixed …
=> Fix mage master:deploy

internal/core/alert_delivery/outputs/pagerduty.go, internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sns_test.go, internal/core/alert_delivery/outputs/sqs.go, internal/core/alert_delivery/outputs/sqs_test.go, internal/core/alert_delivery/outputs/utils.go
Sync changes #1492 merged into `release` back into `master`.
- Return a success delivery response from SNS/SQS payloads
- mage test:ci
=> fix: sns and sqs delivery statuses

deployments/auxiliary/cloudformation/panther-deployment-role.yml, deployments/auxiliary/terraform/panther_deployment_role/main.tf
Teardown with the Panther deployment role failed:
> stack panther-bootstrap: AWS::EC2::EIP NatPublicIP DELETE_FAILED: API: ec2:releaseAddress You are not authorized to perform this operation
- Add `ec2:ReleaseAddress` to deployment role (CF and TF)
- Teardown succeeded with this change
=> Add ec2:ReleaseAddress to deploy role

web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx
When users have a big email, the  profile settings popup cuts the  email out.
This PR allows the profile popup to have a dynamic width based on its content
- Change `width` to `maxWidth`
- Visually
=> fix: add dynamic width  to profile popup

web/src/apollo/typePolicies.ts
Due to an issue with Apollo keyfields, whenever a user updated the GeneralSettings form's email, the form was failing to set the new initial values to the updated ones (it thought the initial values where the ones before the update).
This caused issues forcing the users to refresh in order to see the "disabled" button as "enabled"
- Add static non-modifiable key field for GraphQL types that are singletons (only one instance of them is present)
- Visually
=> Fix issue with form General Setting's form initial values

deployments/cloud_security.yml, internal/core/custom_resources/resources/alarms_api_gateway.go, internal/core/custom_resources/resources/alarms_lambda.go, internal/core/users_api/cognito/create_user.go, tools/mage/master/deploy.go
A few small bugfixes based on observed problems in existing deployments.
- Bump snapshot-poller memory from 128 to 512 MB. One of our deployments is running out of memory, and this is a critical piece of infra that needs more cpu/network at all times anyway (just like the log processor). The extra monetary cost is typically negligible compared to log processing.
- Add a comment about why we lowercase emails in Cognito (@alxarch )
- Allow `mage master:deploy` with an optional `STACK` env variable - this way, you can deploy the pre-packaged version on top of any stack name. We already support `STACK=name mage teardown`, so this is a natural extension.
- CI; will deploy to release env after merged internally
=> Small ops improvements

package.json
`npm` complains the license is not in a valid format:
```
license should be a valid SPDX license expression
```
- Update the license field from `Apache v2.0` -> `Apache-2.0`
- npm i
=> fix: change the license to an acceptable format

internal/log_analysis/log_processor/pantherlog/pantherlog.go
I forgot to add this PR a while back and docs were not up-to date with the code base. Thankfully someone noticed it on Slack.
Re-export field types from the pantherlog package so event types only need to import a single package.
This makes explaining the process of adding support for a new log type much easier.
It also allows us to change implementations of a field type in the future without modifying parser code
- Re-export types for common fields from the pantherlog using type aliases
- mage test:ci
=> Re-export field types from pantherlog modules

internal/log_analysis/log_processor/pantherlog/pantherlog.go
I forgot to add this PR a while back and docs were not up-to date with the code base. Thankfully someone noticed it on Slack.
Re-export field types from the pantherlog package so event types only need to import a single package.
This makes explaining the process of adding support for a new log type much easier.
It also allows us to change implementations of a field type in the future without modifying parser code
- Re-export types for common fields from the pantherlog using type aliases
- mage test:ci
=> Re-export common field types from the pantherlog module

deployments/bootstrap.yml
Add name tag to EC2 resources so it is easy to identify panther-created resources in the aws console.  Prevents user from having to dig into the console to find the "Application: Panther" tag by displaying name field. Closes #1422 
- Added name tags to EC2 resources that support tagging.  Reference: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html
- A few of the EC2 resources in use don't support tags: [VPCGatewayAttachment, Route, SubnetRouteTableAssociation, SecurityGroupIngress] 
- `mage test:ci` and verifying name shows up in the console.
=> add name to ec2 resources

internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sns_test.go, internal/core/alert_delivery/outputs/sqs.go, internal/core/alert_delivery/outputs/sqs_test.go
SNS/SQS alert deliveries will fail if there is more than one SNS/SQS destination in a single alert. This is because we have a map caching clients by region, but we access that map from each goroutine which delivers alerts in parallel:
```
  | 2020-09-11T14:04:55.167-07:00 | fatal error: concurrent map writes
  | 2020-09-11T14:04:55.206-07:00 | goroutine 12 [running]:
  | 2020-09-11T14:04:55.206-07:00 | runtime.throw(0xe3965d, 0x15)
  | 2020-09-11T14:04:55.206-07:00 | /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72 fp=0xc0005d97b8 sp=0xc0005d9788 pc=0x4332f2
  | 2020-09-11T14:04:55.206-07:00 | runtime.mapassign_faststr(0xd1f7e0, 0xc000606f00, 0xc0001000fc, 0x9, 0x1)
  | 2020-09-11T14:04:55.206-07:00 | /usr/local/Cellar/go/1.14/libexec/src/runtime/map_faststr.go:291 +0x3de …
```
=> Remove cached sns/sqs clients from alert-delivery

web/src/components/badges/AlertStatusBadge/AlertStatusBadge.tsx
Closes #1535 
- Changed color attributes of the `AlertStatusBadge`
- visually
=> refactor: changed colors for alert statuses

web/src/components/JsonViewer/JsonViewer.tsx
When there's a lot of text in a JSON blob, then the text can overflow outside the container.  This PR makes sure that the text is always restricted within the limits of its bounding box.
For more info, check out the reported issue #1542 
Closes #1542 
- Add `wordBreak` on `JsonEditor`
- Visually
=> fix: JSON tree overflow

internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sns_test.go, internal/core/alert_delivery/outputs/sqs.go, internal/core/alert_delivery/outputs/sqs_test.go
Syncs #1530 release bugfix to master. All other release bugfixes are already included. This will no longer be necessary after #1546 
This will need to be a standard merge (not a squash)
=> Sync release bugfix: sns/sqs clients

tools/mage/master/publish.go
We use `mage master:publish` to package the release and publish to our public S3 buckets. I'm generally the only one who has used the command so far, but the v1.8 release cycle revealed some problems that I can quickly fix
- Don't do a full `mage clean` before every publish, because it takes quite a long time to reinstall all the `npm` packages from scratch. All we really care about is removing the build artifacts (`out/`). We still update dependencies (`mage setup`), we just don't need to erase them ahead of time - `setup` will automatically update any that are out of date.
- Allow overwriting an existing release with a warning and an additional prompt. Sometimes, there is a tiny bug that can be fixed by just republishing the existing version number (especially for release candidates / …
=> mage master:publish: double-prompt to allow overwriting existing release

internal/compliance/alert_processor/models/api.go, internal/compliance/alert_processor/processor/processor.go, internal/compliance/alert_processor/processor/processor_test.go, internal/compliance/resource_processor/processor/handler.go, tools/mage/test/cfn.go
* While investigating an error I realized some of the error messages were missing some information. Updated error messages in alert-processor to give more context about the operation that failed (policyID & resourceID)
* I modified the `ComplianceNotification` to include scalars instead of pointers. All the fields are getting anyway populated, new code is much simpler since we don't need to dereference pointers. 
* cfn-lint started failing with 
```
E3002 Invalid Property Resources/WebApplicationServer/Properties/NetworkConfiguration/AwsvpcConfiguration
deployments/web_server.yml:208:9
```
However, the property is valid: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-networkconfiguration.html#cfn-ecs-service-networkconfiguration-awsvpcconfiguratio …
=> Updated logged error to include more information

deployments/bootstrap_gateway.yml, internal/core/custom_resources/resources/alarms_api_gateway.go
The `describe-org` operation of compliance-api needs to scan the DDB resources table in order to generate some statistics. 
This operation can take longer in deployments that include a lot of monitored resources. This is an architectural deficiency of the current design. This operation invoked whenever a user accesses the Panther dashboard in order to generate some statistics.  
Increasing the latency threshold for compliance-api
- Increasing the latency threshold for compliance-api
- mage test:ci
=> Update the latency threshold for compliance-api

.github/workflows/main.yml
Github actions behaves weirdly  when switching & checking-out branches using custom `run` commands. This PR fixes this and makes sure that `git checkout` works correctly in a job's steps
- Add `fetch-depth: 0`
- Shorten new-branch-spawning commands
- In Fork
=> ci: force clone entire repo

.github/workflows/main.yml
The release sync automation targets the `master` branch. This PR fixes it to target the `release`
- Use github event item instead of ENV var
- Change PR sync's base branch
- In fork
=> ci: Fix target branch of release syncs

web/src/pages/AlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx, web/src/pages/PolicyDetails/PolicyDetailsInfo/PolicyDetailsInfo.tsx, web/src/pages/RuleDetails/RuleDetailsInfo/RuleDetailsInfo.tsx
This one fixes some alignment issues regarding the threshold values. Tags may get quite lengthy breaking the lines between the columns, thus a grid is required in order to create a more structured way for displaying the rule details.
=> Add proper grid alignment for rows in rule details

internal/compliance/snapshot_poller/models/aws/ec2_instance.go, internal/compliance/snapshot_poller/pollers/aws/ec2_instance.go
Add the `EC2MetaDataOptions` field to the CloudSecurity EC2 Instance resource. Closes https://github.com/panther-labs/panther-analysis/issues/112. 
- Add new field to resource model
- Dev deployment
=> Add meta data options

internal/compliance/snapshot_poller/pollers/aws/awstest/assume_role.go, internal/compliance/snapshot_poller/pollers/aws/clients.go, internal/compliance/snapshot_poller/pollers/aws/poll_test.go, internal/compliance/snapshot_poller/pollers/aws/utils_test.go
When assuming a role in another account in the snapshot-poller, we always used the ENV credentials of the lambda function to create a session in the Panther account and used that session to assume the role. This works fine, except for when you want to use the credentials created by the assumed role to query regional endpoints in regions that are not enabled in the Panther account but are enabled in the account the role to be assumed lives in.
I believe this affects the Log Analysis log-processor based on the source code, but I was repeatedly failing to subscribe an SNS topic in `ap-east-1` to the the panther SQS queue I had deployed in `us-east-1` in a different account to test this. I still have not figured it out, creating the subscription with CloudFormation failed. Creating it from …
=> Fix edge case in role assumption

deployments/master.yml, tools/mage/master/publish.go
The Panther version is applied manually the master.yml template before a release.
This PR validates that the applied version tag matches the repo git tag.
I did not test this, but it looks right and we can test with 1.9 release.
=> Ensure master template is published with same version tag as repo

deployments/log_analysis.yml, internal/core/custom_resources/resources/glue.go, internal/core/source_api/api/put_integration.go, internal/log_analysis/awsglue/table_metadata.go, internal/log_analysis/gluetables/gluetables.go
I realized there is no easy way to force the custom resource "Custom::UpdateGlueTables" to run on a deployment. 
Before it was only running if the signature of the deployed tables had changed or if the Panther version had changed. With this change, it also runs in case some user specifies a `CUSTOM_RESOURCE_VERSION` env variable (this is the model we follow for all other resources as well)
- Deployed to my account and verified the script runs in case the `CUSTOM_RESOURCE_VERSION` variable is specified.
=> Updating Glue table update to run on CUSTOM_RESOURCE_VERSION upgrade

web/src/pages/AlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
Found this issue in the UI. Faster to fix it than making an issue for it :P
Before the threshold had 'minute` attached to it
After 
- mage test:ci
- deployed and verified
=> Fixing minor UI issue

tools/mage/deploy/frontend.go, tools/mage/master/publish.go
#1589 changed the master template version to be prefixed with a `v`. But the `mage master` code still assumes the version does not have the prefix.
- Fix `mage master` source code - the loaded version is now always prefixed with `v`
- I will publish v1.9.0-RC1 after this merges to the release branch, which will test this code path
=> Remove redundant version prefix

api/graphql/schema.graphql, api/lambda/organization/models/api.go, internal/core/custom_resources/resources/map.go, internal/core/organization_api/main/integration_test.go, internal/core/organization_api/table/update.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts
Since we are implementing telemetry for the frontend, we need to allow users to opt-out from product analytics. We need to persist their selection in DB in an identical fashion as we do with errorReportingConsent.
We need to update the backend to handle this operation and store the `analyticsConsent` boolean
Closes #1598 
- Added `AnalyticsConsent` Bool in API model
- Updated `organization-api` to handle update
- Updated schema
- Deployed env API and UI test
=> AnalyticsConsent for General settings

web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx, web/src/pages/PolicyDetails/PolicyDetailsInfo/PolicyDetailsInfo.tsx
This PR fixes a malformed `null` values concatenated for ignored patterns.
=> Fix remove `null` from ignore patterns

api/lambda/alerts/models/api.go, api/lambda/delivery/models/api.go, internal/core/alert_delivery/outputs/asana_test.go, internal/core/alert_delivery/outputs/custom_webhook_test.go, internal/core/alert_delivery/outputs/github_test.go, internal/core/alert_delivery/outputs/jira_test.go, internal/core/alert_delivery/outputs/msteams_test.go, internal/core/alert_delivery/outputs/opsgenie_test.go, internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/outputs_test.go, internal/core/alert_delivery/outputs/slack_test.go, internal/core/alert_delivery/outputs/sns_test.go, internal/core/alert_delivery/outputs/sqs_test.go, internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go, internal/log_analysis/alert_forwarder/forwarder/models.go, internal/log_analysis/alert_forwarder/forwarder/models_test.go, internal/log_analysis/alerts_api/api/get_alert.go, internal/log_analysis/alerts_api/table/table.go, internal/log_analysis/alerts_api/utils/utils.go, internal/log_analysis/awsglue/schema.go, internal/log_analysis/awsglue/schema_test.go, internal/log_analysis/rules_engine/src/alert_merger.py, internal/log_analysis/rules_engine/src/engine.py, internal/log_analysis/rules_engine/tests/test_engine.py, internal/log_analysis/rules_engine/tests/test_output.py
We were using "Type" to define if an alert if because of a Rule or Policy and an "ErrorType" to differentiate between "Rule Error" and "Rule matches". Seems better approach to extend the Alert Type to be one of "Policy"(failure), "Rule"(match), "Rule Error". This could make it easier to use the same structure for other types that are not necessarily errors
- Changed Alert API to handle the new type
- Changed Alert Delivery to handle the new type
- Changed rules engine to populate handle the new type
- mage test:ci
- Deployed and generated a rule that hits an error. Seeing it in the UI:
=> Switch to using "Alert Type" in the alert rather than "error Type"

go.mod, go.sum, internal/log_analysis/log_processor/pantherlog/tcodec/extension.go, internal/log_analysis/log_processor/pantherlog/tcodec/extension_test.go, internal/log_analysis/log_processor/pantherlog/tcodec/registry.go, internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go, internal/log_analysis/log_processor/pantherlog/tcodec/tcodec_test.go, internal/log_analysis/log_processor/pantherlog/tcodec/unix.go
Closes #1511
- Adds the ability to use `tcodec:"strftime=%Y-%m-%d" tags to parse JSON timestamps using a custom format defined in [strftime](https://strftime.org/)
- Adds missing codecs for microsecond and nanosecond UNIX timestamps (`unix_us`, `unix_ns`)
- Unit tests
=> Add support for strftime and unix microseconds/nanoseconds to tcodec 

internal/log_analysis/rules_engine/src/main.py, internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_main.py, internal/log_analysis/rules_engine/tests/test_output.py, internal/log_analysis/rules_engine/tests/test_rule.py
Closes #1592
See https://github.com/panther-labs/panther/issues/1592 for more context.
The rule engine now returns any errors raised from `title()` or `dedup()` instead of swallowing them.
Subsequently, rule tests will fail if any of its functions raises an exception.
- unit test
=> Make rule engine return the exception if title() or dedup() raises

deployments/master.yml
Again, this is really just testing the sync-to-release functionality, which I forgot to do in #1654 
- Bump version in master template to `1.10.0-RC1`
=> Bump version in master stack

.github/workflows/main.yml
#1652 updated the automation to *checkout* the correct release branch, but when submitting the sync PR, `panther-bot` still set `release` as the branch base: https://github.com/panther-labs/panther/pull/1656
I had to manually change the branch base, and then the PR was fine.
- Fix the sync automation: change base branch from `release` to the same versioned release branch that we checked out
According to the [GitHub docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable), the `echo >> $GITHUB_ENV` syntax I'm using allows me to share an environment variable with a future step in the same job
We'll see what happens when this PR is merged! GitHub actions seem to be pretty hard to test without just making …
=> Sync automation: fix release branch base

.github/workflows/main.yml
Take 3! #1657 was able to get the branch name passed to the PR creation, but because we are listing remote branches, the branch name was `origin/release-1.10` instead of `release-1.10` and the action failed: https://github.com/panther-labs/panther/runs/1200950117?check_suite_focus=true
So now I strip the `origin/` prefix from the branch name before passing the env variable.
Verified syntax locally:
```bash
BRANCH="origin/release-1.10"
echo "LATEST_RELEASE_BRANCH=${BRANCH#origin/}"
```
=> Release sync automation: Strip origin prefix from branch name

.golangci.yml
#1658 seemed to work: the `release-1.10` branch was checked out and a PR was attempted, but the last step failed with
> refusing to change .github/workflows/main from GitHub App without the "workflows" permission
I'm hopeful that means any other change will sync correctly. Let's find out!
- Fix comment in `.golangci` - we don't "check" formatting, we just do it on behalf of the developer
We'll see what happens when this merges!
=> Small comment change to trigger release sync again

tools/mage/gen/gen.go
Code Scanning found an insecure regex containing an unescaped period `.` in `github.com`
- Added a backslash to regex to denote a literal `.` i.e. `github.com` => `github\.com`
=> Added backslash to escape dot in 'github.com'

api/graphql/schema.graphql
Deployments from `master` are failing with:
> stack panther-appsync: AWS::AppSync::GraphQLSchema GraphQLSchema CREATE_FAILED: Schema Creation Status is FAILED with details: Found 1 problem(s) with the schema:
The type 'ListAlertsInput' [@202:1] has declared an input field with a non unique name 'logTypes'.
Turns out there is a duplicate schema field. @3nvi , is there a check we can add to CI to prevent a bug like this from merging again?
This bug is not present in the `release-1.10` branch
- Remove duplicate field
- Fresh deploy (in progress)
=> Bugfix: remove duplicate logType from GraphQL schema

internal/core/alert_delivery/outputs/sns.go, internal/core/alert_delivery/outputs/sns_test.go, pkg/testutils/awsmocks.go
There was a bug in the SNS destination. SNS subjects can only be up to 100 characters in length, but we were only limiting alert titles to 1000 characters in length. I updated specifically the SNS destination to truncate to 100 characters in the subject field. The full (up to 1000 characters) title is still present in the message body.
- Truncate subject after 100 characters when sending to SNS
- Updated unit test to have a policy name over 100 characters in length, and ensured it was adequately truncated for SNS messages
- Fresh deploy in progress, will update once I verify a message is successfully delivered to an SNS topic even with a 100+ character title.
=> handle case where sns subject is over 100 characters

internal/log_analysis/rules_engine/src/alert_merger.py, internal/log_analysis/rules_engine/src/aws_clients.py, internal/log_analysis/rules_engine/src/main.py, internal/log_analysis/rules_engine/src/output.py
We have occasional alarms due to aws api failures in the rule engine. It is using default settings. This PR increase the retries to 10 and uses a more modern (similar to Golang SDK) implementation for retries.
- Added config for retries using "standard' retry mechanism
- Refactored AWS client creation
- mage test:ci
- deployed and created an `AlwaysTrue` rule, no errors in CloudWatch and UI displayed the alerts and alert events.
=> Increase aws sdk retries for rules engine

web/src/components/utils/AuthContext/AuthContext.tsx, web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx, web/src/helpers/analytics.ts, web/src/pages/CreateRule/CreateRule.tsx
We shouldn't report error data to our product analytics.
- Removed data property from `trackError`
- Locally
=> Removed data from trackError for analytics

dev.sh, tools/mage/setup/setup.go
`mage setup` failed for both @vorillaz and I in the development image (`./dev.sh`) with:
>  18:26:43	INFO	[setup]	pip install requirements.txt to .setup/venv...
ERROR: Could not install packages due to an EnvironmentError: [Errno 5] Input/output error
As best I can tell, this is caused by too many open files or not enough disk space. After a `docker system prune --volumes` (from within the image), it worked for me and has continued to work every time I've tried it since. It always works outside the docker image.
So I don't know for sure if these changes will completely fix the problem we encountered, but they should certainly help. One is to update the `dev.sh` image to the correct version and the other is to change `mage setup` to be sequential. `npm install` and `pip install` running at …
=> Sequential mage setup and update dev image version

web/src/components/wizards/SqsSourceWizard/ValidationPanel/ValidationPanel.tsx
SQS onboarding would direct me to the Cloud Security/Sources upon successful completion. 
- Fixed redirection
- Deployed and verified in my account
=> Fixing redirect of successful SQS onboarding

cmd/opstools/requeue/requeue/main.go
We changed our q naming convention to always have `-queue` at the end and dlq's end in `-queue-dlq`.
The default "from" q in the `requeue` opstool was not updated.
- Update default for from q to current naming convention.
- mage test:ci
=> Fix generating default dlq name (naming convention changed) in requeue ops tool

internal/log_analysis/datacatalog_updater/process/setup.go
Got ticket for "read: connection reset by peer".
- Changed to use custom retryer
- mage test:ci
=> Add retryer to datacatalog-updater lambda

internal/core/custom_resources/resources/self_registration.go
We have noticed that sometimes when updating an account, the sources-api will throw an error. The issue can occur in the following scenario: 
1. User deploys Panther for first time. Disabled self on-boarding for cloud security
2. User onboards Panther account manually. 
3. Use enables self-monitoring when updating the account
The above would lead to an error in the sources API like the one below: 
```
{"level":"error","ts":1602342918.492403,"caller":"api/put_integration.go:58","msg":"failed to put integration","application":"panther","requestId":"1fb2b8d0-98b0-4b26-8bb5-7f0b3b6c49df","error":"Source account 123456789012 already onboarded"}
```
The above error is not causing some permanent issue in the system, it is however leading to some false CW Alarm triggers
- Update the …
=> Avoid errors during self-onboarding

web/src/helpers/analytics.ts
All product analytics events should have an additional field about the system version the are generated
- Added `STABLE_PANTHER_VERSION` as version property for mixpanel metadata
- Locally
=> Add version to all tracking events

pkg/awsbatch/sqsbatch/delete_message_batch.go
It appears that from time to time we see cases were the log processor fails to delete SQS messages from the queue and they get reprocessed. 
I suspect the issue could be caused by partial failures to delete SQS messages in the BatchDelete operation.
Fixing the error logging (changed it to warning) to check for all SQS message deletion failures. 
- Logging a warning if we fail to delete a message from SQS
=> Added warning in case we fail to delete SQS messages

deployments/log_analysis.yml
The `UpdateGlueTables` resource on every deployment is triggers the `panther-datacatalog-updater`. As such, it had an un-enforced dependency on the `UpdaterFunction`. This could lead to a race condition were `UpdateGlueTables` with version X would try to invoke `panther-datacatalog-updater` with version X-1 resulting in message drops. 
- Added an explicit dependency between CFN resources.
- `mage deploy`
=> Add dependency to UpdateTables resource

web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.test.tsx, web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.tsx
The phrasing used in the Alert Delivery text in the Alert Details page was a bit misleading. This PR makes it a bit more clear
- Update phrasing
=> fix: Alert Delivery text

web/src/pages/ComplianceOverview/TopFailingPoliciesTable/TopFailingPoliciesTable.tsx, web/src/pages/ComplianceOverview/TopFailingResourcesTable/TopFailingResourcesTable.tsx
In Cloud Security overview page, some data cause the tables to overflow. This PR makes sure to force words to wrap( since we have stuff like ARNs which is a **single big word** that can easily overflow) whenever they exceed the available width
- Add `word-break: break-all` to links that have large texts
- Visually
=> Aggelos fix overview tables

deployments/log_analysis.yml, internal/log_analysis/gluetasks/recover.go, internal/log_analysis/gluetasks/sync.go
Syncing #1759 and #1751 into the 1.10 release (they automatically synced to the 1.11 release branch, but we have to manually copy it back to 1.10)
After these fixes, we can publish 1.10.1 from this branch
- Fix deploy dependency (git cherry-pick 71ccf54)
- Fix `glue*` tools (git cherry-pick 6807436)
=> [Sync] 1.10.1 Bug fixes

deployments/master.yml
Forgot to bump the master template version in #1765 (this sort of PR won't be necessary after #1711 )
=> 1.10.1: bump version in master template

deployments/appsync.yml
ListAvailableLogTypes was not working after backporting cutomlog changes. (The change was missed in the sea of changed files)
No need to sync to release, already fixed there
- Forces empty object (`{}`) payload for `ListAvailableLogtypes` endpoint in AppSync resolver
- Deployed and tested that FE can retrieve available log types
=> Fix AppSync for ListAvailableLogTypes

web/src/components/wizards/SqsSourceWizard/SqsSourceConfigurationPanel/SqsSourceConfigurationPanel.tsx, web/src/components/wizards/SqsSourceWizard/ValidationPanel/ValidationPanel.tsx, web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.test.tsx, web/src/pages/EditSqsLogSource/ΕditSqsLogSource.test.tsx
This PR includes fixes for some bad validation checks for wizards used when onboarding logs.
- Correct validation for `integrationLabel`
- Removed misleading button when creating/updating SQS
- Locally
=> Onboarding Logs validation fix

api/lambda/alerts/models/api.go, internal/log_analysis/alerts_api/api/list_alerts_test.go, internal/log_analysis/alerts_api/table/list.go, internal/log_analysis/alerts_api/table/table.go
Closes #1749 
Alerts API now can filter the alerts by type (Rule matches or Rule errors). We introduce a new "Type" parameter that lets the users select the API to return `RULE` or `RULE_ERROR` (in the future it could add one filter for policy @s0l0ist )
- Added the ability to filter alerts by type
- mage test:ci
- Tested E2E (tested also backwards compatibility)
=> Alerts API now can filter the alerts by type (Rule matches or Rule errors)

deployments/bootstrap_gateway.yml
Analysis API is currently doing a DDB scan to retrieve the enabled rules/policies. Seeing sometimes the `/enabled` operation, depending on the number of rules, can to take >1second
- Updating threshold
@austinbyers @s0l0ist not sure if there is a reason for greater concern here?
=> Updating threshold for analysis API

tools/mage/deploy/deploy.go
#1795 had a bug when deploying the `cfn-custom-resources` lambda directly - this function is in the `bootstrap-gateway` stack, which has to be injected with Swagger before CloudFormation runs, which means the function code path is slightly different from the other stacks.
- Instead of stripping `out/bin/`, we now strip `out/` and `bin/` separately. Kind of a hack, but works fine
- `LAMBDA=cfn-custom-resources mage deploy`
- `LAMBDA=policy-engine mage deploy` (to make sure this doesn't introduce a Python regression)
- `LAMBDA=log-processor mage deploy` (to make sure this doesn't introduce a Go regression)
=> Bugfix for custom-resources lambda

internal/core/source_api/api/list_integrations.go, internal/core/source_api/api/vars.go, internal/core/source_api/ddb/ddb.go
Small increase in default number of retries for source-api. Now doing 5 retries (compared to default of 3), so we are retrying for ~5 seconds. 
Source-api is queried by BE and FE services, so need to keep the number of retries to something that would make sense for both. 
- test:ci
=> Slight increase in source-api retries

internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
An S3 object ending in "/" is a "folder" object. It cannot contain data but it can be used to visually group S3 objects together. 
S3 will send notifications when someone creates an object like this and Log processor would try to process it. Added a check that ignores such objects. 
- Added unit test.
=> Ignore "S3 folder" objects

internal/log_analysis/alerts_api/api/get_alert.go
While testing 1.11 found this bug. It demonstrates for rules that use threshold. 
- Fixing S3 list object operation
- pending E2E
=> Fixing issue when retrieving events for an alert

internal/compliance/snapshot_poller/pollers/aws/ec2_vpc.go, internal/compliance/snapshot_poller/pollers/aws/ec2_vpc_test.go
In a recent change (#1784) I changed how VPC scanning works to include only a list of security group and network acl IDs, and not a full list of embedded security groups and network acls. Policies that needed to consider the contents of a security group while evaluating a VPC would need to use the `resource_lookup` helper.
As a convenience, I pulled up the default security group ID and the default network ACL ID as these elements are frequently more interesting than other security groups/network acls, and having to do 20 resource lookups just to find the default seemed unwieldly. Unfortunately, I mistyped the check for default security groups so this feature is not working as intended. This PR fixes that bug.
- Removed an extraneous trailing space
- Deployed into my dev account and …
=> VPC Scanning bug fix

internal/compliance/aws_event_processor/processor/accounts.go, internal/compliance/aws_event_processor/processor/handler.go, internal/compliance/aws_event_processor/processor/handler_test.go
Increase retries when reading CloudTrail objects from S3. Found some errors in our logs that could have been avoided. 
- mage test:ci
=> Increase retries when reading CloudTrail objects from S3

api/lambda/metrics/models/api.go, internal/core/metrics_api/api/get_metrics.go
Closes #1648 
Sometimes Panther will have no data points to report for a specific metric. This is an expected state for the system (I believe) and can happen if someone hasn't enabled some part of the Panther application (e.g. if they haven't onboarded any logs) 
Stop throwing an error if the metrics api doesn't have datapoints for a given metric for a given period. 
- Remove error check
- mage test:ci
- Pending E2E test
=> Removed error from metrics API

web/src/constants.ts, web/src/pages/GeneralSettings/__snapshots__/GeneralSettings.test.tsx.snap
Until now, documentation has been built from versioned doc branches, e.g. `v1.11-docs`. But now that we have versioned release branches, e.g. `release-1.11`, the separate doc branch is redundant (and it's a pain to remember to keep it up to date).
I've updated our GitBook settings to sync `release-X` branches; this PR is just changing the base doc link in the web app to have the new branch name
Closes: https://github.com/panther-labs/panther-enterprise/issues/944
- `docs.runpanther.io/v/v1.11-docs` => `docs.runpanther.io/v/release-1.11` (I like this link better anyway)
- Deploying now and will verify doc links work in web app
=> Change doc branch name

internal/core/custom_resources/resources/alarms_sqs.go
Increasing the evaluation period for SQS queue delayed messages. This is *NOT* changing the evaluation periods for the DLQ alarms. 
My thinking is: we are going to get occasionally some messages stuck in the SQS queue for a bit longer. We only need to intervene if the system is not able to recover automatically. In other words, a single spike in SQS messages age is not reason for paging. 
- Increasing the evaluation periods for SQS `ApproximateAgeOfOldestMessage` metrics to 3
- mage test:ci
=> Updating evaluation periods for SQS queue threshold

web/__tests__/env.ts, web/scripts/utils.js
For our specs running, we are using the `dotenv` npm module to load some test environmental variables. Unfortunately, lots of us have some values hardcoded and it causes hiccups and flakiness to some test scenarios. This PR introduces `env` variables overrides **just** for our test suite.
Run `AWS_REGION="FOO" npm run test web/src/pages/GeneralSettings/GeneralSettings.test.tsx` and you may witness a failure from snapshot testing since `AWS_REGION` gets overridden by the call site.
``
=> Override `.env` variables for Jest

package-lock.json, package.json, web/src/components/Navigation/ProfileIcon/ProfileIcon.test.tsx, web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx, web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx, web/src/pages/ListRules/ListRulesFilters/DropdownFilters.tsx
This PR replaces `Dropdown` usages that don't relate to menu buttons, with `Popover` which provides a more customized experience to the developer
- Replace `Dropdown` with `Popover`
=> Feat: use pounce's `Popover` for filters

internal/compliance/alert_processor/processor/processor.go
Auto remediations would not fire in the alert suppress window. This is not working as intended; the auto remediations should trigger on a per resource basis regardless of whether alerts are being sent or not. We already have a separate check in place that ensures we don't repeatedly try (and fail) to remediate a failing resource.
This elusive bug has plagued the last few release tests, because it will _sometimes_ work, depending on how many times you try and how long you wait.
- Still attempt auto remediations if auto remediations are enabled and we are in the alert suppress window.
- No testing, but I eyeballed the code really hard to be sure :) I can test if someone really wants me to...
=> Make auto remediations more consistent

deployments/log_analysis.yml, internal/log_analysis/alerts_api/api/api.go
This fixes some missing config in the backport of the [refactor of the alerts api](russ-fix-alerts-api-env-vars)
- Fix env for alerts_api
- mage test:ci
- mage deploy plus created rule + alerts and viewed
- Alex tested patch
=> Fix config issues with recent refactor of alerts_api

internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/models.go, internal/log_analysis/alert_forwarder/forwarder/models_test.go, internal/log_analysis/rules_engine/src/alert_merger.py, internal/log_analysis/rules_engine/tests/test_output.py
Fixing issue with alert merging. Rules Engine was not handling properly rules without alert context method specified. 
- Fixing bug in the issue
- unit tests
- Deploymed master, seen the bug, Deployed fix not seeing it anymore
=> Fixing issue with alert merging

internal/core/custom_resources/resources/log_processor_tables.go, internal/core/custom_resources/resources/map.go
Reverts the physical resource id for the log processor glue custom resource. These ids can never change once used or upgrades will fail.
=> Revert the change to the log processor glue customer resource id

internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go, internal/log_analysis/log_processor/sources/s3_test.go
Sometimes log processor will receive events from unregistered sources. This can happen if e.g. someone has configured bucket-wide SNS notifications but has registered only a subfolder in Panther. 
In those cases it doesn't make sense to fail and retry - just ignore the messages. 
- If we receive messages from unregistered S3 path, log a warning and continue
- Unit test
=> Ignoring S3 files from unregistered sources

internal/compliance/awsglue/awsglue.go, internal/core/custom_resources/resources/cloud_security_tables.go, internal/core/custom_resources/resources/log_processor_tables.go, internal/log_analysis/athenaviews/athenaviews.go, pkg/awsathena/integration_test.go, pkg/awsathena/query.go
These are small changes from previous PR feedback and from the enterprise sync/merge of the change where we removed the custom resource that configured Athena WorkGroups (they are now supported in CF)
- Use `awsutils.IsAnyError()` where appropriate in custom glue resources
- Fix typo in descriptions of new tables
- Remove the optional s3 path in `pkg/awsathena` since this is no longer used now that proper WorkGroups are functional
- mage fmt test:ci
- mage deploy, checked the athena views worked and table meta data
- mage test:integration
=> Minor Athena/Glue Tidies

internal/core/source_api/api/put_integration.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/update_integration_test.go
API prevents creating/updating an s3 integration that doesn't have distinct s3 bucket (and prefix, not user-editable though).
Fixes #1646.
Manual QA
=> Validate S3 bucket (and prefix) are unique among S3 log sources

api/lambda/source/models/api.go, deployments/bootstrap_gateway.yml, deployments/log_analysis.yml, deployments/master.yml, internal/core/custom_resources/resources/clients.go, internal/core/custom_resources/resources/log_processor_tables.go, internal/core/source_api/api/list_logtypes.go, internal/core/source_api/api/list_logtypes_test.go, internal/core/source_api/api/vars.go, internal/core/source_api/apifunctions/apifunctions.go, internal/log_analysis/datacatalog_updater/process/create_tables.go, internal/log_analysis/datacatalog_updater/process/create_tables_test.go, internal/log_analysis/gluetables/gluetables.go, pkg/testutils/awsmocks.go, tools/mage/deploy/deploy.go
This PR removes use of `DeployedLogTables()` and consolidates all the management of Glue tables behind the `datacatalog_updater` lambda.
This refactor is needed in Panther Enterprise to support inclusion of custom logs with Parquet and Snowflake integrations.
There was only 1 use of `DeployedLogTables()` in the custom resource used to update schemas during deployment.
This was replaced by a call to get the deployed logTypes from the source api and then calling the `datacatalog_updater`  to update the related tables. All of the code to update the tables and views had already been moved into the `datacatalog_updater` . One change was added to allow an optional `Sync` flag to kick of a sync of the partitions after the tables and views have been updated.
- update custom resource that manages …
=> Remove use of DeployedLogTables()

web/src/pages/RuleDetails/RuleDetails.test.tsx, web/src/pages/RuleDetails/RuleDetails.tsx
This is an optional one that shows the tabs in a "pseudo" disabled state when no rule errors or rule matches are in place.
- Fetching rule errors and rule matches upon mounting
- Activate the  tabs that have data.
- Added coverage tests.
=> fix: add opacity as indication for active tabs

web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.tsx
Fixes sorting by `status` which does not exist for rules. Instead, this should be sorting on enabled/disabled status.
- Change sorting `status` filter for rules to be `enabled`
- Visually
=> fix: sort rules by enabled/disabled status

web/src/components/forms/RuleForm/RuleFormTestResult/RuleFormTestResult.tsx, web/src/components/forms/RuleForm/RuleFormTestResult/__snapshots__/RuleFormTestResult.test.tsx.snap
Rename dedup() output label to "Dedup String" (on the rule test results UI)
=> Rename "Dedup Message" to "Dedup String"

internal/log_analysis/log_processor/sources/s3_client_cache.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go, internal/log_analysis/log_processor/sources/s3_test.go
Using regional STS endpoint. This gives few benefits: 
- Improved latency
- Support opt-in regions
We are doing this fix also for the snapshot poller: https://github.com/panther-labs/panther/pull/1929
- Using local STS endpoint when getting STS credentials for accessing data in S3 buckets
- mage test:ci
=> Using regional STS endpoint

internal/log_analysis/datacatalog_updater/process/create_tables.go
The Glue Catalog is eventually consistent and if we are too fast the above schema changes will not be visible to Athena
- Add 1 sec delay before creating views
- mage test:ci
=> Mitigate race in creating Athena views

deployments/bootstrap_gateway.yml
- Add `EnforceWorkGroupConfiguration` to the Panther Athena Workgroup to be consistent with Panther Enterprise where we need the Parquet compaction process to override the s3 path
- Add trailing `/` to s3 paths since the console UI enforces that they end in `/`
- mage test:ci
- mage deploy, then checked Athena workgroups in console
=> Tidy config for Athena workgroups

deployments/log_analysis.yml, internal/log_analysis/alerts_api/table/list.go
Found this issue while looking at the code today. This could result in alerts-api returning partial results to the FE. 
According to description: 
```
// The maximum number of items to evaluate (not necessarily the number of matching
// items). If DynamoDB processes the number of items up to the limit while processing
// the results, it stops the operation and returns the matching values up to
// that point, and a key in LastEvaluatedKey to apply in a subsequent operation,
// so that you can pick up where you left off. Also, if the processed dataset
// size exceeds 1 MB before DynamoDB reaches this limit, it stops the operation
// and returns the matching values up to the limit, and a key in LastEvaluatedKey
// to apply in a subsequent operation to continue the operation. For more …
```
=> Fixing ddb filtering

web/src/apollo/createErrorLink.ts, web/src/components/GuardedRoute/GuardedRoute.tsx
Currently when a user gets redirected to the sign-in page, he/she sometimes doesn't get redirected back where he/she was after the sign-in. 
This happens only when a session gets expired and nott when a session doesn't exist at all. This PR fixes that
- Maintain location referrer state accross redirects
- maintain/restore `search` and `hash` params on the redirect URL
- Manually
=> fix: broken redirect after sign-in

web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
The mini-graph below all charts are displayed in reverse. The cause of this is that `seriesData` are coming from backend in descending timestamp order. While that didn't affect charts cause they are ordered on charts based on timestamp, echarts dont seem to apply the same logic on the mini-chart.
This PR fixes the issue (check before & after screenshot below), the alternative would be to change the API so that it returns data in ascending order.
- Reversed data before passing it to echart
- Locally
=> fix: reverse mini-chart for TimeSeries charts

internal/compliance/resource_processor/processor/analysis_api.go, internal/log_analysis/log_processor/common/common.go, internal/log_analysis/log_processor/processor/processor.go, internal/log_analysis/log_processor/processor/processor_test.go, internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
Sometimes we mis-detect gzipped log files as ms-fontobject.
Change the detection code to check directly for the gzip signature instead of relying on the `http.DetectContentType` function. That function checks for many content types and produces a false positive in some cases.
- Unit
=> Fix gzip files being mis-detected as ms-fontobject

internal/compliance/resource_processor/processor/analysis_api.go, internal/log_analysis/log_processor/common/common.go, internal/log_analysis/log_processor/processor/processor.go, internal/log_analysis/log_processor/processor/processor_test.go, internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
Sometimes we mis-detect gzipped log files as ms-fontobject.
Change the detection code to check directly for the gzip signature instead of relying on the `http.DetectContentType` function. That function checks for many content types and produces a false positive in some cases.
- Unit
=> File detection

api/gateway/analysis/api.yml, api/gateway/analysis/models/data_model.go, api/gateway/analysis/models/update_data_model.go, internal/core/analysis_api/handlers/create_datamodel.go, internal/core/analysis_api/handlers/dynamo.go, internal/core/analysis_api/handlers/modify_datamodel.go
Add DisplayName to DataModel, similar to Rules/Policies. This allows users to change the default name displayed with various DataModels. 
- Added new `DisplayName` field to `UpdateDataModel` object
=> add displayName to data models

internal/log_analysis/log_processor/parsers/cloudflarelogs/cloudflarelogs.go, internal/log_analysis/log_processor/parsers/cloudflarelogs/firewall.go, internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request.go, internal/log_analysis/log_processor/parsers/cloudflarelogs/spectrum.go, internal/log_analysis/log_processor/parsers/cloudflarelogs/testdata/cloudflare_tests.yml
Cloudflare allows users to select which fields should be included
in the events, meaning we can't arbitrarily tag fields as required.
Keeps only 1 timestamp field as required for every Cloudflare log type.
- unit tests
=> Keep only 1 required field for each Cloudflare log type

deployments/bootstrap_gateway.yml
Every time we upgrade Panther, we get a handful of `WARN` messages logged by the `panther-cfn-custom-resources` lambda function (see below for examples). Since we're seeing these for every deployment, we're getting paged on every upgrade. I have increased the threshold from 1 to 10 to prevent these pages.
This particular  `WARN` alarm had overwritten the default threshold of I believe 15, and explicitly set it to 1. But there were no comments/documentation on why this was set this way, so I wasn't sure if we were good to increase it. But since we apparently aren't getting any good signal out of it at it's current level, I decided to bump it.
- Changed the `WARN` threshold for the custom lambda alarms resource for the `panther-cfn-custom-resources` lambda from 1 to 10
- None
This change is …
=> Bump warn threshold for custom resources lambda

api/graphql/schema.graphql, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/codegen.yml, web/codegen/buildGraphqlResourcesPlugin.js, web/codegen/buildGraphqlResourcesPlugin.ts, web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx, web/src/pages/LogAnalysisOverview/AlertsBySeverity/AlertsBySeverity.tsx, web/src/pages/LogAnalysisOverview/AlertsCharts/AlertsCharts.tsx, web/src/pages/LogAnalysisOverview/EventsByLatency/EventsByLatency.tsx, web/src/pages/LogAnalysisOverview/EventsByLogType/EventsByLogType.tsx, web/src/pages/LogAnalysisOverview/LogTypeCharts/LogTypeCharts.tsx, web/src/pages/LogAnalysisOverview/graphql/getLogAnalysisMetrics.generated.ts, web/src/pages/LogAnalysisOverview/graphql/getLogAnalysisMetrics.graphql
Currently, we use `Int` and `Float`  as GraphQL scalars whenever we want to depict a numerical value. AppSync uses an 32bit `Int` and `Float` JavaLang representation under the hood, causing some big values ( > 2,000,000,000) to crash our system.
This hasn't been identified so far, because our test data didn't come near to those numbers. AppSync doesn't have any publicly documented scalars (other than `Int` and `Float`) and it doesn't allow you to specify your own custom scalars. The need for a `Long` type has been heavily requested [for more than a year](https://github.com/aws/aws-appsync-community/issues/21), but so far there haven't been any updates from AWS.
Due to the fact that AppSync uses Java under the hood (that's why it can parse VTL templates as well), I took advantage of that …
=> GraphQL: Use undocumented `Long` scalar

internal/core/alert_delivery/outputs/opsgenie.go, internal/core/alert_delivery/outputs/opsgenie_test.go, internal/core/alert_delivery/outputs/utils.go, internal/core/outputs_api/api/utils.go
Default value for opsgenie service region is wrong. This PR fixes it and assigns it the value `US`
- refactor utility function name
- correct default opsgenie service region value
`mage test:go`
=> fix: opsgenie default value

internal/core/outputs_api/api/utils.go
Creating an Opsgenie EU config works; however, upon refreshing the page the config shows it was set for the US region. This is because the check had a bug and overwrote the region to always be "US".
- return "US" iff the region was an empty string ("")
- N/A
=> Opsgenie incorrect region display

internal/compliance/aws_event_processor/processor/elbv2.go, internal/compliance/aws_event_processor/processor/rds.go, internal/compliance/aws_event_processor/processor/waf-regional.go, internal/compliance/snapshot_poller/pollers/aws/awstest/eks.go, internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go, internal/compliance/snapshot_poller/pollers/aws/eks_cluster_test.go
Fix two bugs reported in Cloud Security scanning systems.
The first bug was in scanning EKS clusters. We require new permissions for the audit role to scan these systems, so we updated the `PantherAuditRole`. In order to be backwards compatible, we capture permission denied errors on the relevant API call and keep scanning. Unfortunately this was not implemented correctly, so we were still logging permission denied errors when scanning EKS clusters.
The second bug is a weird one. The snapshot-poller received several requests to scan a resource of type `ELBV2.LoadBalancer` with the arn `arn:::::`. Clearly this is incorrect, so I checked the `aws-event-processor` logs and it logged some `WARN`s that it had found and extracted an invalid ARN out of a few CloudTrail logs it was processing …
=> Minor polling fixes

internal/log_analysis/log_processor/processor/stream.go, internal/log_analysis/log_processor/processor/stream_test.go
Currently the log processor pulls a lot of events through SQS, processes them, and if everything has succeeded, the messages are deleted from the SQS queue. However if any of the following errors occur, the FULL BATCH will fail and all of the messages will be reprocessed. 
The failures can occur: 
1. Polling new messages from SQS queue
2. Accessing the S3 objects & reading first chunk of the S3 objects
3. Reading the full S3 objects
4. Writing to the output
With this PR, I make sure that failures No1, and No2 don't cause the batch to fail. No3 and No4 could be addressed in separate PR and are indeed more complicated. They are also less common - especially No2 can happen very frequently in case of permissions misconfiguration.
- See above
- Updated flaky test
- Unit tests
=> Don't fail the full batch in case of partial failures

internal/core/analysis_api/handlers/list.go, internal/core/analysis_api/handlers/list_data_models.go, internal/core/analysis_api/handlers/list_policies.go, internal/core/analysis_api/handlers/list_rules.go
#2087 broke `ListPolicies` and `ListDataModels`. Both the backend and the web app started reporting `analysis-api` panics with the message "unexpected SortBy: "
The problem was that we changed how the list operations handle the default sortBy when none is specified: it used to be handled as the default in a switch statement, but now we expect each List handler to provide their own defaults.
This error would have been caught when running integration tests for #2087 , but I forgot to have Alex run those, so that's my bad.
- Add default `sortBy` for policies and data models
- Deployed, verified fix to policy list page in the web app
- CloudWatch alarms for `analysis-api` and `resource-processor` were resolved after the fix
- @AlexPanther is working on fixing the `analysis-api` integration …
=> Add default sortBy for policies and data models

web/src/components/charts/TimeSeriesChart/ChartTooltip.tsx, web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx, web/src/components/charts/TimeSeriesChart/index.tsx
This PR corrects a few edge cases with the rendering of a `TimeSeriesChart`, as well as its Tooltip
- Make `units` optional within tooltip
- Merge typings into something exportable
- Fix edge cases with absolute positioning
=> Fix: visual bugs & issues with TimeSeriesChart

tools/mage/master/deploy.go
We now support publishing Panther to EU regions. I already manually published 1.12.1 to those regions, so we need to get the new regions into 1.13 as well.
This is a PR directly against the release branch; the associated change in `master` is already in #2096
Please merge on approval
- Add `eu-west-1` and `eu-central-1` to the region publication set for `mage master:publish`
- `mage master:publish` for 1.12.1
=> Add EU regions for publishing

internal/log_analysis/awsglue/wrappers.go
`@message	
failed to create databases: AlreadyExistsException: Database already exists.; AlreadyExistsException: Database already exists.; AlreadyExistsException: Database already exists.; AlreadyExistsException: Database already exists.; AlreadyExistsException: Database already exists.: withStack
null`
Current setup prevents successful check of EnsureDatabase by returning an error if "database already exists" error is returned, which is not what we want. 
Replaced err with nil in the EnsureDatabase function
- Deployed branch, no errors
=> Fix bug that prevented successful check of EnsureDatabase()

internal/log_analysis/awsglue/glueschema/glueschema.go, internal/log_analysis/awsglue/glueschema/glueschema_test.go
Some changes to `glueschema` were required during sync. Backport them so code is in sync.
- Adds `glueschema.InferColumnsCustom`
- mage test:go
=> Backport glueschema.InferColumnsCustom

internal/log_analysis/log_processor/pantherlog/meta.go, internal/log_analysis/log_processor/pantherlog/scanners.go, internal/log_analysis/log_processor/pantherlog/scanners_test.go
This PR is related to #1321
- Adds `username` indicator scanner and field
- Adds `email` indicator scanner and field
- Adds `username` tag to `AWS.CloudTrail`
- mage test:go
=> Add `username` and `email` indicators to `pantherlog`

internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go, internal/log_analysis/log_processor/parsers/duologs/administrator.go, internal/log_analysis/log_processor/parsers/duologs/authentication.go, internal/log_analysis/log_processor/parsers/duologs/duologs.go, internal/log_analysis/log_processor/parsers/duologs/duologs_test.go, internal/log_analysis/log_processor/parsers/duologs/offline_enrollment.go, internal/log_analysis/log_processor/parsers/duologs/telephony.go, internal/log_analysis/log_processor/parsers/duologs/testdata/duologs_test.yml, internal/log_analysis/log_processor/registry/init.go
Add parsers for Duo logs.
https://duo.com/docs/adminapi#logs
- Add parsers for Duo authentication (v2), administrator, telephony logs.
-  Unit
=> Add parsers for Duo logs

web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.test.tsx, web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.tsx, web/src/pages/ListLogSources/LogSourceCards/SqsLogSourceCard.test.tsx, web/src/pages/ListLogSources/LogSourceCards/SqsLogSourceCard.tsx
During the latest refactor of log source cards, we added `lastEventReceived` information to the top right corner but we left out the pre-existing field displaying this info on cards for S3 & SQS
Closes #2146 
-  Removed `lastEventReceived` field from card body
- Updated tests
- Locally
=> Removed lastEventReceived from S3 & SQS card

internal/compliance/aws_event_processor/processor/rds.go
The `aws-event-processor` processes AWS CloudTrail logs and determines if scans need to happen as a result of these logs. Part of the responsibility of the `aws-event-processor` is to extract the `resourceID` (typically the ARN) of the resource being changed and include that in the scan request.
For certain AWS RDS instance related events, the instance ID may not be present in the log if the instance no longer exists.  This is common, for example, when changes happen to RDS instance snapshots of instances that no longer exist.
We were previously passing along these "blank" arns that were causing issues in the `panther-snapshot-poller`.  This change extends some validation of the instance ID extraction to all branches when evaluating RDS Instance related events.
Discovered while …
=> Validate instance IDs exist before sending

deployments/core.yml
The `source-api` is now using versioned aux templates, but the version being used is the `CUSTOM_RESOURCE_VERSION` CloudFormation parameter, which was not designed for this purpose. This has different values when doing `mage deploy` vs `mage master:deploy`. For a VERSION file which contained "v1.13.0-RC" as the base version:
* `mage deploy` was setting `v1.13.0` as the CUSTOM_RESOURCE_VERSION because of a string split on `-`
* `mage master:deploy` uses the full version string `v1.13.0-RC-(branch)-(commit)`
Neither of these are correct - the template version comes from the VERSION file, so it should have been `v1.13.0-RC`
----
The quick fix for right now is to literally just hardcode the version in the `source-api` environment.
Longer term fixes in progress:
* I will put up a PR to use …
=> Hardcode source-api version

internal/log_analysis/alert_forwarder/forwarder/forwarder.go, internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go, internal/log_analysis/rules_engine/src/engine.py, internal/log_analysis/rules_engine/tests/test_engine.py
Closes https://github.com/panther-labs/panther/issues/2169
Updated Rule errors to use the same dedup period as the Rule matches (instead of hardcoded 24h)
- mage test:ci
- Deployed and verified E2E
=> Fixes Rule Errors threshold and dedup period

api/lambda/analysis/models/api.go, api/lambda/analysis/models/data_models.go, api/lambda/analysis/models/globals.go, api/lambda/analysis/models/policies.go, api/lambda/analysis/models/rules.go, internal/core/analysis_api/handlers/list.go, internal/core/analysis_api/handlers/list_data_models.go, internal/core/analysis_api/handlers/list_policies.go, internal/core/analysis_api/handlers/list_rules.go, internal/core/analysis_api/handlers/list_test.go, internal/core/analysis_api/main/integration_test.go
Our release QA revealed a few bugs with the `analysis-api`, which isn't that surprising since we removed the analysis-api gateway in this release.
Fortunately, the fixes are small and easy
- Do not require userIDs to be UUID4s: they just need to be non-empty
- In the community edition, userIDs happen to always be uuids, but that's not always true in enterprise
- Updated the integration test with a non-uuid userID as a regression test
- ID filtering is now correctly case-insensitive
- We were lowercasing the display name search, but not the ID search
- Related minor performance improvement: when sorting by display name / ID, we can use the existing dynamo columns "LowerID" and "LowerDisplayName" to avoid having to recompute the lowercase string on each comparison
- Deployed to dev account, …
=> Fix uuid validation and case-insensitive filtering

web/src/components/GenericItemCard/GenericItemCard.tsx, web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
The Color of the date on the Cards is not correct, but the correct one is not in our palette. After speaking with @dimitriszoitas we agreed to use `navyblue-200`
- Change color of "date" on cards to `navyblue-200`
=> fix: date color on generic item card

deployments/web_server.yml, tools/mage/deploy/frontend.go, tools/mage/master/build.go, tools/mage/master/deploy.go, tools/mage/master/publish.go
The v1.14 release adds publishing support for 15 different AWS regions! We tried to publish the regions in parallel, but both @s0l0ist and I ran into issues with "Content-MD5 mismatch" or "docker credential failure"
So, we have to revert to sequential region publishing. However, to compensate, I've added the ability to specify which regions you want to publish. For release testing, for example, we don't need to publish all 15 regions, which can take quite awhile.
- `mage master:publish`
> 17:49:15	INFO	[master:publish]	Publishing panther-community 1.14.0-RC to ca-central-1, ap-northeast-2, eu-north-1, eu-west-1, eu-west-2, us-west-1, ap-northeast-1, ap-southeast-1, ap-southeast-2, us-east-1, us-east-2, us-west-2, ap-south-1, eu-central-1, eu-west-3, …
=> Revert to sequential publishing

internal/log_analysis/log_processor/parsers/awslogs/guardduty.go
All non-required fields for a parser need to be declared `omitempty` else Parquet conversion fails.
- Update GuardDuty parser to use omit empty on non-required fields
=> Update GuardDuty parser to use omit empty on non-required fields

deployments/bootstrap_gateway.yml
The stack was not applying tags to the Athena Work Group. This is needed for accurate billing reporting.
- Explicitly add Application:Panther tag to Athena workgroup
- mage deploy, checked tags present.
=> Explicitly add Application:Panther tag to Athena workgroup because stack is not applying

deployments/master.yml, deployments/panther_config.yml
AWS raised the max lambda size to 10240. This PR updates our limits for the log processor.
- Up limits in master template and panther_config.yml
- mage deplooy
=> Raise log processor lambda size limits since AWS has raised maximum

internal/compliance/resources_api/handlers/delete_resources.go
During delete  "resource no longer exists" errors were logged at warn level but this creates alarms when we get spikes of warnings above threshold.
- Change "resource no longer exists" log from Warn() to Debug()
=> Change "resource no longer exists" log from Warn() to Debug()

package-lock.json, package.json
Snyk re-reported a vulnerability with the patch version it recommended. This PR bumps the patch version of `ua-parser-js` once more.
- bump to latest patch version of `ua-parser-js`
- CI:
- `npm audit`
- snyk CI checks
=> security: bump ua-parser-js

build/images/ci/Dockerfile
Updates the docker build image to use node `v14.15.1`
- change the version string
- the URL download works with the specified version
=> fix: ci image update node

internal/core/alert_delivery/outputs/asana_test.go, internal/core/alert_delivery/outputs/custom_webhook_test.go, internal/core/alert_delivery/outputs/github_test.go, internal/core/alert_delivery/outputs/jira_test.go, internal/core/alert_delivery/outputs/msteams.go, internal/core/alert_delivery/outputs/msteams_test.go, internal/core/alert_delivery/outputs/opsgenie_test.go, internal/core/alert_delivery/outputs/outputs.go, internal/core/alert_delivery/outputs/outputs_test.go, internal/core/alert_delivery/outputs/pagerduty_test.go, internal/core/alert_delivery/outputs/slack_test.go, internal/core/alert_delivery/outputs/sns_test.go, internal/core/alert_delivery/outputs/sqs_test.go
Previously, alerts generated by policies were including a URL that was the sending the user to the `AnalysisID` or policy details page because there was no supporting _alert_ details page for these types of alerts.
This PR ensures all alerts will have the same URL to direct the user to the respective alert details pages.
- `return alertURLPrefix + *alert.AlertID` for all alerts regardless of the alert type
- Manually
- mage test:go
=> fix: return alertId when generating the URL

internal/log_analysis/alerts_api/api/get_alert.go, internal/log_analysis/alerts_api/utils/utils.go
UI would crush trying to list policy alerts. Fixing this. 
The code currently tries to fetch Rule information even when the user accesses/lists an alert related to a Policy. This needs to be addressed properly. In the meantime, putting a quick fix here. 
- deployed and verified it works properly.
=> Fixing bug that would result in crushing of the UI

web/__tests__/setupTests.ts
Jest now times out at over 1 minute, but our testing library still has a max-await of 1 second. This PR increases the timeout of our testing library to 10 seconds within CI environments
- Increase timeout of testing library
- Forced a fail and waited until the test timed out. The timeout occurred 1 min later
=> fix: web test timeout

web/src/pages/AlertDetails/RuleAlertDetails/RuleAlertDetails.tsx
When moving to policy-based alerts, the GraphQL structure changed and we introduced more "parent" objects to the alert's `events` key. Because of the fact that our GraphQL library isn't 100% strongly typed, we missed a modification that was affecting endless pagination on alert's events.
This PR fixes that
- Fix issue where the paginated events were not being properly merged with the existing ones
- Enforce strong types on pagination params
- Manually
=> fix: correct deep merging on alert's events

deployments/Dockerfile
I've spent hours trying to publish the 1.14.3 release, and no matter what I try it always fails at the last step:
```
Step 17/19 : RUN npm install express express-static-gzip ejs chalk dotenv
---> Running in d8b2a87ddd07
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/escape-html failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-17T23_54_16_068Z-debug.log …
```
=> Upgrade web image to node14

internal/compliance/snapshotlogs/compliance.go, internal/compliance/snapshotlogs/resource.go, internal/compliance/snapshotlogs/testdata/snapshot_tests.yml, internal/log_analysis/gluetables/gluetables.go, internal/log_analysis/log_processor/destinations/s3_test.go
- Change cloudsec history table names to `panther_cloudsecurity.resouce_history` and `panther_cloudsecurity.compliance_history`
- Generalize function `LogTypeTableMeta()`
- mage test:ci
- mage deploy + Athena queries
=> Change cloudsec history table names

internal/log_analysis/alerts_api/main/lambda.go
It seems that the code was wrapping errors always in InternalError. This is not correct though: The error could be e.g. a input validation error
- mage test:ci
=> Don't wrap error in internal error

cmd/opstools/s3sns/s3sns.go
Updating S3SNS tool to support CloudSecurity
- Support Cloud Security log types
- uses the tool to send notifications for CloudSecurity data
=> Updating S3SNS tool to support CloudSecurity

internal/log_analysis/log_processor/logtypes/entry.go, internal/log_analysis/log_processor/pantherlog/meta.go, internal/log_analysis/log_processor/pantherlog/meta_test.go
We need a way to define extra indicators from values implementing `pantherlog.ValueWriter` interface to be included in generated schemas.
- Adds `ExtraIndicators` field to `logtypes.ConfigJSON` field
- Fixes a bug with multiple indicator fields during schema inference.
- mage test:go
=> Add 'ExtraIndicators' field to the ConfigJSON struct

deployments/bootstrap.yml, deployments/log_analysis.yml, internal/core/custom_resources/resources/alarms_lambda.go
The max size (I thought) I fixed earlier but it seems to have been put back to 3008. Lambda now allows 10240. Master stack has this correct.
- Change max in log process CF and in the alarm generation code.
- mage test:ci
- benchmarks using large lambdas
=> Update max lambda size to 10240

package-lock.json, package.json
We use Amplify for its `Auth` package. Amplify internally uses  `axios`  which recently had a reported vulnerability. Amplify has since fixed the package, but no release has yet been cut. Even if it did,  we'd require a backport, since we are using `v2.x.x.` while Amplify is on `v3.x.x`.
Until all that happens, we manually forced Amplify to  use `v0.21.1` of axios instead of the current `v0.19.0`. Went through  axios' [changelog](https://github.com/axios/axios/blob/hotfix/0.21.1/CHANGELOG.md) and didn't see any breaking changes.
This will fix our `npm audit` issue for now and we'll upgrade to Amplify's patch version as soon as it becomes available
- Force all axios resolutions to latest `v0.21.1`
- `npm audit`
=> fix: axios issue from AWS Amplify

internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_main.py, internal/log_analysis/rules_engine/tests/test_rule.py
Changing name from `destination_overrides` to `destinations` according to this discussion: https://github.com/panther-labs/panther/pull/2165#discussion_r534324500
It seems that this feature was not released officially in 1.14, so we get some time to fix names like this
- Updated name of method
- mage test:python
=> Change name of destination functions

package-lock.json, web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.test.tsx, web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.tsx
There was a remnant from S3 refactor in `S3LogSourceCard` related to S3Prefixes. 
We decide to remove the display of the S3 prefix from that card for the moment.
Closes #2323
- Remove S3 prefix field from `S3LogSourceCard`
- Update test
- Update package-lock.json
- Locally
=> Removed s3Prefix from S3LogSourceCard

internal/log_analysis/log_processor/destinations/s3.go, internal/log_analysis/log_processor/destinations/s3_test.go
Closes #2179 
* Fixing flaky test: TestSendDataIfTimeLimitHasBeenReached
* It was possible for S3 destination to block indefinitely while waiting for new events to become available from the parsers and wouldn't flush buffers on schedule. Fixed.
* Updating behavior of S3 destination so that if it has encountered a failure, we no longer try to flush buffers to S3. 
- mage test:ci
=> Fixing flaky test and few S3 destination bugs

internal/log_analysis/log_processor/parsers/slacklogs/integrationlogs.go, internal/log_analysis/log_processor/parsers/slacklogs/slacklogs.go, internal/log_analysis/log_processor/parsers/slacklogs/testdata/slacklogs_test.yml
Add parser to support Slack integration logs https://api.slack.com/methods/team.integrationLogs
- Add parser to support Slack integration logs
- Unit
=> Add Slack integration logs parser

web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx, web/src/pages/AlertDetails/PolicyAlertDetails/PolicyAlertDetails.tsx, web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx, web/src/pages/AlertDetails/RuleAlertDetails/RuleAlertDetails.tsx
When a rule is deleted you are expected to be able to still see the alerts that this rule has generated. This used to work, but in the previous sprint we modified some code and now it doesn't. This PR fixes that.
- Allow rendering of Alert when associated Rule or Policy has been deleted
- Locally
=> fix: issue where alert wouldn't render if rule got deleted

internal/core/analysis_api/handlers/list_rules.go
The `ListRules` endpoint currently drops the `LogTypes` filter entirely (ignoring it). This fix just passes that filter through.
- Pass `LogTypes` filter through when calling `ListRules`
- Deployed to dev env and tested manually
=> Pass through Log Types filter

deployments/auxiliary/cloudformation/panther-stackset-execution-role.yml, deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml
The stackset roles only work if you deploy the stackset admin role in the same account and region as Panther. This updates the stackset admin role so it is not region dependent (but remains backwards compatible) and adds a new standalone stackset execution role for users who don't want to have panther be the stackset admin accout.
- Created new optional standalone stackset execution role
- Updated new stackset admin role to not have to be deployed in the same region as Panther
- Deployed the stackset admin & execution role templates into my dev account and validated I could use them
- Deployed the stackset admin role without specifying a region and verified it behaved as it did previously (backwards compatibility)
=> Update stackset roles

tools/mage/master/deploy.go
My release testing failed when I tried to upgrade a v1.14.3 stack to v1.15.0-RC. Turns out I had deployed the root stack with a non-traditional name, but `STACK=my-stack-name mage master:deploy` did not work as it should have - `mage` still passed the default `panther` stack name instead of the one I specified in the environment.
- Correctly pass STACK environment variable to the deploy code
- Searched for all references to the default stack name to make sure there were no other places that were using it
- Release upgrade testing (ongoing)
=> Pass stack name correctly during master:deploy

web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
Fix typo in placeholder word.
- Change placeholder in the corresponding `tsx` file.
- `mage test:web`
=> Fix placeholder text in Rule Create/Edit form Log Type dropdown

api/lambda/analysis/engine.go, internal/core/analysis_api/analysis/rule_engine.go
Related to some issues discovered when debugging the FE implementation. 
The analysis-api test record expects a string to be returned from DDB for the destinationsOutput, however it will return a string set (since that's what the rules-engine will store in DDB)
- Changed analysis-api model destinationsOutput field to be `[]string`
- Patched the `buildTestSubRecord` for `Destinations` with `buildTestSubRecordList` which handles the case of 
- Deployment and manual testing in `us-east-1`
=> Generated Alert Fields - Destinations Fix

.gitignore, internal/log_analysis/log_processor/parsers/awslogs/awslogs.go, internal/log_analysis/log_processor/parsers/awslogs/testdata/waf_web_acl_tests.yml, internal/log_analysis/log_processor/parsers/awslogs/waf_web_acl.go, internal/log_analysis/log_processor/parsers/awslogs/waf_web_acl_test.go
Enable log parsing for [AWS WAF Web ACL](https://docs.aws.amazon.com/waf/latest/developerguide/logging.html).
Addresses https://github.com/panther-labs/panther/issues/2341.
- Define new log parser `struct` `WAFWebACL` along with nested object `struct` definitions.
- Register the new parser in `internal/log_analysis/log_processor/parsers/awslogs/awslogs.go`.
- Add a list of test cases specified in #2341, in YAML format.
- New log type is available on Panther frontend for selection.
- Rule Engine:
* Composed a rule that checked for specific log event values.
* Send HTTP requests that were blocked by WAF rule.
* Alert was triggered in Panther. 
- Verified log processing by inspecting Lambda Cloudwatch Logs.
- Verified AWS Glue Data Catalog registration by running sample Athena queries.
=> Introduce AWS WAF Web ACL log parser

web/src/components/forms/TotpForm/TotpForm.tsx
While most QR Code scanners can read an inverted Code, some apps are not able to scan them.
To make sure that our QR Code is scannable, we have to stick with a light colored background and dark foreground.
- Invert the colors of the QR code.
- Add margin to the QR code for easier detection.
Closes #1740
=> Standardize mfa qr code

internal/compliance/snapshot_poller/models/aws/types.go, internal/compliance/snapshot_poller/pollers/aws/configservice.go, internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go, internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go, internal/compliance/snapshot_poller/pollers/aws/password_policy.go, internal/compliance/snapshot_poller/pollers/aws/poll.go, internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go
Addresses the remaining issues from https://github.com/panther-labs/panther/pull/2361 that were unaddressed.
- Added the regex compile to run immediately after the instantiation of `pollerResourceInput` as well as an error check
- Removed err from `ShouldIgnoreResource` and updated the callers
=> CloudSecurity Filtering and Ignore List Options - Post Fix

internal/compliance/snapshot_poller/models/aws/types.go, internal/compliance/snapshot_poller/pollers/aws/configservice.go, internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go, internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go, internal/compliance/snapshot_poller/pollers/aws/password_policy.go, internal/compliance/snapshot_poller/pollers/aws/poll.go, internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go
Addresses the remaining issues from https://github.com/panther-labs/panther/pull/2361 that were unaddressed.
- Added the regex compile to run immediately after the instantiation of `pollerResourceInput` as well as an error check
- Removed err from `ShouldIgnoreResource` and updated the callers
=> [SYNC] CloudSecurity Filtering and Ignore List Options - Post Fix

package-lock.json, package.json, web/src/components/fields/DateRangeInput/DateRangeInput.test.tsx, web/src/pages/ListAlerts/ListAlerts.test.tsx
Update pounce to the latest version to fix the inconsistent dates in the date range picker.
Update pounce to v0.80.1.
- npm run test
- Manually tested date range picker
=> Update pounce version

internal/compliance/aws_event_processor/processor/elbv2.go, internal/compliance/aws_event_processor/processor/process.go, internal/compliance/snapshot_poller/pollers/aws/clients.go
This PR fixes one major and three minor bugs related to Cloud Security scanning found during on call.
- Add several events to the `aws-event-processor` ignore list that were causing hiccups in the `aws-event-processor`
- elb `RegisterInstancesWithLoadBalancer`, `ConfigureHealthCheck`, `SetLoadBalancerPoliciesOfListener`, and `CreateLoadBalancerPolicy` are all elb classic events. We don't support elb classic, but are unable to differentiate between elb classic and elbv2 events explicitly. These were causing `warn` messages.
- lambda `InvokeExecution`. Processing this API call raised errors when trying to extract the account ID. Luckily this event does not indicate to us that we need to scan, as no infrastructure is changing.
- Added special error handling to the elb …
=> Fixes for ELBV2 scanning

api/graphql/schema.graphql, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/graphql/fragments/AlertDetailsFull.generated.ts, web/src/graphql/fragments/AlertDetailsFull.graphql, web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/AlertDetailsInfo.test.tsx, web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx, web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/__snapshots__/AlertDetailsInfo.test.tsx.snap
Users are able to dynamically override data for an alert generated by a rule (such as description, reference, etc.), but  - up until now - those weren't showcased in the UI, since we always showed the values that the rule had.
This PR fixes it, by making sure that all dynamic fields originate from the alert item itself.
Closes #2482
Closes #2166 
- Add missing fields to schema
- Use new fields in Alert Details page
All dynamic fields **automatically** fallback to the values that the rule has, so no need to add a fallback in the UI ourselves
=> [FE] Showcase dynamic alert field in details page

internal/core/source_api/api/list_integrations.go, internal/core/source_api/api/list_integrations_test.go
Due to a previous bug, a deleted integration could be re-created in the DB without the `IntegrationType` field. This would break Panther in many places in addition to breaking Panther upgrades. 
- The `ListIntegrations` endpoint in source-api now doesn't return sources that don't have a valid `IntegrationType` field.
- unit
=> source-api: Don't return sources without populated IntegrationType

web/src/components/modals/DeleteCustomLogModal/DeleteCustomLogModal.tsx
When deleting a Custom Log item, we remove the item from the list even when the BE has returned an error. This removes the custom log from the UI but doesn't restore it back unless the user refreshes.
This PR addresses that
- Check for BE errors before removing a Custom log from the UI
=> [FE] Fix custom log modal deletion

internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_rule.py
Closes #2515
- Allow users to return object from `alert_context` method
- mage test:ci
- E2E after deploying to my account and defining a rule:
```
def rule(event): 
return True
def alert_context(event): 
return event
```
=> Allow users to return event from alert_context

internal/core/source_api/api/put_integration.go, internal/core/source_api/api/update_integration.go
Allowing an s3 source to be saved even if healthcheck fails will enable many improvements down the road, like enabling users to manage Panther sources-as-code, bulk create sources and faster source onboarding.
- Allow s3 source to be saved (during creation or update) even if healthcheck fails
- Manual QA
=> source-api: Allow saving s3 source even if healthcheck fails

api/graphql/schema.graphql, internal/log_analysis/rules_engine/src/rule.py, internal/log_analysis/rules_engine/tests/test_rule.py, web/__generated__/schema.tsx, web/src/components/cards/RuleCard/RuleCard.tsx, web/src/components/cards/RuleCard/RuleCardOptions/RuleCardOptions.tsx, web/src/components/forms/RuleForm/RuleFormCoreSection/RuleFormCoreSection.tsx, web/src/components/modals/DeletePolicyModal/DeletePolicyModal.tsx, web/src/components/modals/DeleteRuleModal/DeleteRuleModal.tsx, web/src/graphql/fragments/PolicyDetails.generated.ts, web/src/graphql/fragments/RuleDetails.generated.ts, web/src/hooks/useDetectionDestinations.tsx, web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx, web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap, web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx, web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap, web/src/pages/EditPolicy/graphql/updatePolicy.generated.ts, web/src/pages/ListPolicies/ListPoliciesTable/ListPoliciesTableRowOptions/ListPoliciesTableRowOptions.tsx, web/src/pages/PolicyDetails/PolicyDetailsBanner/PolicyDetailsBanner.tsx, web/src/pages/PolicyDetails/PolicyDetailsInfo/PolicyDetailsInfo.tsx, web/src/pages/PolicyDetails/graphql/getPolicyDetails.generated.ts, web/src/pages/PolicyDetails/graphql/getPolicyDetails.graphql, web/src/pages/RuleDetails/RuleDetailsBanner/RuleDetailsBanner.tsx
This PR backports minor but necessary changes from Scheduled Rules feature, back to the OSS
[Related Enterprise PR](https://github.com/panther-labs/panther-enterprise/pull/2043)
- Update typings
- Mark GraphQL fields as required
- Add `flexWrap="wrap"` to propery losts
- Add `Detection Type` in detection banners
`npm run test`
=> [FE] Backport UI changes from Enterprise

api/lambda/analysis/models/api.go, internal/core/analysis_api/handlers/delete.go
Add a DeleteDetections endpoint.
- Add DeleteDetections
- Manually tested in dev account. This deleted a rule and a policy:
```
{
"DeleteDetections": {
"entries": [
{
"id": "AWS.CloudTrail.RootFailedConsoleLogin"
},
{
"id": "AWS.ACM.Certificate.Valid"
}
]
}
}
```
=> Add DeleteDetections endpoint

internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs.go, internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs_test.go, internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go, internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity_test.go, internal/log_analysis/log_processor/parsers/crowdstrikelogs/testdata/identity.yml, internal/log_analysis/log_processor/parsers/crowdstrikelogs/unknown.go
These events are significant during investigation. Specifying a custom parser facilitates querying, since the `Unknown` parser doesn't generate structured records.
- Define parser for [`GroupIdentity` event](https://developer.crowdstrike.com/crowdstrike/page/event-explorer#section-event-GroupIdentity) (applicable only to Mac platform) and [`UserIdentity` event](https://developer.crowdstrike.com/crowdstrike/page/event-explorer#section-event-UserIdentity).
- `mage test:go`
=> CrowdStrike parsers: UserIdentity & GroupIdentity

internal/core/analysis_api/handlers/list_data_models.go, internal/core/analysis_api/main/integration_test.go
Bug in sorting of data models, was not taking into account the input `sortBy`
- add sortby to the sort call
- Sorting integration tests
- `mage test:integration`
- manual testing
=> fix issue with sortby in data models

deployments/appsync.yml
When merging policies & rules page together, we removed the `listRules` and `listPolicies` GraphQL queries from the schema, since they were not longer needed. 
Unfortunately, we forgot to remove their related resolvers, causing AppSync to crash. This PR fixes just that.
- Remove stale appsync resolveers
- App can be deployed
This wasn't caught since the GraphQL queries were removed during PR feedback in which case, I personally forgot to re-deploy (since I didn't expect any errors).  What went wrong was optimistically assuming that there would be no side-effects. Guess that's not gonna happen again!
=> [FE][BUGFIX] Remove stale appsync resolvers

internal/compliance/snapshot_poller/pollers/aws/awstest/elbv2.go, internal/compliance/snapshot_poller/pollers/aws/elbv2_application_load_balancer.go, internal/compliance/snapshot_poller/pollers/aws/elbv2_application_load_balancer_test.go
Calling `GetWebAclForResource` on network load balancers will raise `WAFInvalidParameterException`. This change will check for for the lb type before calling `GetWebAclForResource`
- check for lb type
- added unit test for network type
- `mage test:go`
=> bugfix: check for lb type

web/src/components/cards/AlertCard/PolicyAlertCard/PolicyAlertCard.tsx, web/src/components/cards/AlertCard/RuleAlertCard/RuleAlertCard.tsx, web/src/components/utils/SelectContext/SelectAllCheckbox.tsx, web/src/components/utils/SelectContext/SelectCheckbox.tsx, web/src/components/utils/SelectContext/SelectContext.test.tsx, web/src/components/utils/SelectContext/SelectContext.tsx, web/src/components/utils/SelectContext/index.tsx, web/src/pages/ListAlerts/ListAlerts.test.tsx, web/src/pages/ListAlerts/ListAlerts.tsx, web/src/pages/RuleDetails/RuleAlertsListing/RuleAlertsListing.tsx, web/src/pages/RuleDetails/RuleDetails.test.tsx
Currently, when we are using `<SelectionContext>` we expect the developer to pass a list of string identifiers (IDs) to help the context undertand what's selected and what's not selected.
Unfortunately, sometimes we want access to the actual selected object (not just its ID) so that we can show some additional information to the user. With this PR this is now possible, since it extends `SelectionContext` to allow any type to be added to it, opening the door to other work that relates to mass selections.
- Add typings to all selection-related entities
- Extend functions to support all types of selected items
- Update tests
The changes here are as minimal as I could make them, trying to introduce as small of a migration as possible.
The purpose of this change is to allow …
=> [FE][Feat] Allow any type of item in Selection.Context

web/src/components/utils/Autosave/Autosave.tsx
In several forms, we are using a `FormikAutoSave` component that allows the form to auto-submit when values change.
That component doesn't account for initial values and therefore triggers submission on render.
- Added `useRef` for initial mount
- Test some cases that this was apparent.
=> fix: Autosave to skip submit when mounting

deployments/cloud_security.yml, deployments/core.yml, deployments/log_analysis.yml, deployments/web_server.yml, tools/mage/deploy/deploy.go, tools/mage/deploy/template.go, tools/mage/pkg/pkg.go, tools/mage/test/cfn.go
#2524 was a large PR which replaced the `mage` packaging logic. As devs have started using it, there were a few small fixes needed
- The YAML v3 library uses 4 spaces for indentation by default, who knows why. I've lowered it to 2 spaces when writing packaged templates: it takes quite a bit less space and it is easier to see deeply nested CFN settings in the web console
- The `bootstrap` stack still needs to be "packaged" to strip comments or else it will be too large (in enterprise) to deploy directly. This stack cannot have S3 packaging in the old deployment model because it is itself the stack which creates the S3 buckets
- The problem with large numbers being written in scientific notation appears to be resolved in the YAML v3 parser. I've removed all the YAML quotes around large …
=> Minor cleanup for new pkg code

internal/core/logtypesapi/managed_schemas.go
There's was a small bug where the reply of `ListManagedSchemaUpdates` would be `{}` if there were no updates available.
The field should be kept as `omitempty` because we want it to be missing when there is an API error to report.
To work around `omitempty` behavior where empty slices are omitted, the value was changed to be a pointer to a slice.
- Changes the `Releases` field of `ListManagedSchemaUpdatesOutput` to `*[]managedschemas.Release` to get the correct behavior in the API response
- mage test:go
=> Fix empty managed schema release result

api/graphql/schema.graphql, api/lambda/source/models/api.go, api/lambda/source/models/integration.go, deployments/appsync.yml, deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml, go.mod, go.sum, internal/core/source_api/api/check_integration.go, internal/core/source_api/api/check_integration_test.go, internal/core/source_api/api/managed_bucket_notifications.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/testdata/panther-log-analysis-iam-updated.yml, internal/core/source_api/api/utils.go, internal/core/source_api/ddb/items.go, pkg/testutils/awsmocks.go, tools/mage/util/version.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.graphql, web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
This check was missing and is required. Even if the other checks (AssumeRole, GetBucketLocation, DescribeKmsKey) pass, `GetObject` could still fail if the permissions are not correctly set up.
- Add a check for `s3.GetObject`
- unit
- manual e2e with cross-account s3 source
Closes #2586
=> Add GetObject to the health checks for an s3 source

api/graphql/schema.graphql, api/lambda/source/models/api.go, api/lambda/source/models/integration.go, api/lambda/source/models/validator.go, internal/core/source_api/api/check_integration.go, internal/core/source_api/api/get_integration_template.go, internal/core/source_api/api/list_integrations.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/utils.go, internal/core/source_api/ddb/items.go, internal/core/source_api/main/integration_test.go, internal/log_analysis/log_processor/sources/s3_client_cache_test.go, internal/log_analysis/log_processor/sources/s3_test.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts
Users must specify the log processing role that Panther will use for reading s3 files
- Rename `LogProcessingRole` to `LogProcessingRoleARN`
- Added `roleARN` fied in GraphQL models. It is a required field now for creating/updating an s3 integration
- integration tests
=> The log processing role must be now provided by users

deployments/root.yml
`mage master:deploy` failed with:
> 17:00:11	INFO	[deploy]	create CloudFormation stack panther
Error: failed to create change set for stack panther: ValidationError: Parameters: [PythonManagedPolicyArn] must have values
https://github.com/panther-labs/panther/pull/2647 added 2 new root stack parameters, but forgot to set an empty default value for one of them
- Add default value
- `mage master:deploy` (in progress)
=> Add default value for PythonManagedPolicyArn

deployments/root.yml
#2647 introduced a new root stack parameter which is a CommaDelimitedList. That broke root-stack deployment (`mage master:deploy`)
> 18:04:58	ERROR	[deploy]	stack panther: AWS::CloudFormation::Stack LogAnalysis CREATE_FAILED: Value of property Parameters must be an object with String (or simple type) properties
18:04:59	ERROR	[deploy]	stack panther: AWS::CloudFormation::Stack CloudSecurity CREATE_FAILED: Value of property Parameters must be an object with String (or simple type) properties
Error: UPDATE_ROLLBACK_IN_PROGRESS
The CommaDelimitedList is a very awkward type in CloudFormation: it is passed as a string, but referenced as a list. When you pass it to another stack, then, you have to flatten it back to a string.
- Flatten `AssumableRoleArns` to a string before passing to …
=> String join the role arns list to fix root stack

api/graphql/schema.graphql, internal/core/source_api/api/managed_bucket_notifications.go, internal/core/source_api/api/put_integration.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.graphql, web/src/pages/ListLogSources/LogSourceCards/LogSourceCardOptions.tsx
If user opted for Panther-managed bucket notifications, Panther may also create an SNS topic on the user's AWS account.
When user deletes the source, Panther does not delete the topic (it may be re-used). This PR
-  Display the Panther-created SNS topic when an s3 source is deleted
- A small backend refactoring (get Panther queue ARN from api Config)  (by @giorgosp)
- Manually
=> Display the Panther-created SNS topic when an s3 source is deleted

internal/core/analysis_api/handlers/dynamo.go, internal/core/analysis_api/handlers/github.go, internal/core/analysis_api/handlers/update_pack.go, internal/core/analysis_api/handlers/update_pack_test.go, internal/core/analysis_api/main/integration_test.go, pkg/github/github.go
A few issues/items arose in testing:
1. `nameContains` filter wasn't working: added missing ddb columns for lowerid and lowername
2.  Added some guardrails around values returned from github api
3.  `PatchPack`: update and enabled should not be allowed in a single operation.  
4. `PollPack` will now add but _disable_ new detections in a pack
- `nameContains` : added missing ddb columns for lowerid and lowername
- wrapped values in `aws.StringValue` and `aws.BoolValue`
- `PatchPack`: Separate out the enabled status update and the version update into two separate operations. This simplified some of the detection update logic
- `PollPack`: will now add but _disable_ new detections in a pack (vs not adding them at all)
- `mage test:integration`
- `mage test:go`
- manual testing:
<details> …
=> Misc fixes and feedback on pack api

api/graphql/schema.graphql, api/lambda/source/models/api.go, api/lambda/source/models/integration.go, deployments/appsync.yml, internal/core/source_api/api/check_integration.go, internal/core/source_api/api/managed_bucket_notifications.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.graphql, web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx, web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx, web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
Add healthcheck for bucket notifications configuration
- Add a check that checks the bucket notifications are configured properly for the prefixes the user filled in the onboarded s3 source.
- The healthcheck is only run if user has enabled Panther-managed
bucket notifications
- Manual QA:
- Test with empty prefix in the source, multiple prefixes and overlapping prefixes in the source 
- Test source with Panther-managed notifications, healthcheck is displayed
- Test source with manual notification configuration, healthcheck is not displayed
=> Add healthcheck for bucket notifications configuration

api/graphql/schema.graphql, api/lambda/source/models/integration.go, internal/core/source_api/api/check_integration.go, internal/core/source_api/api/delete_integration.go, internal/core/source_api/api/list_integrations.go, internal/core/source_api/api/managed_bucket_notifications.go, internal/core/source_api/api/managed_bucket_notifications_test.go, internal/core/source_api/api/put_integration.go, internal/core/source_api/api/update_integration.go, internal/core/source_api/api/update_integration_test.go, internal/core/source_api/api/utils.go, internal/core/source_api/ddb/items.go, internal/core/source_api/ddb/scan.go, web/__generated__/schema.tsx, web/__tests__/__mocks__/builders.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts, web/src/graphql/fragments/S3LogIntegrationDetails.graphql, web/src/pages/ListLogSources/LogSourceCards/LogSourceCardOptions.tsx
The Panther notifications feature didn't really account for multiple s3 sources for the same bucket. This scenario
would make the feature unusable if some s3 sources would have the same bucket and overlapping prefixes.
Although this might not seem a common scenario, it is currently allowed and we should support it.
- The code that configures bucket notifications now takes into account the s3 prefixes for all the saved sources with the same bucket.
- Don't save the created notifications or the created SNS topic in the db anymore. Assume that a notification is managed by Panther if its name starts with `panther-managed-`
- The healthcheck now becomes green if the prefix defined for a notification is a string prefix of the source's prefix (i.e. we don't require exact equality)
- Preexisting …
=> Managed notifications multiple sources same bucket

internal/core/metrics_api/api/log_processor_metrics.go
Integration tests were failing - and for a good reason. This PR fixes the issue
- Fix metrics issue
- mage test:integration
```
]$ mage test:integration
13:30:19	WARN	[test:integration]	Integration tests will erase all Panther data in account 123456789012 (eu-central-1)
Are you sure you want to continue? (yes|no) yes
ok  	github.com/panther-labs/panther/api/lambda/source/models	0.010s [no tests to run]
ok  	github.com/panther-labs/panther/cmd/opstools/requeue	21.992s
ok  	github.com/panther-labs/panther/cmd/opstools/s3queue	3.332s
ok  	github.com/panther-labs/panther/cmd/opstools/s3sns	1.425s
ok  	github.com/panther-labs/panther/internal/compliance/compliance_api/main	1.468s
ok  	github.com/panther-labs/panther/internal/compliance/resources_api/main	1.939s
ok …
```
=> Fixing integration tests

internal/compliance/snapshot_poller/pollers/aws/cloudtrail.go, internal/compliance/snapshot_poller/pollers/aws/configservice.go, internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go
@s0l0ist reported a bug found in dogfooding/release testing. We were actually tracking this bug already, but did not realize it would affect the release so strongly.
The bug is that if a user configures a region ignore list for a cloud security scan, we will fail to scan all cloudtrails, guard dutys, and config recorders in the account (and log an error) because we use the same region deny list code for generating generic clients. For the other scanners this situation gets handled higher up in the stack, but these three scanners behave slightly differently because they scan all regions for each scan, not just the region requested.
I'm tagging `sync-to-release` since this will affect every user of cloud security that configures region ignore lists, and @s0l0ist said it should be in 1.16.
- …
=> Fix bug in cloud security scanning when a region ignore list is configured

internal/compliance/resources_api/handlers/dynamo.go
In a recentish [PR](https://github.com/panther-labs/panther/pull/2623) I added parallel scanning of the `panther-resources` table. I had spot checked it to make sure it didn't break any existing functionality, but did not do a thorough enough job as @jacknagz found that in some cases when listing resources only a fraction of the resources were being returned.
It turns out that when moving the serial table scanning to parallel table scanning, I did not convert some of the logic properly and so we ended up only taking the first resource on each page of results returned by dynamo in cases where we did not need to include the compliance status of the resource. As far as I can tell, this only occurs when a user updates a policy and it needs to be evaluated against all current resources.
- …
=> Fix resources-table scanning bug

internal/log_analysis/log_processor/common/common.go, internal/log_analysis/log_processor/processor/processor.go, internal/log_analysis/log_processor/sources/s3.go, internal/log_analysis/log_processor/sources/s3_test.go
Asana Task URL: https://app.asana.com/0/1199942399745175/1200013141331018
A recent PR has us ignore s3 event notifications if they have a file size of zero. These files cause us to log errors during processing, and there's no value in processing an empty file anyways so it saves us time and pages.
For CloudTrail logs, instead of configuring S3 event notifications to send to SNS when new objects are written to S3 you can configure the CloudTrail service itself to directly deliver notifications of new data to SNS. This is for some reason I can't remember better than just relying on s3 event notifications directly (more efficient maybe because it groups the s3 keys?). When we process CloudTrail -> SNS notifications, we internally convert them to look like an S3 event notification. When we do …
=> Allow CloudTrail notifications to process

tools/mage/master/publish.go
Trying to publish the release failed with:
> Error: failed to describe https://panther-community-us-east-2.s3.us-east-2.amazonaws.com/v1.16.0/panther.yml : operation error S3: HeadObject, https response error StatusCode: 404, RequestID: TCP2GZEAXG78RESY, HostID: Gjd0uLfwOVkpKyQyuWLhOKgM70nu2EEk1Zx4wzXaTC1iAInVEGgSmyjzkNVFTDFgB7Tm77ypwLo=, api error NotFound: Not Found
We can't check for a strong error type with S3, we just have to look at the msg.
- Fix error msg check
None (release will be published once this merges)
=> Fix not found err check
